### ISSUE TITLE
[Feature : Tour Search View] 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1000]
### What is missing ?

When using MT in Linux and trying to use the tour search feature, I see this message that requires the user to do the search in a separate browser instead of the embedded browser just like when using MT on windows:
![image](https://user-images.githubusercontent.com/25235665/220764187-09367e90-ff50-4985-b7f5-ec00cf06a807.png)

Considering that this message was added back in [February 2015](https://github.com/mytourbook/mytourbook/commit/00e89d882ac5f8049a6296d3350b906227eb1784
) (8 years ago!), is this possible crash still a possibility ?? Or can the tour search be embedded when using Linux ?

**Comment by wolfgang-ch** [comment]
I tested the tour search with the embedded browser in my VM with Ubuntu 20.04 and it didn't crash. Can you also test it in your environment with this commit https://github.com/mytourbook/mytourbook/commit/5d21e6fe5a8e58c8401b4a43d48b1e249a27ca9b

When it works on your PC then I will enable it in 23.3 but make it optional to disable it with a command line parameter

**Comment by FJBDev** [comment]
Thanks, I will try on my Linux (Debian 11.6) and I will report if I experience any crash.

It's a good idea to make it enabled in 23.3 and then after several months, I will know if it crashes since I mostly use MT under Linux

**Comment by FJBDev** [comment]
I tested and so far, I didn't experience any crashes :+1: 

![image](https://user-images.githubusercontent.com/25235665/221439122-60458c3a-ac52-47be-9480-eecec967cf1c.png)

**Comment by FJBDev** [comment]
I have been using the search view in MT on my Linux since 23.3 and have experienced 0 crashes so far 👍
