### ISSUE TITLE
[Bug : Tag Image] Vertical white line

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1001]
### What happened ?

Vertical orientated tag images have a white line on the right side

![image](https://user-images.githubusercontent.com/1283445/221344079-78937f63-8887-4b63-9676-bbf42c4f56c7.png)

![image](https://user-images.githubusercontent.com/1283445/221344280-784bea19-db6e-4d22-b831-a18ce6ae4ad1.png)

### Version

23.3

### System

Windows

**Comment by FJBDev** [comment]
I will investigate this issue

**Comment by FJBDev** [comment]
I've tried with several of my images but I can't reproduce the issue.

![image](https://user-images.githubusercontent.com/25235665/221628330-59be832d-8d08-414b-9532-e65e4efef0ba.png)


Can you provide 1 or 2 images so I can reproduce and investigate the issue ?

**Comment by wolfgang-ch** [comment]
I've sent you these 2 images.

Because the white line is just 1 pixel width, it can depend on the original image pixel width and height that my images have this line and your images not

![image](https://user-images.githubusercontent.com/1283445/221765877-b74658c0-746f-4877-b78a-4c2d0f454bf7.png)

**Comment by wolfgang-ch** [comment]
This issue was a rounding problem which is now fixed.

When the computed value was, e.g. 47.666 then it was rounded up to 48 which caused the white line because the resized image was smaller than the image canvas

![image](https://user-images.githubusercontent.com/1283445/221810971-f849261b-e1f3-4458-a42c-f523705be9ca.png)


![image](https://user-images.githubusercontent.com/1283445/221810382-4943bd5a-4654-467d-9fa6-3e220ede36ed.png)

**Comment by FJBDev** [comment]
> This issue was a rounding problem which is now fixed.
> 
> When the computed value was, e.g. 47.666 then it was rounded up to 48 which caused the white line because the resized image was smaller than the image canvas
> 

That's what I suspected but because I couldn't reproduce it, I couldn't verify it was the actual issue.

However, wouldn't it be better and less "hacky" to, instead of doing - 0.5 to use [Math.floor()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Math.html#i20) ?

That would be : 
`newimageHeight = Math.floor(newimageWidth * imageHeight / (imageWidth * 1f));`

**Comment by wolfgang-ch** [comment]
> That would be :
> `newimageHeight = Math.floor(newimageWidth * imageHeight / (imageWidth * 1f));`

No, it hast to be casted to `int` and then, I think, `Math.floor()` is not necessary

`newimageHeight = (int) (newimageWidth * imageHeight / (imageWidth * 1f));`

**Comment by FJBDev** [comment]
> No, it hast to be casted to `int` and then, I think, `Math.floor()` is not necessary
> 
> `newimageHeight = (int) (newimageWidth * imageHeight / (imageWidth * 1f));`

In this case, `Math.floor()` may not be necessary but I (personally) find it more readable than even substracting `0.5` because it's more obvious the result we're trying to achieve.

**Comment by wolfgang-ch** [comment]
I fixed it with `Math.floor()` because it is better readable
