### ISSUE TITLE
[Bug : Tour Editor] "Recorded Time" and "Paused Time" are wrong when deleting time slices

### ISSUE THREAD

**Issue by GurVJ** [mytourbook/mytourbook#1009]
### What happened ?

When deleting Time slices in Tour editor then :
- Recorded Time is decreased even if it shouldn't 
- Pause Time is not updated.

See the following example :

After the end of an activity I restarted my watch by mistake instead of stopping it definitively and saving it, which I did few seconds later.
![Capture 001_20230308](https://user-images.githubusercontent.com/64196685/223788329-e8dac8d9-00b1-4cb1-8973-a9f4f6900a5e.jpg)

The points #5044, #5045 and #5046 are mistakes
![Capture 002_20230308](https://user-images.githubusercontent.com/64196685/223788356-6fd0d7fb-353f-4929-9d8c-138aad93ffb8.jpg)

So I deleted them :
![Capture 003_20230308](https://user-images.githubusercontent.com/64196685/223788374-cf18a677-823d-4bad-968c-0551cf67b756.jpg)

The Recorded Time has changes even if I actually deleted 3 recorded points (so 3 seconds).
The Pause Time has not decreased even if the duration I deleted is about 5 minutes
![Capture 004_20230308](https://user-images.githubusercontent.com/64196685/223788395-a136c258-244e-44cf-9b00-f75fde76fe7b.jpg)

Do you confirm my thoughts ?

### Version

23.3.0

### System

Windows

**Comment by GurVJ** [comment]
I don't think  that copying Elapsed Time into Recorded Time and Break Time into Paused Time when time slices are deleted would be a good idea. These are different informations.
Wouldn't it be possible to recompute values after deleting time slices as if it was the first time ?

**Comment by wolfgang-ch** [comment]
> Wouldn't it be possible to recompute values after deleting time slices as if it was the first time ?

These values are not computed, they are set on the device when the user is pressing the start/stop/pause buttons

**Comment by GurVJ** [comment]
I thought that pressing Start/Stop buttons were just events and that the counters for each type of time were computed...

In the 22.6.0/1 release notes there was this Bugfix :
![image](https://user-images.githubusercontent.com/64196685/223998903-f647789f-6994-4ca2-b0f3-45bdc591c416.png)

Is it linked ?

**Comment by FJBDev** [comment]
> These values are not computed, they are set on the device when the user is pressing the start/stop/pause buttons
> 

Correct, the "recorded" and "paused" values come directly from the file (here, `fit` I believe). They represent the times where the user used the device or stopped it.

**Comment by FJBDev** [comment]
> The Recorded Time has changes even if I actually deleted 3 recorded points (so 3 seconds). The Pause Time has not decreased even if the duration I deleted is about 5 minutes ![Capture 004_20230308](https://user-images.githubusercontent.com/64196685/223788395-a136c258-244e-44cf-9b00-f75fde76fe7b.jpg)

Maybe it hasn't decreased because the time slices you deleted didn't contain a pause and hence the recorded time was decreased instead.

I don't necessarily see where the issue is though:

You removed 1:30:46 to 1:35:40 =>4:54 

Because the paused time was not changed, I assumed the times you deleted didn't contain a pause.

Original Recorded time 1:24:01 - 4:54 => 1:19:07

**Comment by GurVJ** [comment]
Actually the watch paused at 1:30:46 and restarted at 1:35:38 until 1:35:40, so it means 4:52 of paused time.
If I delete the 3 last time slices then MT removes 4:54 of recorded time and 0:00 of paused time.

But I've just noticed that if I also delete the 1:30:46 time slice then MT recomputes the recorded and paused time so that it removes only 0:03 to recorded time and 4:52 to paused time which is quite correct.
![image](https://user-images.githubusercontent.com/64196685/224055729-34844e06-642e-4c2f-8303-f26598c9ca12.png)

![image](https://user-images.githubusercontent.com/64196685/224055125-24f7a491-487b-4b50-8163-f61651ae7155.png)

**Comment by FJBDev** [comment]
> Actually the watch paused at 1:30:46 and restarted at 1:35:38 until 1:35:40, so it means 4:52 of paused time. If I delete the 3 last time slices then MT removes 4:54 of recorded time and 0:00 of paused time.
> 
> But I've just noticed that if I also delete the 1:30:46 time slice then MT recomputes the recorded and paused time so that it removes only 0:03 to recorded time and 4:52 to paused time which is quite correct. ![image](https://user-images.githubusercontent.com/64196685/224055729-34844e06-642e-4c2f-8303-f26598c9ca12.png)
> 

I guess I'm not sure what your expected times should be, can you elaborate ?

**Comment by GurVJ** [comment]
Actually, in my former example I've stopped the watch at 1h30'46'' (point #5043), then I restarted it (by error) 4'52" later at 1h35'38'' during 2 seconds (saved points #5044, 5045 and 5046).
So in order to correct my error I've deleted points #5044, #5045 and #5046 and I expected that MT removes 2" of recorded time and 4'52" of paused time, which is not the case.
But it seems to be quite OK if I also delete point #5043 (which is quite weird to me).

**Comment by FJBDev** [comment]
@GurVJ 

Do you mind sharing your file so I can investigate further locally ?

**Comment by GurVJ** [comment]
No problem.

**Comment by GurVJ** [comment]
[D37I2032.zip](https://github.com/mytourbook/mytourbook/files/11075945/D37I2032.zip)

**Comment by FJBDev** [comment]
Thank you

**Comment by FJBDev** [comment]
> Actually, in my former example I've stopped the watch at 1h30'46'' (point #5043), then I restarted it (by error) 4'52" later at 1h35'38'' during 2 seconds (saved points #5044, 5045 and 5046). So in order to correct my error I've deleted points #5044, #5045 and #5046 and I expected that MT removes 2" of recorded time and 4'52" of paused time, which is not the case. But it seems to be quite OK if I also delete point #5043 (which is quite weird to me).

Thanks for the file, I was able to test locally and I've deleted points 5046, 5045, 5044, and then 5043 and it seems to me that the elapsed time, paused time, recorded time and pause were updated correctly (see screenshot below)
My understanding is that to correct your error, you should delete all those points and then the proper elapsed time, recorded time and pause time are fixed


![image](https://user-images.githubusercontent.com/25235665/234719690-e6fd78b4-6a72-4ea3-a1b2-7e3d14205634.png)


>But it seems to be quite OK if I also delete point #5043 (which is quite weird to me).

If you don't delete point 5043, then because the pause is connected to it (see the black dot highlighted in red), then the pause is kept

![image](https://user-images.githubusercontent.com/25235665/234720061-8a6464e3-9387-4f68-acc6-929629951e58.png)

**Comment by GurVJ** [comment]
Yes, this the explanation I supposed.
In my example, it is not so disturbing because my GPS points are recorded second per second, so I'm just losing 1 second of my activity. But if my recording period was bigger then it would be annoying.
