### ISSUE TITLE
[Tour Editor] The tag info should be optional and customizable

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1015]
### Discussed in https://github.com/mytourbook/mytourbook/discussions/1014

<div type='discussions-op-text'>

<sup>Originally posted by **Thompson-ongithub** March  9, 2023</sup>
Hello

I just tried the new version of MTB (23.3.0 on Linux) and whilst I was very happy about the use of the embedded browser when searching for tours, it was the revamped tagging system that makes me a bit unhappy.
The reason is that in my setting, it's not only equipment that I'm tagging, but also people I do rides with, so the new tags with photos and hours and miles provides information I don't need (and it takes up way more space) and sometimes even more information, since in difference to the "Tagged Tours"-View where only the selected tour type is calculated, this new feature just adds up all the information of all the tour types (ex. cycling and running), which might be ok when looking at running shoes, but is of no help if I want to know how often / long I've been running with a buddy of mine. 
Is there a way to turn that of (I tried but haven't found one)

Oh, and since I'm talking about tagging: is there a setting to have the tags displayed not in an alphabetical order but grouped by category and within that group alphabetical (should I make a feature request for this)

sorry for moaning about a new feature (otherwise MTB is great!)</div>

**Comment by wolfgang-ch** [comment]
@Thompson-ongithub Can you create a new issue for your request, the topic for this issue is `The tag info should be optional and customizable` which is not what you are requesting

**Comment by Thompson-ongithub** [comment]
of course...

**Comment by wolfgang-ch** [comment]
Tag image and data can be customized in the next version

![image](https://user-images.githubusercontent.com/1283445/224928052-49874c81-f14f-4737-8762-6dbc6771173e.png)


![image](https://user-images.githubusercontent.com/1283445/224928104-542f51c9-6884-496e-a3f6-22b3b631060a.png)
