### ISSUE TITLE
 [2D Map] Referring to Select trackpoint #461 [Feature : Location] 

### ISSUE THREAD

**Issue by stvzldn** [mytourbook/mytourbook#1017]
### What is missing ?

I have tried following the trackpoint selection detailed in https://github.com/mytourbook/mytourbook/issues/461.  My goal is to select a track segment and then use Geo Compare to examine other tours which go through the same segment.

With MT 23.3.0 I find that I can set the R (right) slider any where on the track, but the L (left) slider always reverts to start of the tour.  If I use the Tour Chart to set the L slider and then use the map to set the R slider, the L slider reverts to Tour start.  There needs to be a way to select and pin the L slider using the map.  E.g. right-click on the map and have the tour chart slider options be selectable.
I also find the documentation for #461 to not correspond to the current options for the 2D Map in 23.3.0.
![Image1](https://user-images.githubusercontent.com/106929478/224394985-00a37913-63d7-4719-b282-349dd0c0b083.jpg)
![Image2](https://user-images.githubusercontent.com/106929478/224394989-19f1c4e0-cc90-4e07-a164-68cc849e3a18.jpg)
![Image3](https://user-images.githubusercontent.com/106929478/224394992-6f7a9b1a-bfb8-48c4-bf1a-499a136c736c.jpg)

**Comment by wolfgang-ch** [comment]
With the `<Shift>` key you can select the 2nd slider, see also https://github.com/mytourbook/mytourbook/issues/461#issuecomment-1030856742

**Comment by stvzldn** [comment]
Perfect!  Sorry I did not read close enough, thank you for the hint.
