### ISSUE TITLE
[Bug : Search]  Searching for a tour is no longer possible.

### ISSUE THREAD

**Issue by mluttermoeller2** [mytourbook/mytourbook#1024]
### What happened ?

If I want to search for a tour, that's no longer possible.
Here the steps.

![2023-03-14 08_53_36-Touren Liste - MyTourbook - 23 3 0](https://user-images.githubusercontent.com/127829940/224933878-71c85b7c-1b77-44ba-bf98-ae803f860104.png)

Then I open the browser and it comes up in the browser.
![2023-03-14 08_54_01-MyTourbook - Suchen](https://user-images.githubusercontent.com/127829940/224934128-78a4917e-2c40-4a86-9812-40270c2f304c.png)

In the error log it says here.
![2023-03-14 09_02_15- log - Editor](https://user-images.githubusercontent.com/127829940/224934617-e3ce2f52-36d7-4f4e-b577-9ad97dbb910f.png)

### Version

23.3.0

### System

Windows

### Relevant log output

```shell
!ENTRY net.tourbook.common 4 0 2023-03-14 08:53:46.747
!MESSAGE /dgrid/util/touch.js
404 (Not Found)
 C:\Users\user\.eclipse\1027998707_win32_win32_x86_64\configuration\org.eclipse.osgi\618\0\.cp\WebContent-rel\dgrid\util\touch.js
```

**Comment by wolfgang-ch** [comment]
I just check the tour search in my MT 23.3 and it worked for the embedded or external web browser.

In your MT, it cannot find the file  `C:\Users\user\.eclipse\1027998707_win32_win32_x86_64\configuration\org.eclipse.osgi\618\0\.cp\WebContent-rel\dgrid\util\touch.js` in the file system.

You may try to uninstall MT and reinstall it. When using the windows installer, it will not touch the saved tours and other saved configurations but it should install the missing file.

**Comment by mluttermoeller2** [comment]
I uninstalled and reinstalled MT with the same error.

The directory "util" does not exist at all.
![2023-03-14 10_33_46-dgrid](https://user-images.githubusercontent.com/127829940/224958389-13340cfe-4210-448f-9065-fa868cc95cd8.png)

Important. I also have an Eclipse for Java development on the computer.

Can I perhaps delete the entire "C:\Users\user\.eclipse\1027998707_win32_win32_x86_64" directory after uninstalling and then new install? Is this directory only for the Eclipse from the MT or for all Eclipse environments?

**Comment by wolfgang-ch** [comment]
What happens when you use the embedded browser when searching tours?

**Comment by wolfgang-ch** [comment]
Which files are loaded in the browser?

![image](https://user-images.githubusercontent.com/1283445/224962423-ac5b6cbc-15bb-4c1e-b7ca-eb2ae02c9798.png)

**Comment by mluttermoeller2** [comment]
How is the embedded browser activated? Here are my browser settings.
![2023-03-14 11_25_04-Benutzervorgaben](https://user-images.githubusercontent.com/127829940/224972762-e60f8e86-cacb-4de6-8cfb-062ef99f87f8.png)

When I go to "Directory/Search" this page opens first.
![2023-03-14 11_25_34-](https://user-images.githubusercontent.com/127829940/224973219-83256962-a654-4f69-bb28-5cbe00fef461.png)

Then when I click the url in the page it opens Chrome because this is my default browser.

Here are the loaded files in Chrome and Firefox.
![2023-03-14 11_12_07-](https://user-images.githubusercontent.com/127829940/224973527-83145755-e97d-4726-bc32-dae0c03473cb.png)

![2023-03-14 11_15_03-MyTourbook - Suchen – Mozilla Firefox](https://user-images.githubusercontent.com/127829940/224973556-8b46a7e0-187f-41e6-ae6f-bd67905ce010.png)

**Comment by mluttermoeller2** [comment]
I found it using the embedded browser. You have to click on the magnifying glass :-)

Everything works fine with this. That's perfect and enough for me.
![2023-03-14 11_39_20-Touren Liste - MyTourbook - 23 3 0](https://user-images.githubusercontent.com/127829940/224976211-c1026e8f-342c-4134-96ba-b9c15c59fe83.png)

**Comment by mluttermoeller2** [comment]
Should I close the ticket? Or do you want to test something with me using the external browser?

**Comment by wolfgang-ch** [comment]
I was wondering why you used the external browser. For Linux we activated the embedded browser just in 23.3 https://github.com/mytourbook/mytourbook/issues/1000 but didn't modify any js/html/css resources.

> Or do you want to test something with me using the external browser?

No, the external browser was only implemented because Linux crashed many years ago

> Should I close the ticket? 

I will close it now

**Comment by mluttermoeller2** [comment]
thanks for the very quick help
