### ISSUE TITLE
[Tour Blog] Show tours tags and images

### ISSUE THREAD

**Issue by bern6** [mytourbook/mytourbook#1026]
### What is missing ?

I would like to know if it is possible to display the images also in the Tour Blog.

Thanks

**Comment by wolfgang-ch** [comment]
The `Tour Blog` view is currently not displaying the tour tags and many other tour properties. This could be implemented but it should be optional.

**Comment by FJBDev** [comment]
I have added this feature for 24.1
Here is a preview

![image](https://github.com/mytourbook/mytourbook/assets/25235665/7ea82f7f-a60e-419e-bf02-8cc143acd485)

> This could be implemented but it should be optional.

It can be deactivated by unchecking the option in the slideout:
![image](https://github.com/mytourbook/mytourbook/assets/25235665/ce8f0ee3-7888-4ebd-8ba9-412d5994840a)

**Comment by bern6** [comment]
Great thanks a lot
