### ISSUE TITLE
[Build Failed] Failed test found in:   D:/a/mytourbook-BUILD-autocreated/core/net.tourbook.tests/target/surefire-reports/TEST-cloud.strava.StravaUploaderTests.xml

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1028]
I changed the weather data but don't know how to solve this

![image](https://user-images.githubusercontent.com/1283445/225847173-4610d20f-af74-43b8-9140-c20951e6673f.png)

https://github.com/mytourbook/mytourbook/blob/9d019fc99f79e163c92510c68b1b6ae2eff97c55/bundles/net.tourbook.tests/src/test/cloud/strava/StravaUploaderTests.java#L140

Failure log: https://github.com/mytourbook/mytourbook/actions/runs/4445176849

**Comment by FJBDev** [comment]
Ok, I think I see what's wrong, I will fix it.

**Comment by FJBDev** [comment]
Fixed in this [PR](https://github.com/mytourbook/mytourbook/pull/1031)

**Comment by wolfgang-ch** [comment]
After merging your PR, this test is still failing

**Comment by wolfgang-ch** [comment]
I just run it in the current main branch

![image](https://user-images.githubusercontent.com/1283445/227266484-65944b6f-ad87-4ec9-9151-3e87a1eb6e3f.png)

**Comment by FJBDev** [comment]
My bad, I had forgotten this file in my previous PR.

Fixed in [this PR](https://github.com/mytourbook/mytourbook/pull/1036)
