### ISSUE TITLE
[Bug : Tourchart display] Some information is always on top of *all* windows

### ISSUE THREAD

**Issue by sroller** [mytourbook/mytourbook#1030]
### What happened ?

A small widget with information from the Tourchart is always on top of all other windows.

![image](https://user-images.githubusercontent.com/596136/226151929-a6621bfa-dc1b-4cce-80d8-7886f4dca58a.png)

### Version

23.3.0

### System

Windows

**Comment by wolfgang-ch** [comment]
Slideouts in MT will be always on top of any other windows. The reason is that it could be hidden behind the MT main window. This is also the reason why slidouts have a` X ` button to close them when not needed

**Comment by FJBDev** [comment]
> This is also the reason why slidouts have a`X` button to close them when not needed

Except that clicking on the `X` button doesn't seem to work (see captured video below)

https://github.com/mytourbook/mytourbook/assets/25235665/f8bd8b01-8f5a-4fef-bbaf-209f3a642881

**Comment by wolfgang-ch** [comment]
The tooltip pops up again because you are moving the mouse over the tour chart after pressing the X button

**Comment by wolfgang-ch** [comment]
The tooltip activation is implemented that when you enable this feature, then the tootip is displayed when hovering the tour chart


![image](https://github.com/mytourbook/mytourbook/assets/1283445/1b3febe1-2461-43df-afa7-d4d823425234)
