### ISSUE TITLE
[Feature : Statistics] Include an additional graph with descent as well

### ISSUE THREAD

**Issue by Thompson-ongithub** [mytourbook/mytourbook#1034]
### What is missing ?

Would it be possible to add another graph to the statistics view? Right now it's possible to show distance, altitude, time and tours with altitude being metres uphill. Would it be difficult to add another graph for descent?
Thanks

**Comment by wolfgang-ch** [comment]
>Would it be difficult to add another graph for descent?
I's not difficult but time consuming because the code must be modified in many places

**Comment by FJBDev** [comment]
Some other people have asked [for it](https://github.com/isaacs/github/issues/1533)

**Comment by wolfgang-ch** [comment]
This feature will be available in the next version

![image](https://github.com/mytourbook/mytourbook/assets/1283445/66bd639d-85af-448d-a712-c583e90493e7)

**Comment by Thompson-ongithub** [comment]
Thank you!

**Comment by bjberlin** [comment]
Hi Wolfgang,
thank you for your post in my Q&A, the link right to this thread and of course the developing :-)

I'm looking for statistics about time and distance going uphill and going downhill - by trip/track or by tour.
Do you think this will be available in a later version as well? 

I am hiking a lot - right back from Kanton Uri :-). Actually I'm using the sliders and take the delta (left/right) and sum up for each trip to have this information.

Björn

**Comment by wolfgang-ch** [comment]
> I'm looking for statistics about time and distance going uphill and going downhill - by trip/track or by tour. Do you think this will be available in a later version as well?

Can you create a separate feature request

> I am hiking a lot - right back from Kanton Uri :-). Actually I'm using the sliders and take the delta (left/right) and sum up for each trip to have this information.

Are you using the tour segmenter?
