### ISSUE TITLE
[Bug : Tour Tags] 

### ISSUE THREAD

**Issue by bern6** [mytourbook/mytourbook#1037]
### What happened ?

Name and data, the font is white, with the same theme.

23.3.0
![Mytourbook-23 3 0](https://user-images.githubusercontent.com/103836286/227509631-b94f682a-d3b7-4ae0-9ced-7229ae6a74e5.png)
23.3.1
![Mytourbook-23 3 1](https://user-images.githubusercontent.com/103836286/227509724-b844107a-dd72-4cec-a6b6-8c2353f9600c.png)

### Version

23.3.1

### System

Linux

**Comment by wolfgang-ch** [comment]
Before I released 23.3.1, I checked Win/Linux with dark/bright theme and all were OK

This is from my Ubuntu in a VM

![image](https://user-images.githubusercontent.com/1283445/227535855-2c2aa40e-a2b2-46a5-a7f2-a82cacb6731d.png)

**Comment by FJBDev** [comment]
It works on my Debian 11.6

![image](https://user-images.githubusercontent.com/25235665/227536057-cbdd5ef6-adaa-422d-a61d-b2f0dcd90ec9.png)

**Comment by FJBDev** [comment]
@bern6  Which theme are you using ?

 I am using the "System" theme

![image](https://user-images.githubusercontent.com/25235665/227536834-4baa7aba-5215-4a96-94ca-b3b91673b974.png)

**Comment by wolfgang-ch** [comment]
My system theme

![system-theme](https://user-images.githubusercontent.com/1283445/227537864-0bbb792e-22da-4493-838a-44b6d15edd11.png)

My classic theme

![classic-theme](https://user-images.githubusercontent.com/1283445/227538040-06e8104c-0a7a-4687-91de-1b2ff5f75aa7.png)

**Comment by FJBDev** [comment]
@bern6  Is there any entry in the error log ?

**Comment by wolfgang-ch** [comment]
@bern6 Can you test the `Text Width`, it cannot be set to 0 which would hide the text

![image](https://user-images.githubusercontent.com/1283445/227590116-73cc3626-9a3b-4151-aa22-8103310ae3ae.png)

**Comment by bern6** [comment]
Yes Wolfgang, width to 150 and it displays the text.
great thanks.

Text width 150

![Witdh 150](https://user-images.githubusercontent.com/103836286/227593152-151f4df1-244a-419d-a496-fd9ed78aca9c.png)

**Comment by bern6** [comment]
Rectification, with the default theme gnome-shell  it works.
