### ISSUE TITLE
[Bug : Import Weather Data] Error while retrieving the weather data: "null"

### ISSUE THREAD

**Issue by cyc1ingsir** [mytourbook/mytourbook#1053]
### What happened ?

Finally, I tested the import of weather data I had no look. Neither "OpenWeatherMap" nor "Weather API" had data for my tour.
The first tour I tested was from the previous day of the import. The second tour was just from one hour ago. 
![image](https://user-images.githubusercontent.com/2297037/229571399-f0ff27c6-4e18-416c-8aba-4f9a1512e7da.png)
I haven't checked if any of the providers offer weather data for my region (Northern half of Germany).

### Version

23.3.2

### System

Linux

### Relevant log output

```shell
[TourLog] 18:21:47 [main - 1                 ] 3              2. Imported in 1.514 s
[TourLog] 18:21:47 [main - 1                 ] 4              3. Set tour types
[TourLog] 18:21:47 [main - 1                 ] 5                 4/3/2023, 2:20 PM - Training (Revolutions per Minute (rpm))
[TourLog] 18:21:47 [main - 1                 ] 6              5. Adjust tour start temperature values - 3 minutes < 10.0 ?C
[TourLog] 18:21:47 [main - 1                 ] 7     OK          4/3/2023, 2:20 PM . . . 9.62 ? 9.58 . . . -0.04 ? ?C
[TourLog] 18:21:47 [main - 1                 ] 8              7. Replace elevation up/down total values from SRTM data
[TourLog] 18:21:47 [Worker-0: N52E010.SRTMGL3.hgt.zip - Download from HTTP server - 30] 9     INFO     Downloading https://e4ftl01.cr.usgs.gov/MEASURES/SRTMGL3.003/2000.02.11/N52E010.SRTMGL3.hgt.zip
[TourLog] 18:21:53 [main - 1                 ] 10                4/3/2023, 2:20 PM - Up: 116 ?   214 - Down: 129 ? 216
[TourLog] 18:21:53 [main - 1                 ] 11             50. Retrieve Weather Data
[TourLog] 18:21:53 [main - 1                 ] 12    INFO        Retrieving weather data with "OpenWeatherMap"
[TourLog] 18:21:54 [main - 1                 ] 13    ERROR       4/3/2023, 2:20 PM -> Error while retrieving the weather data: "null"
[TourLog] 18:21:54 [main - 1                 ] 14    INFO        4/3/2023, 2:20 PM . . . Weather data not found
[TourLog] 18:21:54 [main - 1                 ] 15    INFO        Data retrieved in 0.1 s
[TourLog] 18:21:54 [main - 1                 ] 16             Easy import end, 8.401 s
```

**Comment by cyc1ingsir** [comment]
Additional info.
When clicking the button [Test vendor's connection] inside the preferences. I discovered this exception been thrown in the log:
```
!ENTRY net.tourbook.common 4 0 2023-04-03 18:32:59.526
!MESSAGE InterruptedException
!STACK 0
java.lang.InterruptedException
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:550)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
        at net.tourbook.weather.HistoricalWeatherRetriever.lambda$0(HistoricalWeatherRetriever.java:74)
        at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
        at net.tourbook.weather.HistoricalWeatherRetriever.checkVendorConnection(HistoricalWeatherRetriever.java:65)
        at net.tourbook.ui.views.WeatherProvider_OpenWeatherMap.lambda$1(WeatherProvider_OpenWeatherMap.java:86)
        at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
        at org.eclipse.jface.window.Window.open(Window.java:799)
        at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
        at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
        at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
        at net.tourbook.application.Application.start(Application.java:35)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by FJBDev** [comment]
Thanks for all the detailed information.

I can' reproduce the issue locally.
Can you try with the other provider `WeatherApi` to see if you encounter the same issue ?

![image](https://user-images.githubusercontent.com/25235665/229583594-028bb40d-700a-4ddf-916a-52ddf7aedadd.png)

![image](https://user-images.githubusercontent.com/25235665/229583667-6a407b33-2804-4d2b-b9e8-722364481070.png)

**Comment by cyc1ingsir** [comment]
No, firefewall, not proxy, the machine is directly connected to the internet.
However, this part of the log puzzles me:
```
Caused by: java.nio.channels.UnresolvedAddressException
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
```
I couldn't figure out which address is actually tried to be resolved via a quick grep though the source code. 
Maybe, you could enlighten me.
DNS is basically working.
```bash
host openweathermap.org
openweathermap.org has address 138.201.197.100
```

sure, I can send you the tour's FIT file but I'd rather not make it public. I don't think, you will receive Mails sent to the eMail-Adress, you sign off your commits with, do you?

**Comment by FJBDev** [comment]
> I couldn't figure out which address is actually tried to be resolved via a quick grep though the source code. Maybe, you could enlighten me. DNS is basically working.
> 
> ```shell
> host openweathermap.org
> openweathermap.org has address 138.201.197.100
> ```
> 

Well, MT doesn't send requests directly to OpenWeatherMap but uses a program "in the middle" as we need to pass an API key to OpenWeatherMap & WeatherAPI.
The address for OpenWeatherMap  is [here](https://github.com/mytourbook/mytourbook/blob/568422a6d0dadbd2971cec269a17c72c140341e4/bundles/net.tourbook/src/net/tourbook/weather/openweathermap/OpenWeatherMapRetriever.java#L43)


> sure, I can send you the tour's FIT file but I'd rather not make it public. I don't think, you will receive Mails sent to the eMail-Adress, you sign off your commits with, do you?

No need to send me your private FIT.
Here is what you can do instead. Take one of those [public FIT files](https://github.com/mytourbook/mytourbook/tree/main/bundles/net.tourbook.tests/src/test/device/garmin/fit/files), set them to a recent date in MT (less than 5 days from today) and try to request the weather and see if it's successful.

**Comment by FJBDev** [comment]
One more thing: 
Was it working before ? If yes, when did it stop working ?
Otherwise, is it the first time you use this feature implemented back in [2019 ](https://mytourbook.sourceforge.io/mytourbook/index.php/history/history-2019#v19.7.0)?

**Comment by FJBDev** [comment]
> I couldn't figure out which address is actually tried to be resolved via a quick grep though the source code. Maybe, you could enlighten me. DNS is basically working.
> 
> ```shell
> host openweathermap.org
> openweathermap.org has address 138.201.197.100
> ```
> 

You could also test if that works locally using either [curl ](https://curl.se/docs/manpage.html)or [postman ](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwivxsz4vo7-AhUPAjQIHXypASMQFnoECAkQAQ&url=https%3A%2F%2Fwww.postman.com%2F&usg=AOvVaw05sjAjE_hbftSn2Ii8YG6N)for example:
`https://passeur-mytourbook-oauthapps.cyclic.app/weatherapi?lat=40.263996&lon=-105.58854099999999&dt=2023-04-03&lang=fr`

**Comment by cyc1ingsir** [comment]
I never used this feature before. I could have sworn to have seen some discussions about it prior to version 22.10.
Anyway, is this an URL which should resolve:
https://github.com/mytourbook/mytourbook/blob/568422a6d0dadbd2971cec269a17c72c140341e4/bundles/net.tourbook/src/net/tourbook/weather/WeatherUtils.java#L37
I had found it before and wondered if that's just some sort of an identifier. 
```bash
host passeur-mytourbook-oauthapps.cyclic.app
Host passeur-mytourbook-oauthapps.cyclic.app not found: 3(NXDOMAIN)
```
For some reason, I can't find where I can initiate the weather data request from (I always thought, that's connected to the easy import which I never used before either)>

O, I might have discovered it:
![image](https://user-images.githubusercontent.com/2297037/229613262-5e8957a7-3f5b-40a3-b3a7-5abff210963f.png)

However, no success either.
[errorlog.zip](https://github.com/mytourbook/mytourbook/files/11142031/errorlog.zip)

When saving a tour I had some strange SQL errors a couple of times. That's new.

**Comment by cyc1ingsir** [comment]
> You could also test if that works locally using either [curl ](https://curl.se/docs/manpage.html)or [postman ](https://www.postman.com/)for example:
I'm using [HTTPie](https://httpie.io/) at work a lot. Tested it using curl, just to be sure but for some strange reason.
[It's always DNS!](https://duckduckgo.com/?q=it%27s+always+DNS&t=ffab&iar=images&iax=images&ia=images) but why?
:thinking: 

```bash
 http -v https://passeur-mytourbook-oauthapps.cyclic.app/weatherapi?lat=40.263996&lon=-105.58854099999999&dt=2023-04-03&lang=fr
[2] 16892
[3] 16893
[4] 16894
[3]-  Done                    lon=-105.58854099999999
[4]+  Done                    dt=2023-04-03
moppel@thinktraveler:~/Programs/mytourbook> GET /weatherapi?lat=40.263996 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Host: passeur-mytourbook-oauthapps.cyclic.app
User-Agent: HTTPie/2.6.0


http: error: ConnectionError: HTTPSConnectionPool(host='passeur-mytourbook-oauthapps.cyclic.app', port=443): Max retries exceeded with url: /weatherapi?lat=40.263996 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7feff98a6890>: Failed to establish a new connection: [Errno -2] Name or service not known')) while doing a GET request to URL: https://passeur-mytourbook-oauthapps.cyclic.app/weatherapi?lat=40.263996

```

**Comment by cyc1ingsir** [comment]
:tada: 
![image](https://user-images.githubusercontent.com/2297037/229616888-9e9beffc-7c2f-421b-a80d-ca0b653668fd.png)
Thanks for all your help!
I've tested it, connecting the laptop to a tethering hotspot on my phone, hence with different DNS settings.
Doing so, it works.
The `app` top level domain rings some faint bell. I must have setup some manual DNS rule when running a test Kubernets cluster on my Rapis. This could be related but I have to look closer into this tomorrow.
Anyway. It's a local problem. Thanks for all your effort!

**Comment by FJBDev** [comment]
Good to know you have found some culprit. And hence why i asked if you had a firewall or anything that would prevent from the request going through.

**Comment by cyc1ingsir** [comment]
Oh no!
https://www.quad9.net/result?url=passeur-mytourbook-oauthapps.cyclic.app
![image](https://user-images.githubusercontent.com/2297037/229733465-93702665-f6d6-42b2-9622-5b8c794c54f5.png)

I've contacted the support, requesting the URL to be removed from the block list.

**Comment by FJBDev** [comment]
> It's even more complicated! I'm using the independent Swiss based DNS Resolver Quad9. Look at this:

Ok, so you're not really directly connected to the internet like you mentioned above, you have something "in the middle" that prevents the MT requests from being successful

**Comment by FJBDev** [comment]
> I've contacted the support, requesting the URL to be removed from the block list.

Weird, I'm not sure why they would block [cyclic](https://www.cyclic.sh/). I'm not sure Cyclic has anything malicious but hopefully they can help you.
Good luck!

**Comment by cyc1ingsir** [comment]
The Quad9 support sent an answer on my request to remove "[passeur-mytourbook-oauthapps.cyclic.app](https://www.quad9.net/result?url=passeur-mytourbook-oauthapps.cyclic.app)" from the block list:
It seems, the complete "cycling.app" domain is blocked (Firefox warns me too about a certificate mismatch, if I try to connect to https://cycling.app/).
The certificate seems to be issued by Let's Encrcypt to  another site (skoora____ dot com) `openssl s_client -showcerts cycling.app:443`
`openssl s_client -showcerts passeur-mytourbook-oauthapps.cyclic.app:443` returns a better result but the 'listed' parent domain doesn't help.

>Hello,

>Thanks for contacting Quad9 support.

>This domain is listed on at least 7 threat lists:
>https://www.virustotal.com/gui/url/fe13bee6519aa5e26303ad0dfa3a4d7a5c7ce0cb0bce72661b6c68f83ee68987?nocache=1
>https://exchange.xforce.ibmcloud.com/url/cyclic.app

>We recommend informing the service, so they can take steps to get the domain removed from these various lists after >removing any malicious files and/or claiming a false positive.

>The threat lists can be contacted via 

>IBM X-Force: https://exchange.xforce.ibmcloud.com/url/cyclic.app (Suggest an Edit)
>CRDF: https://threatcenter.crdf.fr/false_positive.html
>Emsisoft: [fp@emsisoft.com](mailto:fp@emsisoft.com)
>Lionic: [support@lionic.com](mailto:support@lionic.com)
>CyRadar: https://cyradar.com/contact/
>Heimdal Security: [support@heimdalsecurity.com](mailto:support@heimdalsecurity.com)
>Netcraft: https://report.netcraft.com/report/mistake

>Once the domain is removed from IBM X-Force, it will automatically be removed from the Quad9 blocklist within 8 hours. >However, we'd strongly recommend that the service take the steps to get the domain removed from all the above-mentioned threat lists.

**Comment by cyc1ingsir** [comment]
Weird, I'm not sure why they would block [cyclic](https://www.cyclic.sh/).  `cyclic do sh` isn't blocked. `cycling dot app` is.

**Comment by FJBDev** [comment]
>It seems, the complete "cycling.app" domain is blocked

The actual service URL is [cyclic.sh](https://cyclic.sh/) and their certificate is valid. The `cyclic.app` is only a suffix for the deployed apps

**Comment by cyc1ingsir** [comment]
> The cyclic.app is only a suffix for the deployed apps
Well, in that case, someone at cycling must probably have misconfigured something. 
![image](https://user-images.githubusercontent.com/2297037/229848772-418e9997-6f0a-486a-a94d-929a26a797c2.png)

**Comment by cyc1ingsir** [comment]
>And you have the name of the service wrong, it's cyclic.sh not cycling.sh
You are correct, my bad. The certificate to cyclic.app looks alright. (Even if nobody is using it directly, it's still reachable.)

One might argue, the whole blocking thing is snake oil.
Especially if the whole domain is being blocked. Someone _might_ have used (is using) the cyclic.sh service to distribute malware via a subdomain of cyclic.app. As a result of this IBM X-Force, CRDF and all the others added _all subdomains of_ cyclic.app on the threat list. In the end, it's bad for business for such hosting providers.
I'm really sorry to have bothered you with this. I've taken my learning.

**Comment by FJBDev** [comment]
> One might argue, the whole blocking thing is snake oil. Especially if the whole domain is being blocked. Someone _might_ have used (is using) the cyclic.sh service to distribute malware via a subdomain of cyclic.app. As a result of this IBM X-Force, CRDF and all the others added _all subdomains of_ cyclic.app on the threat list. In the end, it's bad for business for such hosting providers. I'm really sorry to have bothered you with this. I've taken my learning.

Who knows, it's possible that some users might have used it incorrectly but I can tell you that the one we use for MT is legit 😄
