### ISSUE TITLE
Easy Import auf MAC nicht möglich

### ISSUE THREAD

**Issue by Th-Klein** [mytourbook/mytourbook#1058]
### What happened ?

ich habe nach dem Umstieg auf einen MacBook Pro mit der Anleitung im Forum Mytourbook zu laufen gebracht. Es funktioniert alles bis auf den easy Import. Die Daten werden im grünen Feld angezeigt, allerdings erfolgt beim aktivieren des Butten Start Import keine Reaktion. >Auch wenn kein Support für MacOs existiert wäre ich für eine Hilfestellung dankbar. Ich verwende MACOS Ventura 13.3. 
!![ Bildschirmfoto 2023-04-05 um 17 15 10](https://user-images.githubusercontent.com/129975975/230383595-e89006d4-ee8d-4460-97e9-7c68426d7f15.png) ![ Bildschirmfoto 2023-04-05 um 17 14 50](https://user-images.githubusercontent.com/129975975/230383614-e9e937f1-b068-4b16-afcd-27671715028d.png) 

### Version

23.3.2

### System

OSX

**Comment by wolfgang-ch** [comment]
There is another easy import issue https://github.com/mytourbook/mytourbook/issues/982 where the launch of an easy import is not possible. 

I'm planning to implement an alternative easy import launcher with simple SWT widgets and not with the browser as UI, however it will not look so fancy.

**Comment by wolfgang-ch** [comment]
Implemented an alternative easy import UI https://github.com/mytourbook/mytourbook/issues/1065
