### ISSUE TITLE
[Simple Easy Import] Easy Import with a simple UI

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1065]
### What is missing ?

Sometimes the easy import UI is not working because there are some browser issues, e.g. https://github.com/mytourbook/mytourbook/issues/982 or https://github.com/mytourbook/mytourbook/issues/1058.

This new easy import UI is using just simple SWT controls to start the easy import launcher.

**Comment by wolfgang-ch** [comment]
Here is a first glimpse of the new UI which has currently no functionality, there are still a lot of things to implement and fix.

![image](https://user-images.githubusercontent.com/1283445/232098720-369b3e2d-bf18-4d5c-aa49-bad841ffdd05.png)

![image](https://user-images.githubusercontent.com/1283445/232098756-75067b49-ebc4-4f04-8c8c-7ae73a23e5f4.png)

**Comment by FJBDev** [comment]
I actually like the browser version and have been using it since 2018 without encountering the known issues (maybe because I mainly use Linux?). Is it possible to keep it for people (like me) that want to continue using it ?

**Comment by wolfgang-ch** [comment]
> Is it possible to keep it for people (like me) that want to continue using it ?

It was not intended to remove the existing browser UI, I'm adding the "Simple Easy Import"

**Comment by wolfgang-ch** [comment]
The state window can be kept open with the new simple easy import UI, this picture shows the similarity of both UI's

![image](https://user-images.githubusercontent.com/1283445/233118633-f05da321-7ce2-4102-81f0-a4eb1769f650.png)

State window with an error

![image](https://user-images.githubusercontent.com/1283445/233118708-5068571c-da30-48cc-970e-6f763218e8bc.png)

State window without an error

![image](https://user-images.githubusercontent.com/1283445/233118796-803d9412-5014-4dde-98c5-2cea9a68cf7f.png)
