### ISSUE TITLE
[Feature : Weather Retriever] Skip weather retrieval when out of the allowed range

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1076]
### What is missing ?

Weather data should not be retrieved when it is out of the allowed range.

The easy import could be considerable be faster when weather data are only retrieved for the allowed date range, in this case all retrieval were not allowed but had to wait 8 seconds.

The weather text should also not be filles with 0 values, interresting is, that air quality seems to be set to a value other than 0

```
50. Retrieve Weather Data 
Retrieving weather data with "OpenWeatherMap" 
28/03/2023, -> Error while retrieving the weather data: "{"cod":"400","message":"requested time is out of allowed range of 5 days back"}" 
28/03/2023, avg. 0.00°C, min. 0.00°C, max. 0.00°C, feels like 0.00°C, air quality Moderate 
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 3
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 3 

04/04/2023, -> Error while retrieving the weather data: "{"cod":"400","message":"requested time is out of allowed range of 5 days back"}" 
04/04/2023, avg. 0.00°C, min. 0.00°C, max. 0.00°C, feels like 0.00°C, air quality Moderate 
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 3 

03/04/2023, -> Error while retrieving the weather data: "{"cod":"400","message":"requested time is out of allowed range of 5 days back"}" 
03/04/2023, avg. 0.00°C, min. 0.00°C, max. 0.00°C, feels like 0.00°C, air quality Fair 
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2 

03/04/2023, -> Error while retrieving the weather data: "{"cod":"400","message":"requested time is out of allowed range of 5 days back"}" 
03/04/2023, avg. 0.00°C, min. 0.00°C, max. 0.00°C, feels like 0.00°C, air quality Fair 
13h 0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2 

06/04/2023, -> Error while retrieving the weather data: "{"cod":"400","message":"requested time is out of allowed range of 5 days back"}" 
06/04/2023, avg. 0.00°C, min. 0.00°C, max. 0.00°C, feels like 0.00°C, air quality Fair 
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2 

28/03/2023, -> Error while retrieving the weather data: "{"cod":"400","message":"requested time is out of allowed range of 5 days back"}" 
28/03/2023, avg. 0.00°C, min. 0.00°C, max. 0.00°C, feels like 0.00°C, air quality Fair 
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 1
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 1
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2 

30/03/2023, -> Error while retrieving the weather data: "{"cod":"400","message":"requested time is out of allowed range of 5 days back"}" 
30/03/2023, avg. 0.00°C, min. 0.00°C, max. 0.00°C, feels like 0.00°C, air quality Good 
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 1
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 1
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 1 

27/03/2023, -> Error while retrieving the weather data: "{"cod":"400","message":"requested time is out of allowed range of 5 days back"}" 
27/03/2023, avg. 0.00°C, min. 0.00°C, max. 0.00°C, feels like 0.00°C, air quality Fair 
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2 

26/03/2023, -> Error while retrieving the weather data: "{"cod":"400","message":"requested time is out of allowed range of 5 days back"}" 
26/03/2023, avg. 0.00°C, min. 0.00°C, max. 0.00°C, feels like 0.00°C, air quality Fair 
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 2 

02/04/2023, -> Error while retrieving the weather data: "{"cod":"400","message":"requested time is out of allowed range of 5 days back"}" 
02/04/2023, avg. 0.00°C, min. 0.00°C, max. 0.00°C, feels like 0.00°C, air quality Good 
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 1
0.00°C feels like 0.00°C 0.00km/h from 0° humidity 0% pressure 0.0mbar precipitation 0.0mm snowfall 0.0mm air quality 1 
Data retrieved in 8.3 s 

```

**Comment by wolfgang-ch** [comment]
Because of setting the weather data to 0 values when they are not available , this should be fixed in the next version that the weather description is not overwritten

**Comment by FJBDev** [comment]
> Because of setting the weather data to 0 values when they are not available , this should be fixed in the next version that the weather description is not overwritten

In which case are you seeing this?
Because if the weather data was not retrieved, the values are unchanged like [here](https://github.com/mytourbook/mytourbook/blob/60035ec2d53168277283f6609b79de291c86962e/bundles/net.tourbook/src/net/tourbook/weather/openweathermap/OpenWeatherMapRetriever.java#L385)

**Comment by wolfgang-ch** [comment]
The last word "overwritten" is misleading and wrong, it happens when I delete tours in MT and import it with easy import. I'm currently testing the additional simple easy import UI and then it happens. 

Below is a test with the fit file which I had send to your, first I deleted this tour in MT, then imported it, 0 values all over the place

![image](https://user-images.githubusercontent.com/1283445/233821124-43252a8a-ee71-4253-9e80-1a3f84c385f8.png)

**Comment by FJBDev** [comment]
> The last word "overwritten" is misleading and wrong, it happens when I delete tours in MT and import it with easy import. I'm currently testing the additional simple easy import UI and then it happens.
> 
> Below is a test with the fit file which I had send to your, first I deleted this tour in MT, then imported it, 0 values all over the place
> 

The image explains it better.
Indeed, it has 0 values "all over the place", but those values are not written to the tour.
In my previous [PR](https://github.com/mytourbook/mytourbook/pull/1048), I added the air quality retrieval for OpenWeatherMap. Since OWM supports air quality retrieval from 11/2020 but full weather retrieval only for the last 5 days, your tour being more than 5 days old, but not older than 11/2020, the air retrieval still happened but ONLY the air quality value was written in the tour.
However, because the OpenWeather weather retrieval is common code for the hourly values, this is why you see the 0 values. Note that you also see the line in the log where it says that the weather temperature, description...etc was not retrieved because the tour's date is more than 5 days

I hope that helps clarify

![image](https://user-images.githubusercontent.com/25235665/233879273-7a810f12-15c6-4746-a167-46a47fec3efa.png)

**Comment by FJBDev** [comment]
The title of your issue is "Skip weather retrieval when out of the allowed range"

Because for OpenWeatherMap the air quality goes until November 27 2020, it should go back to this date. At least, when I designed the air quality retrieval, it's also because i wanted to retrieve the air quality as far back as possible

**Comment by wolfgang-ch** [comment]
This explains my above discovery "...interresting is, that air quality seems to be set to a value other than 0"

After knowing that air quality can be retrieved for more than 5 days and the other weather data only for the last 5 days, I would suggest this solution:

Write into the weather history field only the air quality when the other weather data cannot be retieved and don't fill it with 0 values.

I'll improve the tour info tooltip that a default width can be set and the weather text values are not too often wrapped.

**Comment by wolfgang-ch** [comment]
Are you fixing this, that the red marked area with the zeros are not saved/displayed ?

![image](https://user-images.githubusercontent.com/1283445/235358421-cd75249d-1be3-46ae-9686-2ef77afb5683.png)

**Comment by FJBDev** [comment]
> Are you fixing this, that the red marked area with the zeros are not saved/displayed ?

Yes, but i haven't fixed it yet. Do you need to have it fixed by a specific date soon?

**Comment by wolfgang-ch** [comment]
> > Are you fixing this, that the red marked area with the zeros are not saved/displayed ?
> 
> Yes, but i haven't fixed it yet. Do you need to have it fixed by a specific date soon?

No, just for the next version

**Comment by FJBDev** [comment]
> No, just for the next version

When is the next version?

**Comment by FJBDev** [comment]
This is fixed and available in this [PR](https://github.com/mytourbook/mytourbook/pull/1083)

**Comment by wolfgang-ch** [comment]
> > No, just for the next version
> 
> When is the next version?

There is no plan for the next version, it happens mostly spontaneous or after I've finished a larger part.

**Comment by wolfgang-ch** [comment]
> This is fixed and available in this [PR](https://github.com/mytourbook/mytourbook/pull/1083)

Now it looks a little bit empty 😄 

![image](https://user-images.githubusercontent.com/1283445/235412885-e8694ef7-85de-4665-9bc2-51e64aab23d3.png)
