### ISSUE TITLE
[Feature : Reference tours view] 

### ISSUE THREAD

**Issue by Piff91** [mytourbook/mytourbook#1086]
Column VAM and max pulse

I wonder if it is possible to insert the following columns:

- Pulse max
- VAM

Thanks

**Comment by wolfgang-ch** [comment]
Will be available in the next version

![image](https://user-images.githubusercontent.com/1283445/236248589-e189271f-17a6-4ac1-acf2-59564f6adb40.png)

**Comment by Piff91** [comment]
Super, danke.
