### ISSUE TITLE
[JUnit Test Failed] Connection test filed

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1092]
### What happened ?

https://github.com/mytourbook/mytourbook/actions/runs/4890985645

![image](https://user-images.githubusercontent.com/1283445/236606054-354b7196-a504-4456-ac40-22a299ea48e3.png)

### Version

23.next

### System

All

**Comment by FJBDev** [comment]
I saw the failed build yesterday but when I saw that it was an internet connection issue, I re-ran the build and it succeeded.
Because some tests rely on internet, sometimes there can be issues that make the tests fail.
