### ISSUE TITLE
[SwitchButton] This nebula control is not accessable with the keyboard

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1099]
The newly intotruced `SwitchButton`'s can only be selected with the mouse, even with the `<Tab>` key it cannot be accessed. So this control should be replaced with the old checkbox with it's mnemonic.

https://github.com/mytourbook/mytourbook/blob/614b5ee3708c99ac53880435c934d291a4afb8a8/bundles/net.tourbook.cloud/src/net/tourbook/cloud/strava/PrefPageStrava.java#L265

Nebula controls must not have the full SWT quality, they look good but I already discovered that not all are accessable. I had the same experiences with JavaScript UI framesworks, you can use them with the mouse but mostly not with the keyboard.

**Comment by FJBDev** [comment]
Ok, I will revert

**Comment by FJBDev** [comment]
Reverted in [this PR](https://github.com/mytourbook/mytourbook/pull/1097)

It's too bad the they release "half-baked" widgets that look better than the good working original ones

![image](https://github.com/mytourbook/mytourbook/assets/25235665/ea349b63-910c-481b-9556-ad52d654c34d)
