### ISSUE TITLE
[Feature : Tour Blog View] Detect http links in the tour description to make them clickable 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1102]
### What is missing ?

When a tour description contains an http link, the Tour Blog View should detect them and make them clickable.

Idea: Wrap the `http` text in a `<a href` tag ?

**As of 23.5**
![image](https://github.com/mytourbook/mytourbook/assets/25235665/8240d483-9e79-4404-a66d-e249277f515b)

The link that should be displayed instead:
![image](https://github.com/mytourbook/mytourbook/assets/25235665/a382a009-aac3-4bb5-b29c-44b340e356cd)

**Comment by mff73** [comment]
Nice idea.
I would immediately think about another idea linked to this one. Example of an activity downloaded from Suunto cloud, MTB could automatically create a link into this tour description with link to this suunto online activity. 😋

**Comment by FJBDev** [comment]
> Nice idea. I would immediately think about another idea linked to this one. Example of an activity downloaded from Suunto cloud, MTB could automatically create a link into this tour description with link to this suunto online activity. 😋

That is a bit different and out of scope though. Can you create a separate feature request ?
Also, not sure that Suunto API gives the activity link even for public activities but I can investigate

**Comment by mff73** [comment]
Of course. Suunto API may not give the activity link, but it can be easily built with username and activity Id 😉.

**Comment by FJBDev** [comment]
> Of course. Suunto API may not give the activity link, but it can be easily built with username and activity Id 😉.

I wouldn't say it's easy since the activity ID is not in the FIT file and because saving the FIT file is independent  and disconnected from importing the FIT file and therefore when importing the FIT file, we don't necessarily know the ID anymore.

**Comment by mff73** [comment]
Hi Fred, sorry, my answers are too short, not detailed and, at the end, not fully relevant to this particular idea. I will open a new topic to explain deeper (but this idea is really nice 😊)

**Comment by wolfgang-ch** [comment]
Is available in the next version

![image](https://github.com/mytourbook/mytourbook/assets/1283445/a8399af6-c22a-46d4-b296-be4d67484935)

**Comment by FJBDev** [comment]
Should those types of URL formats be made clickable too ?

![image](https://github.com/mytourbook/mytourbook/assets/25235665/fea067c4-d1bf-47a7-a419-06cdbd2c9964)

**Comment by wolfgang-ch** [comment]
I think that it is difficult (for me) to define a regex expression to detect all possible URL formats or parts of them. But I don't stop you to extend the regex expression 😄

**Comment by FJBDev** [comment]
It seems that [this library](https://github.com/linkedin/URL-Detector) supports it

**Comment by FJBDev** [comment]
This feature doesn't work with the below simple example:

I wonder if the library I mentioned below covers this use case.

![image](https://github.com/mytourbook/mytourbook/assets/25235665/6ddff03b-da79-4430-b0e3-55bddd3387a6)

![image](https://github.com/mytourbook/mytourbook/assets/25235665/42d5cd96-4091-4700-a313-ba0dcbb601e9)

**Comment by FJBDev** [comment]
In this PR, I have improved the detection of http links in the tour description by using [the library](https://github.com/URL-Detector/URL-Detector) I mentioned above

Here is a comparison of link detection with and without this library

MT 23.8 (**without library**):
![image](https://github.com/mytourbook/mytourbook/assets/25235665/8325f4a4-cdba-441e-b8f0-41ef8020e0af)

MT 23.10 (**with library**):
![image](https://github.com/mytourbook/mytourbook/assets/25235665/2c40d0ae-7b9a-4380-94bd-8391bbd1831e)


While it's an improvement, it's not perfect as it can, in some cases, detect links that are not links.
See [this example ](https://github.com/URL-Detector/URL-Detector/issues/32#issuecomment-1828386655)I reported directly in the library's GitHub


For future reference, below is the tour description I created for testing:

```
"http://www.wta.org/go-hiking/hikes/enchantment-lakes"
{http://www.wta.org/go-hiking/hikes/enchantment-lakes}
[http://www.wta.org/go-hiking/hikes/enchantment-lakes]
'http://www.wta.org/go-hiking/hikes/enchantment-lakes'

google.com

(1:30:02 https://podcasts.apple.com/fr/podcast/75-sofiane-sehili-3-jours-%C3%A0-p%C3%A9daler-sans-dormir/id1446344082?i=1000472873755) https://www.youtube.com/watch?v=Eo47Q7DJWdI&t=587s)
( https://www.strava.com/activities/1554809419)
```
