### ISSUE TITLE
[Feature : Tour Pauses] Add the ability to delete tour pauses

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1110]
### What is missing ?

Add the ability to delete tour pauses from the Tour Book View and the Tour Pauses View

**Comment by wolfgang-ch** [comment]
When I delete all pauses in the pauses view, then the pauses are still available in the tour data series. So I don't understand why only one part of the pauses are deleted.

![image](https://github.com/mytourbook/mytourbook/assets/1283445/5e9c81cf-b1c1-49c9-aaad-dcad61ca6966)

**Comment by FJBDev** [comment]
The column you show in your image is a "Break", which is very different than a pause. Deleting a pause won't delete a "Break" as those are computed with an algorithm.
Did you make sure that the pause is not present anymore ?

![image](https://github.com/mytourbook/mytourbook/assets/25235665/97452c2b-287b-4bd8-a7c7-d856933f5d92)

**Comment by wolfgang-ch** [comment]
> Did you make sure that the pause is not present anymore ?

Pauses are gone in the time slice editor


>The column you show in your image is a "Break", which is very different than a pause. Deleting a pause won't delete a "Break" as those are computed with an algorithm.

I was a bit confused but you are correct, pause != break

**Comment by wolfgang-ch** [comment]
When I delete the 3./4. pause, then the 1./2. is removed

![image](https://github.com/mytourbook/mytourbook/assets/1283445/2f393db6-1715-43c3-a354-05b074baa02f)


![image](https://github.com/mytourbook/mytourbook/assets/1283445/f0d2bf39-e8e3-48f6-8bf4-b61b40fde7d2)

**Comment by FJBDev** [comment]
Good catch. I also found a bug when I tested myself this morning.

They should all be fixed in this [PR](https://github.com/mytourbook/mytourbook/pull/1161)
