### ISSUE TITLE
[Bug : 2D Map] Paintings are cropped at times 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1114]
### What happened ?

On the 2D Map, painting of objects can be cropped as the examples below:

![image](https://github.com/mytourbook/mytourbook/assets/25235665/2c94c4b0-a4e7-476e-b17a-1ce4f90b3b2f)

![image](https://github.com/mytourbook/mytourbook/assets/25235665/fd22bd7b-f731-461d-a022-3bba836a2ced)

### Version

23.5

### System

All

**Comment by wolfgang-ch** [comment]
This can happen in the Basic painting mode, use Enhanced mode but then you cannot select tours in the map

![image](https://github.com/mytourbook/mytourbook/assets/1283445/1490968b-0241-4034-a952-faaa0e6411db)
