### ISSUE TITLE
[Bug : Tour Reference View] Exception occurs when using a reference tour's contextual menu 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1118]
### What happened ?

When I open the contextual menu of a reference tour, I see this exception

`Tree context menu has had the wrong parent and is recreated.`

### Version

23.5

### System

Linux

### Relevant log output

```shell
An exception stack trace is not available.
```

**Comment by wolfgang-ch** [comment]
Is a context menu displayed?

This is not an exception, just an info

![image](https://github.com/mytourbook/mytourbook/assets/1283445/ad364423-e53e-42c2-85a6-ac9612d08aa4)

**Comment by FJBDev** [comment]
I

> Is a context menu displayed?
> 
> This is not an exception, just an info
> 
I thought I had seen an exception but now I can't reproduce it. When it occurs again, I will take a screenshot

**Comment by FJBDev** [comment]
@wolfgang-ch 
>This is not an exception, just an info

In this case, would it be better to do a `StatusUtil.logInfo(` instead of `StatusUtil.logError(` ?
