### ISSUE TITLE
[Bug : Tour Reference Creation] Wrong slider position when the chart is zoomed 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1119]
### What happened ?

Scenario to reproduce the issue:

- Set the left chart slider to any position in the Tour Chart
- Zoom in the tour chart to set the right chart slider position so that the left chart slider it not visible anymore
- Right click on the Right Chart Slider and `Create reference tour`.

=> Issue: The left slider position that is used to create the Tour Reference is **NOT** the original left chart slider position set manually but the left side of the currently zoomed chart

### Version

23.5.0

### System

All

**Comment by wolfgang-ch** [comment]
I cannot reproduce this issue. 

In this video, a reference tour is created between both peaks in the way as you described it.

https://github.com/mytourbook/mytourbook/assets/1283445/d7ecb04b-a9a3-4642-b471-015fbed80fdc

**Comment by wolfgang-ch** [comment]
Ensure that this option is disabled

![image](https://github.com/mytourbook/mytourbook/assets/1283445/869384a1-6437-4384-99f6-898dbdf97ece)
