### ISSUE TITLE
[Feature : Elevation up/down speed columns] 

### ISSUE THREAD

**Issue by msmolej** [mytourbook/mytourbook#1126]
### What is missing ?

I am using Alpinequest for hiking, cycling, rowing, etc., and these statistics are very usable for me. Maybe it will also be useful for somebody else.
Proposable statistics:
Moving speeds:
- Up [m/h]
- Down [m/h]

I am attaching a picture with statistics available in Alpinequest.
 
![2023-06-01 11_40_15-MarjanS23+](https://github.com/mytourbook/mytourbook/assets/8914500/4beca1e3-bd1f-43e0-85ab-278b7b75532d)

**Comment by FJBDev** [comment]
I could see this as a useful feature

However, there is something that troubles me in your picture:

Shouldn't those number match ?

![image](https://github.com/mytourbook/mytourbook/assets/25235665/1cadb1e9-2249-45e9-a8bc-e175fe8e865e)

**Comment by Thompson-ongithub** [comment]
I think the +620m/h (1049m) only refers to the "increase" part of the track (those 11.44km done in 1h41) the missing 130m elevation gain probably were too small to register as increase and are included in the "flat" part..
At least the numbers would fit...

**Comment by wolfgang-ch** [comment]
When implementing this feature, then a tour has to be partitioned into the increase, flat and decrease parts. 

What are the parameters for the flat part, e.g. the gradient has to be below a max. value for a min distance?

**Comment by wolfgang-ch** [comment]
This feature will be available in the next version

The tooltip values in the green rectangle are showing the parameters, how the flat/gain/loss values are computed

![image](https://github.com/mytourbook/mytourbook/assets/1283445/b201fbe6-f787-44f7-90c1-37b59239e364)


With this new tour segmenter, the flat/gain/loss values can be checked how they are computed. Flat areas are displayed with a different color, in the dark mode with the white color.

![image](https://github.com/mytourbook/mytourbook/assets/1283445/fbc039ea-e35c-4a6c-bc50-246ad70c6de8)


The flat/gain/loss values are formatted with the value formatter which are defined in the pref dialog

![image](https://github.com/mytourbook/mytourbook/assets/1283445/4f1dbdc9-1011-4278-b229-27c3deafeb62)
