### ISSUE TITLE
[Bug : 2.5D Map] Crash after selecting 2.5D Map

### ISSUE THREAD

**Issue by matthias-bs** [mytourbook/mytourbook#1137]
### What happened ?

Crash when trying to open 2.5D Map.

### Version

23.5.0

### System

Linux

### Relevant log output

```shell
JVM terminated. Exit code=127
/usr/bin/java
-jar /opt/mytourbook-23.5.0/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /opt/mytourbook-23.5.0/mytourbook-23.5.0
-name Mytourbook-23.5.0
--launcher.library /opt/mytourbook-23.5.0/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.500.v20220509-0833/eclipse_11701.so
-startup /opt/mytourbook-23.5.0/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.overrideVmargs
-exitdata 38030
-vm /usr/bin/java
-vmargs
-jar /opt/mytourbook-23.5.0/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
```

**Comment by matthias-bs** [comment]
It's not really important to me. I was just curious about the new features.

**Comment by bern6** [comment]
Which java version are you using ?
For me, versions greater than 12 (linux debian) crash MTB.

**Comment by matthias-bs** [comment]
$ java --version
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode, sharing)

**Comment by Thompson-ongithub** [comment]
The same thing happens with openjdk 18.0.2-ea 2022-07-19 on Ubuntu 22.04.
If I remember correctly it was already once reported on the old forum on sourceforge (but right now I wasn't able to find it)

**Comment by Thompson-ongithub** [comment]
> The same thing happens with openjdk 18.0.2-ea 2022-07-19 on Ubuntu 22.04. If I remember correctly it was already once reported on the old forum on sourceforge (but right now I wasn't able to find it)

Found it:
https://sourceforge.net/p/mytourbook/discussion/622811/thread/fafb9eed39/

**Comment by mt-from-sf-to-gh** [comment]
I've no problems in my VMware test environment with Ubuntu 20.04 and Java 17

![image](https://github.com/mytourbook/mytourbook/assets/103518804/35314661-0aad-480f-821d-22350fb31a3f)

**Comment by wolfgang-ch** [comment]
I've no problems in my VMware test environment with Ubuntu 20.04 and Java 17

![image](https://github.com/mytourbook/mytourbook/assets/1283445/b36f0b83-4605-44dc-909b-56556452ed81)

**Comment by Thompson-ongithub** [comment]
It must be a problem with openjdk then. I never tried Oracle Java since for me the default 2D maps is enough (3D map now works; it's just the 2.5D map that crashes MTB)

**Comment by wolfgang-ch** [comment]
I'm using Java from [Eclipse Adoptium](https://adoptium.net/)

![image](https://github.com/mytourbook/mytourbook/assets/1283445/270a5fa0-d3f3-4e0a-9c2d-989f5d74502a)

**Comment by bern6** [comment]
Wolfgang,
I installed version jdk-17.0.7+17 from Eclipse Adoptium,
everything works now.
[.log](https://github.com/mytourbook/mytourbook/files/11860162/default.log)
Thanks

**Comment by FJBDev** [comment]
> It must be a problem with openjdk then.

Very likely, I have the same issue with OpenJDK 11 on Debian 11

![image](https://github.com/mytourbook/mytourbook/assets/25235665/975f2bbb-ae42-4751-aab5-09a84ac4682e)


```
JVM terminated. Exit code=127
/usr/bin/java
-Xmx8g
--add-exports=java.base/java.lang=ALL-UNNAMED
--add-exports=java.desktop/sun.awt=ALL-UNNAMED
--add-exports=java.desktop/sun.java2d=ALL-UNNAMED
-jar /home/frederic/Mytourbook//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /home/frederic/Mytourbook/mytourbook
-name Mytourbook
--launcher.library /home/frederic/Mytourbook//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.500.v20220509-0833/eclipse_11701.so
-startup /home/frederic/Mytourbook//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.overrideVmargs
-exitdata 8015
-vm /usr/bin/java
-vmargs
-Xmx8g
--add-exports=java.base/java.lang=ALL-UNNAMED
--add-exports=java.desktop/sun.awt=ALL-UNNAMED
--add-exports=java.desktop/sun.java2d=ALL-UNNAMED
-jar /home/frederic/Mytourbook//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar 
```

**Comment by FJBDev** [comment]
> Very likely, I have the same issue with OpenJDK 11 on Debian 11

I should have said Debian **12** now that I have upgraded to the latest ["bookworm" Debian ](https://www.debian.org/News/2023/20230610)😎
