### ISSUE TITLE
[Feature : Geo Compare] Show compare result in a timeline view

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1139]
### What is missing ?

The elevation compare result can be displayed as a graph in the `Year Statistic` view but this graph is not available for geo compare results.

This feature displays the geo compare results in the `Reference Timeline` view (the old `Year Statistic` view). This view is live updated when the start or end positions are modified.

![image](https://github.com/mytourbook/mytourbook/assets/1283445/93f087ee-0425-4595-a3e5-e85868f6c426)

This video shows the live update of the `Reference Timeline` view for a geo compared tour without a reference tour

https://github.com/mytourbook/mytourbook/assets/1283445/55f93e14-d270-4c43-93a6-246772690c59

This video show either the elevation compared tours or the geo compared tours in the `Reference Timeline` view

https://github.com/mytourbook/mytourbook/assets/1283445/f1efc0e3-c78d-4d89-9169-abb14f2f1002

**Comment by wolfgang-ch** [comment]
@FJBDev @telemaxx 
I've merged this feature into the `main` branch. So you can test it and I know it's a complex piece of UI and also the software. There are severals views which are working together and I hope you can figure out how it works.

**Comment by telemaxx** [comment]
Hi together,
my eclipse didn't want to start mt, so i just deleted my eclipse workspace and reimported the complete project.
Now i can start the latest main again.

i did the 1st tests.
tour compare  was/is really a bit complicate to use.
now i can do more tests and try to understand how it works...

**Comment by telemaxx** [comment]
i have played with Geo Compare.
Complicate to understand, so much views playing together.

"Geo Compare" is for me more interesting than "altitude compare".
It is a good alternative for the "Geo Tours Filter", when i search a tour which should contain an interesting track/trail.

**Comment by wolfgang-ch** [comment]
"Altitude Comparison" vs "Elevation Comparison"

I though that we use "elevation" instead of "altitude", we already did a large renaming action

**Comment by wolfgang-ch** [comment]
> Show all the tours being compared on the 2D map (maybe it's something difficult to do, I am not sure)

Multiple tours can already be displayed in the 2D map however not yet multiple compared tours but it should be possible.

**Comment by wolfgang-ch** [comment]
> * I am not a fan of "Geo Compare" view name. here are my suggestions:
>       _Tour Comparison_
>       _Identical Tours Comparison_

When using `Tour Comparison` then I think this is confusing. Someone can ask what is the difference between `Tour Comparison` and `Elevation compare...`

When using `Geo Compare` then we see immediately how the tours are compared

I would use the words `Tour Comparison` when both comparision methods could be used, e.g. `Tour Comparison Timeline`

![image](https://github.com/mytourbook/mytourbook/assets/1283445/76f51b90-8ef7-4388-8a69-1d68ecd9f55f)

**Comment by wolfgang-ch** [comment]
> I would put the best/fastest values in bold (cf. Highlighted values) so that the user can quickly see which one was fastest/best

I think that the timeline view shows the best/worst results easier

![image](https://github.com/mytourbook/mytourbook/assets/1283445/76780cb8-52a8-4e78-a9d1-c3e2a5769b46)
