### ISSUE TITLE
[Feature : Edit Sensor] Allow delete of a Sensor and additional Sensor Types

### ISSUE THREAD

**Issue by stvzldn** [mytourbook/mytourbook#1144]
![Sensors to delete](https://github.com/mytourbook/mytourbook/assets/106929478/a44f165d-fc99-4321-a72a-7de25c0d7991)

If a Sensor is added via a .fit tour import and then the tour is later deleted, that Sensor remains in the Sensor list with the default date of 1Jan1970 (See image above).

1. Add a button to the Edit Sensor dialog which will delete an unused Sensor.
2. Expand the Type list to include: "Power Meter", "Wind", and "Radar".
3. Add a column for the Sensor's Ant+ Id or BlueTooth Id (I assume these are available in the .fit files).

**Comment by wolfgang-ch** [comment]
The next version will included the requested sensor types

![image](https://github.com/mytourbook/mytourbook/assets/1283445/cf180ac7-1078-48b8-ace9-6f9b14de392f)

**Comment by wolfgang-ch** [comment]
> Add a column for the Sensor's Ant+ Id or BlueTooth Id (I assume these are available in the .fit files).

I can't find an Ant+ ID in my .fit files, only the device serial number is available and can already be displayed in the sensor view

![image](https://github.com/mytourbook/mytourbook/assets/1283445/7142304a-0b36-4ada-ae7f-cae0c9afd51d)

**Comment by wolfgang-ch** [comment]
In the next version, a sensor can be deleted when it is not contained in any tour, the `<Delte>` key also works

![image](https://github.com/mytourbook/mytourbook/assets/1283445/e14af00f-4858-4316-afdf-ac093945779f)

![image](https://github.com/mytourbook/mytourbook/assets/1283445/90003f17-34d3-48b4-b5e1-30bc4cabf14f)


![image](https://github.com/mytourbook/mytourbook/assets/1283445/043d6e52-fb5a-41e1-a898-357e222f71cb)

**Comment by wolfgang-ch** [comment]
Closing this issue as done because "Add a column for the Sensor's Ant+ Id or BlueTooth Id (I assume these are available in the .fit files)." cannot be implemented
