### ISSUE TITLE
[Bug : FIT Import] [Bug : GPX Import]

### ISSUE THREAD

**Issue by Atombike** [mytourbook/mytourbook#1156]
### What happened ?

Hi,
I have 2 problems with importing GPX / FIT files.

1. Garmin FIT file: the heart rate chart shows double lines and one with spikes. If I download GPX from Garmin site it is ok but the original FIT is better bc it contains more data like temperatures and pause times.
![kép](https://github.com/mytourbook/mytourbook/assets/25572305/4c6c1e0d-7ee3-4fb1-a096-e2edaa873471)

2. I have an Amazfit watch too and when I export the GPX track from the ZEPP app sometimes it does not show the elevation data (in mytourbook). Sometimes it is shows.
First I tought it was the watch/app problem but other software can read it and shows the elevation charts (I tried it with oruxmaps).

### Version

23.5

### System

Windows

**Comment by FJBDev** [comment]
>     1. Garmin FIT file: the heart rate chart shows double lines and one with spikes. If I download GPX from Garmin site it is ok but the original FIT is better bc it contains more data like temperatures and pause times.

This is not a bug but a feature. The blue line is shows the [R-R data](https://mytourbook.sourceforge.io/mytourbook/index.php/documentation/show-tours/tour-chart#heartbeat-values).
You can hide it if you want. See the chart options drop down menu

![image](https://github.com/mytourbook/mytourbook/assets/25235665/dbf65eba-6b90-483c-8d71-40bcd35e7fa5)


>     2. I have an Amazfit watch too and when I export the GPX track from the ZEPP app sometimes it does not show the elevation data (in mytourbook). Sometimes it is shows.
>        First I tought it was the watch/app problem but other software can read it and shows the elevation charts (I tried it with oruxmaps).
> 

Can you attach a GPX example so it can be used to reproduce/investigate the issue you describe ?

**Comment by Atombike** [comment]
Thanks, I didn't know that settings.

Here is 2 GPX file whitout elevation chart in mytourbook. 
In oruxmaps it shows the altitude profile but it is possible that it use the DEM files which I can not check.
GPS editor did not showed any altitude data but it is a simple software.
(There is also elevation data in the original data in the  ZEPP app but export error is possible). 
[amazfit GPX.zip](https://github.com/mytourbook/mytourbook/files/12214516/amazfit.GPX.zip)
