### ISSUE TITLE
[Bug : Tour Chart] Toolbar always on top

### ISSUE THREAD

**Issue by witdem** [mytourbook/mytourbook#1163]
### What happened ?

The toolbar for the tour chart is always shown on top of everything. So when you open another program you will still have this toolbar shown. 
![afbeelding](https://github.com/mytourbook/mytourbook/assets/14309258/a64d1189-587f-4514-a63d-2cdffbebbac5)

### Version

23.05

### System

Windows

**Comment by wolfgang-ch** [comment]
See https://github.com/mytourbook/mytourbook/issues/1030#issuecomment-1476566816
