### ISSUE TITLE
[Feature : Tour Book View] 

### ISSUE THREAD

**Issue by stvzldn** [mytourbook/mytourbook#1173]
### Go to today in Tour Book View
I often do a search for old tours while in Tour Book View.  Looking at these old tours quickly fills the Tour Book View with many lines of tour summaries.  I can close all these summary lines by the Collapse All "-" button.  But then to reopen the current day/week/month I need to switch to Calendar View, choose the "Go to today" button and then return to Tour Book View. (This sequence does not work if there is no tour for today).

Enhancement request is to add a "Go to today" button to Tour Book View.  This button would always open the most current date tour line, even if "today" does not have a tour.

![Go to today on Tour Book View](https://github.com/mytourbook/mytourbook/assets/106929478/59175e1f-bd6d-4b00-8f77-0100993b1952)

**Comment by wolfgang-ch** [comment]
This feature will be available in the next version

![image](https://github.com/mytourbook/mytourbook/assets/1283445/ad9ec3fc-423b-4842-bbcd-479801d948c7)
