### ISSUE TITLE
[Bug : libwebkit2gtk-4.0-37]

### ISSUE THREAD

**Issue by bern6** [mytourbook/mytourbook#1183]
### What happened ?

Hello

Just for information,
Package: libwebkit2gtk-4.0-37  version:2.42.0-1
breaks Tour Blog, Easy Import and other things.

### Version

23.8.0

### System

Linux

**Comment by FJBDev** [comment]
@bern6 
Can you add log outputs and/or screenshots ?

There was a [similar bug](https://github.com/mytourbook/mytourbook/issues/457) in the past that was fixed in Eclipse 2022-06, I'm curious to see if it's different this time

**Comment by FJBDev** [comment]
I should mention that I am not experiencing those issues with my below version of `libwebkit2gtk`

`2.40.5-1`

**Comment by bern6** [comment]
Hello FJBDev

I have already downgraded the system, and hold libwebkit2gtk-4.0-37 and libjavascriptcoregtk-4.0-18 with version:2.40.5-1
The problems were:
Easy Import - only with a simple UI is aviable
Tour Log - only the simple presentation is aviable
Tour Blog - tour blog blank screen
and maybe other things

**Comment by bern6** [comment]
@FJBDev

I have no knowledge of Eclipse, it is difficult for me to create a bug report.

**Comment by FJBDev** [comment]
@bern6 
Can you export the log from MT and attach it here ?

**Comment by bern6** [comment]
@FJBDev 

I upgrade libjavascriptcoregtk-4.0-18 and libwebkit2gtk-4.0-37 to version:2.42.0-1
and here are the MT logs

[01.log](https://github.com/mytourbook/mytourbook/files/12692488/01.log)
[02.log](https://github.com/mytourbook/mytourbook/files/12692490/02.log)
[start.log](https://github.com/mytourbook/mytourbook/files/12692494/start.log)

**Comment by FJBDev** [comment]
@bern6 
Thanks for the log files. However, I don't see anything related to the `libwebkit2gtk` issue. Can you please add screenshots of the impacted views?

**Comment by bern6** [comment]
@FJBDev 
I deleted libwebkit2gtk-4.0-37, no difference with or without libwebkit2gtk,
I think the problem is related to my debian.
by reinstalling version 2.40.5-1 everything works normally.

![Search Tool](https://github.com/mytourbook/mytourbook/assets/103836286/a01c06d9-f312-4663-a634-7f4470f3c494)
![Easy Import](https://github.com/mytourbook/mytourbook/assets/103836286/56b73c6e-0ea1-42b4-a918-575df09a407b)
![Tour Blog](https://github.com/mytourbook/mytourbook/assets/103836286/6c39ede7-a093-467e-853b-c8ca904de481)

**Comment by FJBDev** [comment]
> @FJBDev I think the problem is related to my debian.

I have Debian myself too (12 - Bookworm) and don't experience this issue

**Comment by FJBDev** [comment]
> I found the solution [here](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1931670.html) run Mytourbook with : WEBKIT_DISABLE_DMABUF_RENDERER=1 ./mytourbook works
> 

Nice 👍 

> @FJBDev can we put this variable in the mytourbook.ini file

Since this issue is only for Linux users, maybe that is something that should be done individually. @wolfgang-ch  Thoughts ?

**Comment by wolfgang-ch** [comment]
> Since this issue is only for Linux users, maybe that is something that should be done individually. @wolfgang-ch Thoughts ?

We could put it into mytourbook.ini but I don't know the consequences for other Linux users

**Comment by bern6** [comment]
Hello

I was only talking about my ini file, a small script will also do the trick

**Comment by FJBDev** [comment]
> Hello
> 
> I was only talking about my ini file, a small script will also do the trick

In this case, no need for a script, just add it to your launch command line
