### ISSUE TITLE
[Bug : Tour Editor] Air quality is not displayed when it's saved with a different language

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1193]
### What happened ?

The air quality is saved as string with the selected language. The tour editor do not select the saved air quality when the language has changed.

### Version

23.10 and before

### System

All

**Comment by wolfgang-ch** [comment]
I think we have to change this in further versions, that air quality is saved as a number which is independend of the language

**Comment by Thompson-ongithub** [comment]
I don't know if it's the same issue, but already when updating from 23.5 to 23.8 (which I did just recently on my way to test 23.10) whatever is inserted in "air quality" gets removed (MTB in German)

**Comment by FJBDev** [comment]
> I don't know if it's the same issue, but already when updating from 23.5 to 23.8 (which I did just recently on my way to test 23.10) whatever is inserted in "air quality" gets removed (MTB in German)

I can't reproduce the issue on 23.10, can you provide a scenario and/or video capture to show the problem ?

**Comment by Thompson-ongithub** [comment]
In version 23.5 I had a few gps-tracks where "air quality" was set when updating the weather information. After updating this to version 23.8 "air quality" was set to "nicht ausgewählt" (not selected).
After updating the weather information (by clicking on weather, obviously) and getting updates from openweathermap air quality once again was set.

**Comment by FJBDev** [comment]
@Thompson-ongithub When you updated from 23.8 to 23.10, did you have the same issue ? Also, did you happen to switch languages or did you keep using MT in german all that time ?
@wolfgang-ch Since you use german too, did you encounter the issue ?

**Comment by Thompson-ongithub** [comment]
> @Thompson-ongithub When you updated from 23.8 to 23.10, did you have the same issue ? Also, did you happen to switch languages or did you keep using MT in german all that time ? @wolfgang-ch Since you use german too, did you encounter the issue ?

If I remember correctly when upgrading from 23.8 to 23.10 the air quality wasn't removed (I'll double check later this evening)
And no, I never switched langauges. I'm using MTB in German since like forever ;)

**Comment by Thompson-ongithub** [comment]
> > @Thompson-ongithub When you updated from 23.8 to 23.10, did you have the same issue ? Also, did you happen to switch languages or did you keep using MT in german all that time ? @wolfgang-ch Since you use german too, did you encounter the issue ?
> 
> If I remember correctly when upgrading from 23.8 to 23.10 the air quality wasn't removed (I'll double check later this evening) And no, I never switched langauges. I'm using MTB in German since like forever ;)

I just double checked: when upgrading from 23.08 to 23.10beta "air quality" is remembered (i.e. is still set where it was set in 23.08)

**Comment by wolfgang-ch** [comment]
Because the translated text is saved in the database field and the german translation was changed https://github.com/mytourbook/mytourbook/issues/1124#issuecomment-1651150892 there is now a mess. 

I was not aware that the tranlated text is saved when I changed the translation but this issue will and can be fixed in the following version after 23.10

**Comment by Thompson-ongithub** [comment]
> Because the translated text is saved in the database field and the german translation was changed [#1124 (comment)](https://github.com/mytourbook/mytourbook/issues/1124#issuecomment-1651150892) there is now a mess.
> 
> I was not aware that the tranlated text is saved when I changed the translation but this issue will and can be fixed in the following version after 23.10

Thanks.
(although I don't really use air quality) ;)

**Comment by FJBDev** [comment]
> Because the translated text is saved in the database field and the german translation was changed [#1124 (comment)](https://github.com/mytourbook/mytourbook/issues/1124#issuecomment-1651150892) there is now a mess.
> 
> I was not aware that the tranlated text is saved when I changed the translation but this issue will and can be fixed in the following version after 23.10

I have done a fix [here ](https://github.com/mytourbook/mytourbook/pull/1213)for the next version.

> there is now a mess
Sorry for the "mess" !

**Comment by wolfgang-ch** [comment]
I also already started a fix for this issue https://github.com/mytourbook/mytourbook/commit/5e4b82c24aeff9cf152553ad5621216bc5b50997 + https://github.com/mytourbook/mytourbook/commit/6ba1d75fa4ff1aa48fabc59db3d8eb353fbaf339 and used simple SQL which is way faster than EJB, you cannot even see the update progress in the UI. 

I was not aware that you already generalized the concurrent update data process in `updateDb__3_Data_Concurrent()` which is not necessarily needed for this update but I will merge your fix into the `main` branch when MT 23.10 is released.

**Comment by FJBDev** [comment]
> I was not aware that you already generalized the concurrent update data process in `updateDb__3_Data_Concurrent()` which is not necessarily needed for this update but I will merge your fix into the `main` branch when MT 23.10 is released.

I used a concurrent update because, for example, in my PROD MT, ALL my tours from 2020 (27th November 2020) to 2023 have air quality and I thought it would be a lot of tours and hence better with concurrency.

**Comment by FJBDev** [comment]
>but I will merge your fix into the `main` branch when MT 23.10 is released.

That sounds good. It's probably too late and risky to put it in 23.10

**Comment by wolfgang-ch** [comment]
> > I was not aware that you already generalized the concurrent update data process in `updateDb__3_Data_Concurrent()` which is not necessarily needed for this update
> 
> I used a concurrent update because, for example, in my PROD MT, ALL my tours from 2020 (27th November 2020) to 2023 have air quality and I thought it would be a lot of tours and hence better with concurrency.

When only a sql field must be updated, like in this issue, then I think it's faster with native sql commands because EJB is loading the whole `TourData` with all it's relations and native sql command could also be run concurrently

**Comment by wolfgang-ch** [comment]
> > but I will merge your fix into the `main` branch when MT 23.10 is released.
> 
> That sounds good. It's probably too late and risky to put it in 23.10

After having published a test version then I don't change the database version in final fixes

**Comment by FJBDev** [comment]
> After having published a test version then I don't change the database version in final fixes

That makes sense, it's better not take any risks for new releases
