### ISSUE TITLE
[Feature : Tour Book Editor]  Scroll Wheel behaviour

### ISSUE THREAD

**Issue by GurVJ** [mytourbook/mytourbook#1200]
### What is missing ?

In Tour Book Editor, using the scroll wheel allows to go down and up in the window but also to change selection in a combo box. So it often happens that while scrolling up and down the window, some data change by error (Tilte, Location, Time Zone, etc).
Would it be possible that the scrolling wheel in Combo Boxes could be activated only after having clicking on it once before ?

**Comment by GurVJ** [comment]
Yes it works but it is only a workaround (so not really user friendly).
Don't you think Combo boxes could be not "activated" by default ?

**Comment by FJBDev** [comment]
>  Don't you think Combo boxes could be not "activated" by default ?

Maybe but that means we would also need to deactivate spinners etc....
Not sure what the best and most practical solution is

**Comment by stvzldn** [comment]
I too find this to be somewhat non-standard.  The Tour Editor is too "good" at sensing the mouse cursor position.  Click outside of some boxes activates the box.  Especially true in the Weather section.

**Comment by wolfgang-ch** [comment]
I'm currently implementing this feature but for the `Air Quality` field it is not easily possible to prevent the mouse wheel in the `org.eclipse.nebula.widgets.tablecombo.TableCombo` widget. There is no interface to hook into it to prevent the mouse wheel, the mouse wheel feature is builtin.

**Comment by wolfgang-ch** [comment]
This feature can be enabled/disabled in the tour editor options slideout

![image](https://github.com/mytourbook/mytourbook/assets/1283445/0d715e81-fe47-4bdc-ba56-16818a3a6801)

**Comment by wolfgang-ch** [comment]
There is one imperfection, when the mouse is hovering a text field and `Scroll field content with the mouse wheel` is disabled, the field content is not scroll (which is what was requested) but also the whole tour editor content is not scrolled

**Comment by wolfgang-ch** [comment]
Improved this feature, there are now two options when the field content should be scrolled

![image](https://github.com/mytourbook/mytourbook/assets/1283445/77517734-57e4-42a8-9c67-176accc49205)


![image](https://github.com/mytourbook/mytourbook/assets/1283445/955dac1c-ef43-4b95-a126-def2fff5702d)
