### ISSUE TITLE
[Feature : Tour Book Editor] Cancel Changes

### ISSUE THREAD

**Issue by GurVJ** [mytourbook/mytourbook#1201]
### What is missing ?

After having changed anything in the Tour Book Editor windows, MTB ask for saving the Tour before displaying another Tour
![image](https://github.com/mytourbook/mytourbook/assets/64196685/9d53771a-f447-4b45-9326-ed2e5af61476)

Would it be possible to have some kind of button to Cancel the changes made on the Tour and then to be able to go to the next selected tour ?

**Comment by FJBDev** [comment]
Did you try the button to "Undo the tour modifications" or Ctrl-Z ?
See below image

![image](https://github.com/mytourbook/mytourbook/assets/25235665/9cbf0044-5f91-4542-89d3-fab21b9739e8)

**Comment by GurVJ** [comment]
Ctrl-Z is working but you have to be used to shortcuts.
I didn't notice this "undo" button until you told me...
These 2 solutions are working but as an Enhancement (if technically feasible)) , it would be great to have the Save and Cancel buttons directly in the Tour Editor view.

**Comment by wolfgang-ch** [comment]
In the next version, the save/restore actions are moved into the tour editor view toolbar

![image](https://github.com/mytourbook/mytourbook/assets/1283445/dbae0d17-528c-494a-936b-a9d9e3380906)
