### ISSUE TITLE
[Bug : Tour Book View]: expand view by clicking on month

### ISSUE THREAD

**Issue by Thompson-ongithub** [mytourbook/mytourbook#1205]
### What happened ?

Up until 23.08 it was possible to click on the month (in the Tour Book View) to expand the selected month. 
in 23.10Beta when clicking on the month MTB seems to run into a loop. It's only possible to expand the view by clicking on the arrow.
When the closing the month again by pressing the arrow sometimes (sorry, I know that's frustrating) the same happens.

MTB23.10beta on Linux (with openJDK)

### Version

23.10Beta

### System

Linux

**Comment by wolfgang-ch** [comment]
>in 23.10Beta when clicking on the month MTB seems to run into a loop. 

Can you create a video to show this

When these new expand features are disabled then the mouse expand/collapse should work like MT 23.8

![image](https://github.com/mytourbook/mytourbook/assets/1283445/309b6a84-2174-4c86-b56c-36b6ad937352)

**Comment by Thompson-ongithub** [comment]
I'll try to do so later this evening...

**Comment by Thompson-ongithub** [comment]
> > in 23.10Beta when clicking on the month MTB seems to run into a loop.
> 
> Can you create a video to show this
> 
> When these new expand/collapse features are disabled then the mouse expand/collapse should work like MT 23.8
> 

you're right, with those 2 new features disabled MTB works as before...
Video will follow...

**Comment by Thompson-ongithub** [comment]
[Bildschirmaufzeichnung vom 2023-10-16, 01:47:32.webm](https://github.com/mytourbook/mytourbook/assets/127450598/e4b90643-fe3a-4a31-8085-f2fe72d8c273)

just a quick video, sorry for not inserting the mouse... when clicking on the arrow the month opens as it should, if I double click the whole thing starts to flicker, only to be stopped by either pressing "go to last tour" or "collapse all"

**Comment by wolfgang-ch** [comment]
I could reproduce this issue, it happens when the window height is small and the content needs to be scrolled. I also tested and discovered the same issue in the reference tour view or tagged tours view

**Comment by wolfgang-ch** [comment]
This issue is now fixed for the views

* Tour Book
* Reference Tours
* Tagged Tours
