### ISSUE TITLE
[Bug : Tour Duplication] Markers from duplicated tours have their date equal to the one from the original tour

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1221]
### What happened ?

Scenario to reproduce:
- Duplicate a tour that contains markers
- Set the date of this tour to a different date than the original tour
- Open the All Tour Markers View
=> The date of the markers belonging to the duplicated tour will display a date identical to the markers belonging to the original tour

![image](https://github.com/mytourbook/mytourbook/assets/25235665/21da90dd-32c4-4b83-87fa-3ee7916da87c)

### Version

23.10

### System

All

**Comment by wolfgang-ch** [comment]
Here we have a bigger problem, any tour were the tour start date is modified+saved do not update the tour marker date/time.

I just fixed this issue https://github.com/mytourbook/mytourbook/commit/77727b251caa8f0795d8806321668c105c5ac5fa for the `All Tour Markers` view

**Comment by wolfgang-ch** [comment]
Fixed in https://github.com/mytourbook/mytourbook/commit/15a09d7e85f7209cb175c4ee486b48b53a91eb18

**Comment by FJBDev** [comment]
And this is why it's good that the "tpur duplication" feature is still marked as "experimental"
