### ISSUE TITLE
[Feature : MT Search] 

### ISSUE THREAD

**Issue by GurVJ** [mytourbook/mytourbook#1224]
### What is missing ?

When hoovering the Preferences icon of the Search window, the Preferences options are shown in a a pop up window like in any other view.
But unlike other views, this Preference pop up windows do not disappear when the Preferences icon is not hoovered anymore : you have to close it manually with the Close cross button.
Would it be possible to standardize the Preferences pop up window behaviour by making it disappear when the preference icon is no more hoovered ?
![image](https://github.com/mytourbook/mytourbook/assets/64196685/2db8710d-6016-4778-818c-ca6d987d981a)

**Comment by wolfgang-ch** [comment]
This slideout is using the Javascript framework Dojo which is total different compared with the other slideouts.

>But unlike other views, this Preference pop up windows do not disappear when the Preferences icon is not hoovered anymore : 

This was already implemented but removed 2021-08-04 in https://github.com/mytourbook/mytourbook/commit/6740d2d1ea6d18faa341f58938ef634f15a89d36 and I cannot remember why, but I think it was not working as it should

![image](https://github.com/mytourbook/mytourbook/assets/1283445/b2d3d364-bbc2-4b4d-8a33-f40014431e9b)



>you have to close it manually with the Close cross button.

This slideout can also be closed with the `<Esc>` key

**Comment by GurVJ** [comment]
If the correction doesn't work, another way to handle the problem could be to not open the slideout on Preference icon being hovered but only when it is clicked (the slideout behaviour is different compared to the others so the Preference icon behaviour could also be different compared to the others).
It really drives me crazy when I am using the search tool and the slideout opens each time that I move my mouse so I have to close it manually (even with <Esc> key) !

**Comment by wolfgang-ch** [comment]
>It really drives me crazy 

me also a little bit, so I removed the mouse hover action for the options button in https://github.com/mytourbook/mytourbook/commit/ebf5d8ccaa79d04d4597039f431cf88571fefba1
