### ISSUE TITLE
[Bug : Developing setup] decription on the homepage is not complete (Developing section)

### ISSUE THREAD

**Issue by telemaxx** [mytourbook/mytourbook#1226]
### What happened ?

i tried to setup eclipse for testing "MyTourbook"
my old linux VM where i did it in the past is outdated(Java 11 etc)

This time i want to use eclipse directly on my windows desktop.
There i have already some other stuff, but only normal java projects.

now i had to start from scratch following the [online instructions](https://mytourbook.sourceforge.io/mytourbook/index.php/development/dev-ide)

in the "App Plugin" Section one point is missing. "Eclipse Java Developing Tools", so the was no "run configuration" "eclipse Application"
in the App Plug in section at least this is missing:

![grafik](https://github.com/mytourbook/mytourbook/assets/22706487/81811225-db04-4824-beea-1d7494a2b231)

with this installed i see now "run configuration" "eclipse Application"

after importing project from github i don't see this:

![grafik](https://github.com/mytourbook/mytourbook/assets/22706487/312860ec-31e3-49cc-9cbf-c8a5341b2f04)

only 3 points:

![grafik](https://github.com/mytourbook/mytourbook/assets/22706487/ed84c695-142b-4588-91b1-1fa9a5343756)

so i selected mytourbook\bundles

after that i tried to create a running configuration, but i can not select/see the product net.tourbook.product

Idea whats wrong?

### Version

Eclips 2023-06 with java 17

### System

Windows

**Comment by wolfgang-ch** [comment]
You have propably not installed the `Eclipse SDK` as pointed out in the descriptions
 
![image](https://github.com/mytourbook/mytourbook/assets/1283445/292c823d-4bcb-4ad6-80b9-36f7c6005b6f)

...then you have these installed plugins

![image](https://github.com/mytourbook/mytourbook/assets/1283445/825208c3-3520-4ec6-a215-3cd4a6688c64)

... and then you can import the plugins

![image](https://github.com/mytourbook/mytourbook/assets/1283445/7a551a52-700c-4f92-af16-6b645a7340c4)


I'm currently updating the documentation but until the imports from the git repo, there are no big changes. 

The "App Plugins" Section is after the git import

**Comment by wolfgang-ch** [comment]
These are my imported projects/plugins

https://github.com/mytourbook/mytourbook/assets/1283445/c84ee0bc-be6d-432f-884c-1cdfc998d045

**Comment by wolfgang-ch** [comment]
These pages are now updated

- https://mytourbook.sourceforge.io/mytourbook/index.php/development/dev-ide/setup-git
- https://mytourbook.sourceforge.io/mytourbook/index.php/development/dev-ide/documentation-dev-ide-app-plugins

**Comment by telemaxx** [comment]
seems so that Eclipse SDK is different from the normal Eclipse.
and its hard to find on the download page...


so downloaded and unpacked this version to a fresh folder
but at first it wont start due to a missing dll in my java installation. but that dll was there.
so i copied some files from a "normal" eclipse to the sdk folder.

now eclipse is starting and i see "Eclipse SDK" as installed.

![grafik](https://github.com/mytourbook/mytourbook/assets/22706487/87e3cd8f-9835-49e8-83c0-cd4d1a5939e6)

but import project has still only the 3 projects.

for now i giving up.

i wait for a test version on dropbox ;-)

**Comment by wolfgang-ch** [comment]
> and its hard to find on the download page...

This is the reason why I've put this link http://download.eclipse.org/eclipse/downloads/ in the documentation https://mytourbook.sourceforge.io/mytourbook/index.php/development/dev-ide/development-env-installation

... select the version

![image](https://github.com/mytourbook/mytourbook/assets/1283445/723112d8-63b6-4aa4-938c-92f0290cfffd)

... and the SDK

![image](https://github.com/mytourbook/mytourbook/assets/1283445/78ca62f8-8e73-4a08-8546-62e20654d5c5)
