### ISSUE TITLE
[Bug : Database Data Update] Wrong sequence of updates -> "weather-showers-scatterd" is not updated

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1251]
### What happened ?

When updating vom e.g. MT version 22.6 directly to 23.10, then the weather "weather-showers-scatterd" is not updated -> this weather is not displayed. When such a tour was not yet modified/saved in the tour editor, then the wrong weather value is still saved in the tour, however when the tour was saved with the tour editor, **then this info is lost**.

When updating MT every new version then this issue did not happen.

MT 24.1 will fix this issue when it finds the old value and will convert it to the new. In the log (when you run MT with a terminal window `C:\Program Files\MyTourbook\mytourbook.exe" -nl en_GB -debug -consolelog`) you can see the tours where the wrong value was converted.

![image](https://github.com/mytourbook/mytourbook/assets/1283445/5bbbc543-3126-44cf-8540-cb3367727349)

This screenshot shows, that the update sequence was wrong since db version 50, which is MT version 23.5

![image](https://github.com/mytourbook/mytourbook/assets/1283445/316e9124-2689-4d48-862b-02cd4d0486c0)

I discovered this issue just yesterday

### Version

23.10 and before

### System

All

**Comment by wolfgang-ch** [comment]
Should we remove the downloads for 23.5 (db version 50) and later, these version can cause this issue ?

![image](https://github.com/mytourbook/mytourbook/assets/1283445/8f27d64b-a84b-49ed-8286-dc64eb4a9c08)

**Comment by wolfgang-ch** [comment]
This is the result of my 24.1 update tests:

**Left side: Update 22.2 -> 24.1**

This is performing update 48 as it should

**Right side: Update 22.2 -> 23.10 and 23.10 -> 24.1**

In 22.2 ->23.10 the db data update 48 is not performed like in 22.2 -> 24.1 but this missing update is now done in 23.10 -> 24.1

![image](https://github.com/mytourbook/mytourbook/assets/1283445/32c9ba45-ec50-4bc7-a9cb-62da5b64ab00)

**Comment by wolfgang-ch** [comment]
This issue is now fixed in 6500ad4418febe8703ca2b03ee7af85186a22b35

**Comment by FJBDev** [comment]
> Should we remove the downloads for 23.5 (db version 50) and later, these version can cause this issue ?
> 
> Version 23.5 was the first version which was wrong

Maybe since we dont want to have those issues happen to anyone 😕

**Comment by FJBDev** [comment]
> > Should we remove the downloads for 23.5 (db version 50) and later, these version can cause this issue ?
> > Version 23.5 was the first version which was wrong
> 
> Maybe since we dont want to have those issues happen to anyone 😕

@wolfgang-ch 
Today an idea came to mind....
Instead of deleting all the MT versions from 23.5 to 23.10, what about we release them again but with the database fix included ? 
That way they are still available ?

**Comment by wolfgang-ch** [comment]
> Instead of deleting all the MT versions from 23.5 to 23.10, what about we release them again but with the database fix included ?

This would need code change and testing, 24.1 is almost available.

> That way they are still available ?

Who needs an old version when a new version is available.

**Comment by FJBDev** [comment]
> Who needs an old version when a new version is available.

I was thinking since the other older versions are still available 18.X, 19.X etc....

**Comment by wolfgang-ch** [comment]
> > Who needs an old version when a new version is available.
> 
> I was thinking since the other older versions are still available 18.X, 19.X etc....

I want to keep all old versions when they are valid.

**Comment by stvzldn** [comment]
I like the idea of software "peace" but best to correct [the red box flagged text](https://mytourbook.sourceforge.io/mytourbook/index.php):
"A complex **piece** of software can sometimes not be 100% OK "

**Comment by wolfgang-ch** [comment]
> I like the idea of software "peace" but best to correct [the red box flagged text](https://mytourbook.sourceforge.io/mytourbook/index.php): "A complex **piece** of software can sometimes not be 100% OK "

Thanks, I corrected it but it will be visible when MT 24.1 is published
