### ISSUE TITLE
[Bug : Calendar] Dragged mouse scrolling verbiage

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1258]
### What happened ?

When I look at the check box "Use dragged mouse scrolling", i find it very confusing.

From my investigation, what it actually does, is to reverse, or not, the mouse wheel scrolling but the check box makes it sound like it does something different when it's unchecked, the dragging is not working, am I missing/misunderstanding something ?

The [documentation](https://mytourbook.sourceforge.io/mytourbook/index.php/documentation/show-tours/tour-calendar-2#navi-mousewheel) actually explains it better

`The scroll direction depends on Use dragged mouse scrolling  in the Calendar Layout`

![image](https://github.com/mytourbook/mytourbook/assets/25235665/4c75fc19-e066-4781-ac17-7049e2a4362d)

### Version

23.10

### System

All

**Comment by FJBDev** [comment]
Here is my proposal for the checkbox label and tooltip

Label: `Reverse mouse scrolling`
Tooltip: `When checked, the mouse scrolling will be inverted when scrolling through the calendar view`

**Comment by wolfgang-ch** [comment]
Fixed with your suggestions 👍
