### ISSUE TITLE
[Bug : Tour Chart Segment Popup] In Imperial segment distance shown as kilometers but labeled miles

### ISSUE THREAD

**Issue by stvzldn** [mytourbook/mytourbook#1262]
### What happened ?

I am using Imperial measurements.
The Tour Chart Segment popup displays the segment distance in kilometers but labeled miles.

![TourSegment Miles](https://github.com/mytourbook/mytourbook/assets/106929478/713cf635-75b0-4351-80a5-51d608fd5161)

### Version

23.10.0

### System

Windows

**Comment by wolfgang-ch** [comment]
There are other similar issues

* Segment elevation value in the segment tooltip
* Segment elevation value in the elevation graph

**Comment by wolfgang-ch** [comment]
Fixed in 24.1
