### ISSUE TITLE
[Bug : Start/End Location - Profile Editor] 

### ISSUE THREAD

**Issue by Thompson-ongithub** [mytourbook/mytourbook#1270]
### What happened ?

Whenever I start MTB the Profile called "Street + House #" is set as standard profile regardless as to which profile I set as standard before...

### Version

24.01

### System

Linux

**Comment by wolfgang-ch** [comment]
I can confirm this issue, the default is saved correctly in `tour-location.xml` but not correctly restored. 

This is now fixed in https://github.com/mytourbook/mytourbook/commit/40bc20212aea0431df01252e2f866c5b0584491d
