### ISSUE TITLE
[Feature : TourBook View] Format Powertrain L-R Balance

### ISSUE THREAD

**Issue by stvzldn** [mytourbook/mytourbook#1271]
### Discussed in https://github.com/mytourbook/mytourbook/discussions/1269

<div type='discussions-op-text'>

<sup>Originally posted by **stvzldn** January 29, 2024</sup>
The Tour Book view allows the display of the Powertrain Left Right Balance which is reported in the .fit file.
However the value as displayed is not usable.  I found a discussion of how to convert the value to a usable %left - % right format.
See: https://www.thisisant.com/forum/viewthread/4604

Below is how MTB reports L-R balance:
![Image1](https://github.com/mytourbook/mytourbook/assets/106929478/c9f4a0c4-3f66-48a5-8d53-7b918e375fce)
</div>

**Comment by wolfgang-ch** [comment]
Will be available in the next version

![image](https://github.com/mytourbook/mytourbook/assets/1283445/ef698bec-cf93-4880-8e47-cbabf9ba0136)
