### ISSUE TITLE
[Bug : French Translation] 

### ISSUE THREAD

**Issue by GurVJ** [mytourbook/mytourbook#1277]
### What happened ?

@FJBDev 
Just some errors/adjustments in the french translation : 

"Traduction"
![Capture 003_20240131](https://github.com/mytourbook/mytourbook/assets/64196685/a2742485-3a9b-4e4a-b0ce-3310a0bb96f8)

"Inclure" pour garder un verbe (ou sinon "Inclus" pour le participe passé)
et "Déplacer"
![Capture 004_20240131](https://github.com/mytourbook/mytourbook/assets/64196685/b26676d9-9f0d-4f3f-a18a-2ff95a493ee9)

Problème du % mais surtout il me semble que la bonne traduction serait "Modifier la taille de la zone de délimitation" car sinon c'est équivalent au dernier libellé "Réinitialisation de la zone de délimitation"
et "Inclure".
![Capture 002_20240131](https://github.com/mytourbook/mytourbook/assets/64196685/d80edc53-ab4e-4af0-80df-f9bdd215c7a9)

### Version

24.1.0

### System

Windows

**Comment by FJBDev** [comment]
@GurVJ Good catches. I fixed the translation issues in this [PR](https://github.com/mytourbook/mytourbook/pull/1278)

**Comment by FJBDev** [comment]
@GurVJ 
Also, if you are interested in contributing to MyTourbook and help with the translation with each release, I'd be glad to pass that task to another contributor like you that seems to also speak/write fluent french 😄 
[This is the process](https://mytourbook.sourceforge.io/mytourbook/index.php/development/translation) to translate each release if you are interested

Let me know!

**Comment by GurVJ** [comment]
Thank you for proposing but I won't have enought available time to be an efficient contributor.
But I can occasionally help if needed.

**Comment by FJBDev** [comment]
> Thank you for proposing but I won't have enought available time to be an efficient contributor. But I can occasionally help if needed.

No worries, let me know if you change your mind at any point, MT can always use any help

**Comment by GurVJ** [comment]
I found a new issue in the french translation.
![image](https://github.com/mytourbook/mytourbook/assets/64196685/caabc4e8-293c-40e4-9021-e392895145ca)

**Comment by FJBDev** [comment]
> I found a new issue in the french translation. ![image](https://private-user-images.githubusercontent.com/64196685/313388182-caabc4e8-293c-40e4-9021-e392895145ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3Mjg2ODUsIm5iZiI6MTcxMDcyODM4NSwicGF0aCI6Ii82NDE5NjY4NS8zMTMzODgxODItY2FhYmM0ZTgtMjkzYy00MGU0LTkwMjEtZTM5Mjg5NTE0NWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAyMTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YjRmYjhmNTA0NTdlNDdlMWE2YjM3NGFhN2E1YzIxYzQ1MzE2ZThiODNkZTM4NmFhMGNlM2E0MjJiNzg1NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FIIaOrgDNII8DBG-Fi3XcU7MlnJEi-9HSNZUsxjMCFg)

Good catch, i will fix it for the next release
