### ISSUE TITLE
[Feature : Tour] Tour Nutrition

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1280]
### What is missing ?

Add the ability to assign food/fluids to any given tour.

For each tour, several food/beverage items could be added and their nutritional values could be retrieved from an API.

**Comment by FJBDev** [comment]
![image](https://github.com/FJBDev/mytourbook/assets/25235665/301d3cd6-0685-4156-8bbe-fdbfab805741)

![image](https://github.com/FJBDev/mytourbook/assets/25235665/57cf415a-c1ae-4b24-88ac-2d1b12bd7d11)


This new feature adds the ability to assign food & fluids to any given tour and see a summary to evaluate the quality of the nutrition during that tour.

This feature uses the public [OpenFoodFacts](https://world.openfoodfacts.org/) database

The Nutrition view contains 2 sections:

1) A section to see the product's summary
2) A section to add products where the table shows all the products assigned to a tour


![image](https://github.com/FJBDev/mytourbook/assets/25235665/57894c37-3a4c-4a89-b024-4860b8be7fbb)

Note: - Double clicking on the name of a product will open the product's webpage
![image](https://github.com/FJBDev/mytourbook/assets/25235665/54ddc19b-6b69-48f3-9ca8-ed140020a535)


The Search products dialog allows to search a product in the openfoodfacts db.
![image](https://github.com/FJBDev/mytourbook/assets/25235665/6dd3999d-9e81-4235-b77e-81328a2cd2c4)

When a product is not found, OpenFoodFacts gives the ability to easily add an existing product
![image](https://github.com/FJBDev/mytourbook/assets/25235665/98939d9a-8c77-4578-a476-5423fca384ea)

But there is also the possibility to create a custom product internally in MyTourbook
![image](https://github.com/FJBDev/mytourbook/assets/25235665/2e980387-5557-4f02-8e63-a10c9d590954)

The ability to create beverage containers allows to associate any product with a beverage container.
![image](https://github.com/FJBDev/mytourbook/assets/25235665/55987238-5ca1-480e-acf6-bb20ba999bc9)

Example: 
![image](https://github.com/FJBDev/mytourbook/assets/25235665/2abf2972-671f-4b64-9fd4-9813244d2042)



The Tour Blog View will display the list of products used as well as the averages
![image](https://github.com/FJBDev/mytourbook/assets/25235665/e9849b83-893f-4786-b291-01350edf747f)




Possible future improvements:
- Set average targets (calories/hour, L/hour, sodium/hr) in the preference page that will be used to determine a "grade"/report card in the Tour Nutrition View for each tour

- Add another food API:
  https://fdc.nal.usda.gov/api-guide.html

- Add a button "_Refresh products information_" in the preference pages AND/OR in the Nutrition view that will allow to update the tour nutrition info for all tours if any given product was updated on the remote database since it was added to the tour.

- Dialog Search Product:
Limit the number of query history to a number configurable by the user in the preferences. Also, for each search, assign a "weight" to keep the most used search names/barcodes.

- Display each beverage's concentration.
Tooltip suggestion:
`Research has shown that carbohydrate is absorbed fastest when its concentration in a fluid is in the range of 6 to 8 % (assuming normal drinking rates`
Source : Runner's World Performance Nutrition for Runners: How to Fuel Your Body for Stronger Workouts, Faster Recovery, and Your Best Race Times Ever
by [Matt Fitzgerald](https://www.barnesandnoble.com/s/%22Matt%20Fitzgerald%22;jsessionid=6D96FAE89150DAE2227108D12B1B8673.prodny_store02-atgap14?Ntk=P_key_Contributor_List&Ns=P_Sales_Rank&Ntx=mode+matchall), [Editors of Runner's World Maga](https://www.barnesandnoble.com/s/%22Editors%20of%20Runner's%20World%20Maga%22;jsessionid=6D96FAE89150DAE2227108D12B1B8673.prodny_store02-atgap14?Ntk=P_key_Contributor_List&Ns=P_Sales_Rank&Ntx=mode+matchall)

- Add a Strava preference to send the nutrition averages in the Strava description

- Add the ability to change the measurement system (L -> fl oz., mg -> oz)

**Comment by FJBDev** [comment]
@mytourbook/active-users Let me know if you want to pre-test this feature

**Comment by mff73** [comment]
Kudos for your job. 
Personally, I won't be the perfect customer for this feature 😊

**Comment by GurVJ** [comment]
The same with me 😁

**Comment by FJBDev** [comment]
@GurVJ @mff73 I guess you don't use nutrition in long rides/runs ?

**Comment by Thompson-ongithub** [comment]
> @GurVJ @mff73 I guess you don't use nutrition in long rides/runs ?

it seems like you did a lot of work for this feature and it looks very good, but I personally wouldn't use that feature. I'm not training **that** professional.
(btw: on the second to last screenshot, should the last 2 products be marked as "Beverage"?

**Comment by GurVJ** [comment]
Of course I use nutrition on long runs but it is not something I am working on it (it is much more feeling) so I have got no need now to have a tool to follow it (but maybe one day).

**Comment by FJBDev** [comment]
> it seems like you did a lot of work for this feature and it looks very good, but I personally wouldn't use that feature. I'm not training **that** professional.

Good point. And while im not a professional either, i have found that nutrition is important to me after 10h+ events/training. I was doing that before in a separate spreadsheet and thought it would be better to centralize with the rest of my data in MT

> btw: on the second to last screenshot, should the last 2 products (the water in the Salomon Flask and the Thermos) be marked as "Beverage"?

It could but in this case, because its used in a "Beverage container", it is automatically considered a beverage

**Comment by stvzldn** [comment]
The system would need to allow for mixed measurement systems given the ad hoc nature of products in the Imperial USA Zone.
"Add the ability to change the measurement system (L -> fl oz., mg -> oz)"
I assume homemade items would be under custom products.

**Comment by FJBDev** [comment]
>  I assume homemade items would be under custom products.

Correct, the custom product allows to add items that are not in the OpenFoodFacts database or products specific to each user

> The system would need to allow for mixed measurement systems given the ad hoc nature of products in the Imperial USA Zone.
What do you mean by "mixed" ?

**Comment by stvzldn** [comment]
I have tried to add Nutrition to several tours.  I find the below from possible future improvements to be very desirable:

- It may be also helpful, when the recent products can be added from the context menu in the "Tour Nutrition" views "Products list" similar like the recent tags which can be added to a tour

Nutrition is often repetitive and "boring" so putting the frequent items in the Properties->Nutrition as was done for beverage containers would be great.

**Comment by FJBDev** [comment]
> I have tried to add Nutrition to several tours. I find the below from possible future improvements to be very desirable:
> 
>     * It may be also helpful, when the recent products can be added from the context menu in the "Tour Nutrition" views "Products list" similar like the recent tags which can be added to a tour
> 
> 
> Nutrition is often repetitive and "boring" so putting the frequent items in the Properties->Nutrition as was done for beverage containers would be great.

@stvzldn Thanks for your feedback, I am glad to know that I am not the only one to use this feature 😄 
I will consider this improvement for a future version of MT.

**Comment by FJBDev** [comment]
> Nutrition is often repetitive and "boring" so putting the frequent items in the Properties->Nutrition as was done for beverage containers would be great.

And by "frequent", do you mean the nutrition items that were added most recently ? or the nutrition items that are the most used in the tour database ?

**Comment by stvzldn** [comment]
I carry just a few of the same foodstuffs on most rides: Water in bidons, bananas at 1 per 75 minutes in pocket (max 3), granola bars for break stops where I might also buy coffee or tea.
So answer is most used.  I do not track non-tour activity nutrition, just consuming to maintain weight.
