### ISSUE TITLE
[Easy Import] Square brackets are not escaped

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1286]
### Discussed in https://github.com/mytourbook/mytourbook/discussions/1276

<div type='discussions-op-text'>

<sup>Originally posted by **pstein** January 31, 2024</sup>
I installed MyTourbook v24.1. on 64bit Windows 10 (and Java OpenJDK 17) in the following path:

D:\tools\gpx\MyTourbook [test]\v24.1\

Mind the blank after "MyTourbook" and before opening bracket "[".

When I double click now on mytourbook.exe I got complaints at startup about "Illegal characters in path" 
As I found out MyTourbook does not like blanks and brackets.

Can this really be?

Modern software should be able to handle such chars. Other software can cope them without problems.
May I ask for fixing these restrictions in the next release.

Thank you
</div>

**Comment by wolfgang-ch** [comment]
Fixed in https://github.com/mytourbook/mytourbook/commit/ba4bf17dd08402b89f2ad5bc108cbb94a24631a2?diff=unified&w=1

**Comment by pstein** [comment]
When will next MTB WITH the fix above be released?

**Comment by wolfgang-ch** [comment]
> When will next MTB WITH the fix above be released?

I don't know yet, there is no fixed schedule
