### ISSUE TITLE
[Feature : Import] Import Suunto fit files battery_level

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1287]
### Discussed in https://github.com/mytourbook/mytourbook/discussions/1284

<div type='discussions-op-text'>

<sup>Originally posted by **mff73** February  3, 2024</sup>
I just discover recently that suunto files files are now containing new informations about battery_level during activities.
In fact, it seems it appears around Oct 10th 2023.
battery_level is in device_info message

There seems to be some fields in MTB for battery levels, but i don't think suunto's one are imported, or at least, i didn't see anything.</div>

**Comment by wolfgang-ch** [comment]
Fit forum battery API https://forums.garmin.com/developer/fit-sdk/f/discussion/276245/di2-battery-level

**Comment by wolfgang-ch** [comment]
After re-importing my existing tours, there are now several new devices which have no serial number

* Red box: New devices without serial #
* Blue box: The devices with a white block symbol do contain battery values, see sensor chart
* Green box: Selected device which battery values are displayed in the sensor chart

I have currently no an idea how to use these "new" devices and why they are available in the fit file. Some of them have no manufacturer # and/or no product #.

![image](https://github.com/mytourbook/mytourbook/assets/1283445/fb63291a-c6c7-4b2d-a0a5-b5f0b8fd4f17)

**Comment by wolfgang-ch** [comment]
Battery values from Suunto fit file can now be imported

The tour info tooltip shows all battery values which could be imported

![image](https://github.com/mytourbook/mytourbook/assets/1283445/b1fbd3f8-d9ca-4bd6-8de5-06b67fb6eed3)

The sensor chart shows all battery values for a selected sensor in the sensor view

![image](https://github.com/mytourbook/mytourbook/assets/1283445/4ce856c5-bad1-4e4a-beb6-4c2a5e1ad97c)

**Comment by mff73** [comment]
Hello,
I really don't know how much work it could be, so apologize in advance, do you plan to do any testing version ? I would love to test it.
Thanks.

**Comment by wolfgang-ch** [comment]
The re-import for battery values is already implemented, see re-import dialog

**Comment by mff73** [comment]
> The re-import for battery values is already implemented, see re-import dialog

Ouch, sorry, I didn't checked before asking. My bad. I never had battery values since a long time and don't re-import values that often.

**Comment by stvzldn** [comment]
Have you any idea how to identify the devices without serial number?

![Unknown Sensor in v24_5_0](https://github.com/mytourbook/mytourbook/assets/106929478/b059ede8-38ef-443d-a91f-3aa103550922)

**Comment by wolfgang-ch** [comment]
> Have you any idea how to identify the devices without serial number?

No, when a device manufacturer provides zero info about the device in the fit file, how should it be identified?

![grafik](https://github.com/mytourbook/mytourbook/assets/1283445/38e69d61-391a-444d-9390-83ad1cccbf7f)

**Comment by stvzldn** [comment]
As suspected in comment above, a low rear derailleur battery reports in the same sensor device as the front on my Edge 520.  The 520 reports on its screen which battery is low.  I have never had both batteries low on the same tour.
![Image1](https://github.com/mytourbook/mytourbook/assets/106929478/15e5191c-fe6d-4797-8925-fe7aea8a8307)

**Comment by wolfgang-ch** [comment]
When a device cannot be identified, then there will be one default device for all device values which was not yet tested. 

This device has these parameters.
* Manufacturer name : empty
* Product name : empty
* Manufacturer # : -1
* Product # : -1
* Serial # : empty
