### ISSUE TITLE
[Feature : Tour Book View] Add a context menu entry to copy/paste tour tags 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1301]
### What is missing ?

Add the ability to copy tags from a tour and paste it to another.

This feature could be added to the current contextual menu as below

![image](https://github.com/mytourbook/mytourbook/assets/25235665/04e8d967-763c-4b00-904c-4367d4f4cca5)

**Comment by wolfgang-ch** [comment]
Will be available in the next version

![image](https://github.com/user-attachments/assets/51391f69-23a0-4b2a-88d4-a280ac54b5f7)
