### ISSUE TITLE
[Feature : Tour Contextual Menu] Add the ability to customize the tour contextual menu actions 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1302]
### What is missing ?

Add the ability to customize the entries in the tour's contextual menu to display or hide actions

For example, there are some options I have never used and probably will never use or very rarely use and I would hide them to save space in the UI as the contextual menu can appear big sometimes.

![image](https://github.com/mytourbook/mytourbook/assets/25235665/341e0393-3f89-4181-8226-a6b03e528255)

Similar to the tour chart graphs selection in the preferences, add the ability to display/hide contextual menu actions.

![image](https://github.com/mytourbook/mytourbook/assets/25235665/5b4bcfc4-85c7-4803-bbb4-2ec0ec3701ad)

**Comment by wolfgang-ch** [comment]
It's not yet all done but the context menu can be very empty...

![image](https://github.com/user-attachments/assets/0ccaee46-42c8-4ca1-ada2-1d1d366a2c60)

...which is customized here

![image](https://github.com/user-attachments/assets/f04e01fa-cade-4dbb-a943-b524d7333b30)

For the recent tag actions it got a little bit complicated with this new class https://github.com/mytourbook/mytourbook/blob/ecfdb2b0168e933fbe704cbb7e7a8e17d76186d5/bundles/net.tourbook/src/net/tourbook/tag/ActionAddRecentTags.java.

The tour type actions are not yet implemented.

**Comment by wolfgang-ch** [comment]
Now all customized actions are implemented for the Tour Book view, the other tour directory views will be the next

![image](https://github.com/user-attachments/assets/0250abd9-428d-4197-9987-6a7e00fe203d)

A diamond for each checked action makes it better visible

![image](https://github.com/user-attachments/assets/ee6b9b71-c883-4565-8071-d29c30ac5720)

**Comment by wolfgang-ch** [comment]
The action "Customize Context Menu..." can show all actions or just the selected actions, see above screenshot.

To make it more visible what is selected, currently a tooltip shows the state but this needs that the mouse is hovering this action.

I think it makes it easier to see it immediately what is selected, so I would like change the wording for this action. This is my suggestion but when you have better ideas, let me know:

"Customize Context Menu..." is displayed when all actions are currently displayed
"Modify Context Menu..." is displayed when selected actions are currently displayed



![image](https://github.com/user-attachments/assets/1658b082-ea93-4b76-931d-9ab2d3167af3)

**Comment by wolfgang-ch** [comment]
After adding some tweaks, this should be the final version of this feature

![image](https://github.com/user-attachments/assets/13e928e1-7645-4f51-99c8-c2b492fbc261)

![image](https://github.com/user-attachments/assets/d5fab133-4b70-4aa5-8d43-f8ebfaa71577)
