### ISSUE TITLE
[Feature : Tour Blog]  Customize text font

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1305]
### What is missing ?

In the Tour Blog slideout, add an entry to customize the text font

![image](https://github.com/mytourbook/mytourbook/assets/25235665/f8274348-ce55-4302-835e-c4c38997af54)

**Comment by wolfgang-ch** [comment]
Is implemented


https://github.com/user-attachments/assets/fd7a4c36-359c-4893-8605-c966b955f8ca
