### ISSUE TITLE
[Bug : Junit Test]

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1314]
JUnit test failed this morning because the nutrition search request was this morning sometimes too slow and needed more than 5 seconds

https://github.com/mytourbook/mytourbook/blob/01f928c8d155bb78de0088ee157a82a5642c8701/bundles/net.tourbook.ui.tests/src/test/views/TourNutritionViewTests.java#L66-L67

**Comment by FJBDev** [comment]
Sometimes this happens. It can also happen for the POI View test where it takes too long.
In this case, i either ignore it or restart the tests

**Comment by FJBDev** [comment]
For now i will close the issue but when it happens too often, then i usually mock the http response
