### ISSUE TITLE
[Bug : net.tourbook.common] Table context menu has had the wrong parent and is recreated. 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1316]
### What happened ?

Not sure what made this exception appear not how to reproduce it but I thought I would create an issue for future reference

### Version

24.1

### System

Linux

### Relevant log output

```shell
An exception stack trace is not available.
```

**Comment by wolfgang-ch** [comment]
We already discussed this issue in https://github.com/mytourbook/mytourbook/issues/1118

**Comment by FJBDev** [comment]
My bad, I forgot about it. Closing this as a duplicate
