### ISSUE TITLE
[Feature : Segmentation] Automatic markers

### ISSUE THREAD

**Issue by benoitroger** [mytourbook/mytourbook#1319]
### What is missing ?

Hello,
Would it be possible to add the functionality of adding automatic markers.
I am thinking for example of using segmentation every X kilometers or X hours then inserting the corresponding markers.
Thank you
Benoît

**Comment by wolfgang-ch** [comment]
Original discussion https://github.com/mytourbook/mytourbook/discussions/1317

**Comment by wolfgang-ch** [comment]
This feature will be available in the next version.

It needs 2 steps to create markers, why? 

It could be possible to accidentally create thousands of markers for long tours and small marker position values. To prevent this, firstly the "Validate Makers" and then the "Create Markers" buttons have to be pressed

https://github.com/user-attachments/assets/a7f81a96-d33c-48c8-aaf5-86b222c9996b
