### ISSUE TITLE
[Bug : TourBookView] "Go to last tour" doesn't work in all cases 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1325]
### What happened ?

The button "Go to last tour" doesn't work properly.
Example:
- Activate the NatTable and sort the tours by date
- Clicking on "Go to last tour" will go to the bottom tour but not the last one.

In the example below, the last tour should be the one above, from 2023, NOT 2015

![image](https://github.com/mytourbook/mytourbook/assets/25235665/49aceb4b-fced-4ff1-a0b3-bded0b26f466)

### Version

24.1

### System

All

**Comment by wolfgang-ch** [comment]
> The button "Go to last tour" doesn't work properly

This button do not say "Go to the last tour sorted by date". When the view is sorted by distance, which tour should this button select?

The text is intentionally "Go to last tour" and not "Go to today" maybe we should have written "Go to tour at the bottom". 

I know that I have thought about the wording of this button because the request was "Implementing goto today action" https://github.com/mytourbook/mytourbook/issues/1173

**Comment by FJBDev** [comment]
> This button do not say "Go to the last tour sorted by date". When the view is sorted by distance, which tour should this button select?
> 
The button says "Go to last tour". In english, when I read that, I understand that "last" means my last tour, the most recent one.
Hence, when the tour is sorted by distance, i would understand that "Go to last tour" still should go to my most recent tour. But maybe I misunderstood

**Comment by wolfgang-ch** [comment]
We can change the wording for the current implementation with my suggestion "Go to tour at the bottom" or similar.

The action "Go to most recent tour" needs to be implemented and can be more complex than it looks like, a tour can be somewhere in the middle and the flat view has paged loading from the db

**Comment by FJBDev** [comment]
We can change it indeed, i am just not sure who needs such a function "go to tour at the bottom". I only want to go to the latest/most recent tour, but that is maybe just me

**Comment by mff73** [comment]
In my case, I discovered, while using this function, that "last tour" means "bottom tour".
I must admit that I use it only for "most recent tour", thus date sorted.
But, I have no idea what could be the use case of going to most recent tour, while having the list sorted by anything else than date 🤔😊.

**Comment by wolfgang-ch** [comment]
I changed the wording to "Select tour at the end of the tour list".

**Comment by wolfgang-ch** [comment]
> But, I have no idea what could be the use case of going to most recent tour, while having the list sorted by anything else than date 🤔😊.

When you are looking for a similar tour by e.g. distance or time
