### ISSUE TITLE
[Bug : Cloud] Strava not connecting

### ISSUE THREAD

**Issue by gregoryxxxxxx** [mytourbook/mytourbook#1339]
### What happened ?

Token expired per expiration date but didn't renew / reconnect. Attempting to disconnect / reconnect Strava results in an error. Tried Firefox, Edge, and Chrome - different syntax, but the short version is nothing is responding to the URL. The URL is something like, "http://localhost:4918/?state=&code=..." and it seems that nothing is listening on 4918. 

Tried disabling "windows firewall" just in case. Same result. 

### Version

24.1.0

### System

Windows

**Comment by FJBDev** [comment]
This is a known issue that will be fixed in 24.5

See [here](https://github.com/mytourbook/mytourbook/issues/1337)
