### ISSUE TITLE
[Feature : Tour Pauses View] Map synchronization 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1352]
### What is missing ?

When clicking on a specific pause in the Tour Pauses View, the 2D map should be centered at the location of the clicked pause (similar to the Tour marker view behavior)

**Comment by wolfgang-ch** [comment]
This should work when the chart slider is synched

![image](https://github.com/mytourbook/mytourbook/assets/1283445/2361fdf6-31b5-4803-8bc5-72152cccd979)

**Comment by FJBDev** [comment]
> This should work when the chart slider is synched
> 
While this works, this is not required in the Tour Marker View and therefore IMO, it should not be required for when clicking on a tour pause from the tour pause view

**Comment by wolfgang-ch** [comment]
> > This should work when the chart slider is synched
> 
> While this works, this is not required in the Tour Marker View and therefore IMO, it should not be required for when clicking on a tour pause from the tour pause view

When a marker is selected in the tour markers view, it is synched with different synch actions but a synch action needs to be selected. When a synch action is not selected then also a marker is not synched, this is OK for me. But propably for historical reasons a marker is synched with different synch actions.

**Comment by FJBDev** [comment]
>this is OK for me.

Then I guess you can close this feature request. I don't like when to do a same action, 2 different scenario need to be done so it's not really "ok for me" but I'll let you decide in the end.

**Comment by wolfgang-ch** [comment]
The sync feature needs to be cleaned up / extended that there are no "hidden" synchronisations

**Comment by wolfgang-ch** [comment]
This came now back in my mind, that there is also a historical reason why there is not an action for every different sync item. In the beginning there was no slideout for the sync actions and instead of increasing the number and space of sync actions in the toolbar, they were combined.

**Comment by wolfgang-ch** [comment]
I fixed several sync issues in https://github.com/mytourbook/mytourbook/commit/a54308792118ab213b7fa4201401552861769333 and changed the wording of the tooltip

![image](https://github.com/user-attachments/assets/add41071-875d-4c96-98dd-4f134bf68f2d)
