### ISSUE TITLE
[Bug : Weather Reimport lost Info about the Clouds] 

### ISSUE THREAD

**Issue by telemaxx** [mytourbook/mytourbook#1353]
### What happened ?

Seems so that i canot reimport some weather data.

i import fresh tours, every about weather is fine:
(Date,Clouds,Weathertemp,Air Quality, Winddirection)

![grafik](https://github.com/mytourbook/mytourbook/assets/22706487/ab054b3a-8190-4187-ba40-205778880608)

now i reimport the weather data of one tour:

![grafik](https://github.com/mytourbook/mytourbook/assets/22706487/7fa15dc7-73ad-45ce-b24e-d8c7063b54cb)

Temp Wind and the new Air Quality is still ok, but now clouds anymore:

![grafik](https://github.com/mytourbook/mytourbook/assets/22706487/4aae6bb0-bf2e-486b-adb2-9fb1208f1842)

Idea?

### Version

24.5.0

### System

Windows

### Relevant log output

```shell
[MTB] [TourLog] 10:30:53 [main - 1                 ] 39             Reimport von diesen Werten:  Wetter
[MTB] [TourLog] 10:30:53 [Re-importing tours - 86  ] 40    OK          23.05.2024, 18:22 ? D:\BTSync\Exchange\gpx\2024\20240523-182208-Hannover_E-Bike-Fahren_Edge_840.fit
[MTB] [TourLog] 10:30:53 [Re-importing tours - 86  ] 41    INFO        Vorherige Daten: Ein paar Wolken,  ?, ø0°C, ^0°C, ?0°C, ~0°C,  - Aktuelle Daten: , , ø22°C, ^22°C, ?22°C, ~21°C, Ungesund
[MTB] [TourLog] 10:30:53 [main - 1                 ] 42             Reimportiert in 0,522 s
```

**Comment by FJBDev** [comment]
If you reimport weather data from a fit file that doesnt contain cloud information, then it will reset it just like if you were to import it for the first time.
To get the cloud information, you will need to retrieve the weather from a cloud vendor again

**Comment by telemaxx** [comment]
sorry for my late answer.

my fit files are coming from garmin, not sure if they contain already weather information's from garmin.

when i import first time i got temp clouds etc mtb receives weather from my weather provider owm.

when i do i reimport of weather or the complete tour the weather information are gone.
device temp is still ok.

my hope was to use historical weather for my older tours.

> New + improvements: While the weather retrieval for this vendor remains free and the historical weather data can be retrieved for the last 40+ years (from January 1st 1979), the total number of requests per day is limited to 1000 for all users.

**Comment by FJBDev** [comment]
> my fit files are coming from garmin, not sure if they contain already weather information's from garmin.

Can you attach one example file ? I will import it and be able to tell you if the original file already contains weather information


> my hope was to use historical weather for my older tours.
> 
> > New + improvements: While the weather retrieval for this vendor remains free and the historical weather data can be retrieved for the last 40+ years (from January 1st 1979), the total number of requests per day is limited to 1000 for all users.

Yes, you can use OpenWeatherMap in the 24.5 release to retrieve the weather for all your old tours

**Comment by telemaxx** [comment]
> Can you attach one example file ? I will import it and be able to tell you if the original file already contains weather information

Sure.

[20240330-112938-Havixbeck_E-Bike-Fahren_Edge_530.zip](https://github.com/mytourbook/mytourbook/files/15502866/20240330-112938-Havixbeck_E-Bike-Fahren_Edge_530.zip)

**Comment by FJBDev** [comment]
> Sure.
> 
> [20240330-112938-Havixbeck_E-Bike-Fahren_Edge_530.zip](https://github.com/mytourbook/mytourbook/files/15502866/20240330-112938-Havixbeck_E-Bike-Fahren_Edge_530.zip)

Thanks. 
I just imported your file in MT 24.5 and there is indeed no weather information except for the temperature so this is why you are not seeing any clouds when importing or re-importing the tour
I also have an Edge 530 and I have never seen myself weather information within the FIT files from the unit

![image](https://github.com/mytourbook/mytourbook/assets/25235665/0146abb9-ab25-4cfd-b773-0da4aac19e0a)

**Comment by telemaxx** [comment]
The strange thing is, that the 1st import is OK.
MyTourBook fills the Weatherdata correctly with the help of Openweathermap.

when i re-import a tour this existing weather data are gone.

> To get the cloud information, you will need to retrieve the weather from a cloud vendor again

but how? ;-)

**Comment by FJBDev** [comment]
> The strange thing is, that the 1st import is OK. MyTourBook fills the Weatherdata correctly with the help of Openweathermap.
> 

Maybe it is "OK" because you have chosen to automatically retrieve the weather when importing a tour ?

> when i re-import a tour this existing weather data are gone.

When you reimport, the weather from the device is reimported and therefore overwrites the weather retrieved with a vendor.
> 
> > To get the cloud information, you will need to retrieve the weather from a cloud vendor again
> 
> but how? ;-)

By using the contextual menu "Retrieve weather data"

![image](https://github.com/mytourbook/mytourbook/assets/25235665/84aed15d-2bd4-40b6-8b65-8a2bc82a4652)


I hope this helps!

**Comment by telemaxx** [comment]
sorry for my late answer.

i used "Re-import tours-> Weather"
this was the wrong way.

"Adjust Tour Values" did the Job. Thank you for the hint! @FJBDev 

Today i imported some tours with the import wizard.
In the past some of them where to old to receive OSM Weather.
But now it was working without Problems.

Next test was receiving weather for already imported old tours.
i got the message "limit of 50 per day reached"
This is ok. I will try tomorrow.

But i can say it is a great improvement.
Together with automated start/stop location via wizard.

So i am happy and close the ticket.
