### ISSUE TITLE
[Bug : Location] : Can' start app after upgrade from 23.8.0

### ISSUE THREAD

**Issue by rsilux** [mytourbook/mytourbook#1355]
### What happened ?

I installed 24.5.0 from 23.8.0. Now I get an error after the splash screen. Not sure what is wrong. Problem is also I can't downgrade as 23.8.0 is no longer available online. 
![image](https://github.com/mytourbook/mytourbook/assets/170818588/05ab2d7e-91a8-4be1-9cfe-4c4701119d04)
[1716653152448.log](https://github.com/mytourbook/mytourbook/files/15444155/1716653152448.log)

### Version

24.5.0

### System

Windows

### Relevant log output

```shell
Logfile attached.
```

**Comment by FJBDev** [comment]
>java.version=11.0.10

You need to install java 17.
The easiest solution would be to download and install MT with Java included

**Comment by rsilux** [comment]
Thanks that did the trick. I should have known this. Sorry for the inconvenience.
