### ISSUE TITLE
[Feature : Tour Tags] Add an option to reset recent tags

### ISSUE THREAD

**Issue by GurVJ** [mytourbook/mytourbook#1366]
### What is missing ?

When adding tags in the Tour Editor, we have the choice in a list of the last used tags.
Would it be possible to have the ability to reset this list with for example a Reset function in the contextual menu ?

It would be helpful in cases where some tags are no more used but are kept in the list because no more new tags are added to this list.

In the following example, I've got twice the same shoes model in the list but only one is now active (and I don't want to erase the old tag in order to keep history).
![image](https://github.com/mytourbook/mytourbook/assets/64196685/d1b9b36e-8433-49d0-993e-c67a0895ec3a)

Another way to deal with this would be to add an Active/Not Active status in the Tags window management, and only Active tags would be listed in the Tour Editor.

**Comment by wolfgang-ch** [comment]
There is a workaround to reset the recent tag list:
* Create a dummy tag
* Delete the dummy tag

Deleting a tag will always reset the recent tag list, this is the way how it is currently implemented

**Comment by GurVJ** [comment]
Thank you for the tip @wolfgang-ch !

**Comment by wolfgang-ch** [comment]
The recent items can now be removed from the tags and tour types

![image](https://github.com/user-attachments/assets/2a03fc97-52b9-4616-b8af-88828002dd6d)


![image](https://github.com/user-attachments/assets/c2b49f46-598f-43c3-b659-34e68bc06376)
