### ISSUE TITLE
[Feature : 2D Map Points] Paint map items which are not overlapping

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1369]
### What is missing ?

This is the implementation of this request https://github.com/mytourbook/mytourbook/issues/1323

# Map Points

This screenshot shows many features (but not all) which are currently implemented

![map2-map-points-2407](https://github.com/mytourbook/mytourbook/assets/1283445/b07d37c6-7683-4a25-94e6-146d4dc5f901)

2 tours are selected but the tour track is not displayed

1. Tour label
2. Tour pause
3. Tour start location
4. Tour end location
5. Tour start & end location
6. Tour location, a related tour is not selected
7. Common location, this is not related to any tour

 
# Map Point Properties

Map point properties can be expanded or collapsed

![map2-map-points-options-10-collapsed-2407](https://github.com/mytourbook/mytourbook/assets/1283445/2b91c0e0-bb62-4f8e-9d8d-95857811fe20)

![map2-map-points-options-01-all-2407](https://github.com/mytourbook/mytourbook/assets/1283445/a8deacff-a4b3-48f3-a681-8b1a2eed7405)

![map2-map-points-options-02-options-2407](https://github.com/mytourbook/mytourbook/assets/1283445/4449b327-ff29-4f35-a0cf-d96d888333c7)

![map2-map-points-options-03-tour-markers-2407](https://github.com/mytourbook/mytourbook/assets/1283445/ac1c33dc-047d-4815-92fe-50d376f6ecd9)

![map2-map-points-options-04-marker-groups-2407](https://github.com/mytourbook/mytourbook/assets/1283445/b7587f33-8213-4574-8261-42934cdb8396)

![map2-map-points-options-05-tour-pauses-2407](https://github.com/mytourbook/mytourbook/assets/1283445/f5d0bdcf-0882-46b4-8791-4dcbe6f49fd7)

![map2-map-points-options-06-tour-locations-2407](https://github.com/mytourbook/mytourbook/assets/1283445/207419a9-19a1-413e-a0ee-c95554c77ea6)

![map2-map-points-options-07-common-locations-2407](https://github.com/mytourbook/mytourbook/assets/1283445/0fb963b4-69e5-4a7e-8007-4ec9909a43e7)

**Comment by wolfgang-ch** [comment]
My railway crossing waiting times

![image](https://github.com/mytourbook/mytourbook/assets/1283445/725ed9c9-f892-4a23-b911-6563b9dbb02b)

Sometimes you have to wait many minutes when 2, 3, or 4 trains are crossing

![image](https://github.com/mytourbook/mytourbook/assets/1283445/2b76351c-a0fe-4dc3-b812-bbc3aeb85ffc)

**Comment by FJBDev** [comment]
This makes me think that a fun feature would be to aggregate all those small pauses into a big one to see how long you've waited total for the trains 😄

**Comment by FJBDev** [comment]
When I use the latest `main`, the tour markers are not displayed in my 2D map and I see this error

![image](https://github.com/mytourbook/mytourbook/assets/25235665/54973143-852e-473f-a71e-d345f2a21d1d)

```

!ENTRY net.tourbook.common 4 0 2024-06-26 22:05:04.776
!MESSAGE Invalid thread access
!STACK 0
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.widgets.Display.error(Display.java:1286)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:863)
	at org.eclipse.swt.widgets.Display.getPrimaryMonitor(Display.java:2245)
	at org.eclipse.swt.widgets.Display.getSystemFont(Display.java:2459)
	at org.eclipse.swt.graphics.Image.internal_new_GC(Image.java:2156)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:171)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:135)
	at de.byteholder.geoclipse.map.Map2.paint_MapPointImage_10_Runnable(Map2.java:6692)
	at de.byteholder.geoclipse.map.Map2.lambda$13(Map2.java:6603)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by wolfgang-ch** [comment]
The deleted comment is in https://github.com/mytourbook/mytourbook/issues/1376

**Comment by wolfgang-ch** [comment]
> This makes me think that a fun feature would be to aggregate all those small pauses into a big one to see how long you've waited total for the trains 😄

I also had a new idea to create a view which lists all visible map points which could be summarized
