### ISSUE TITLE
[Feature : Tour Pauses] Replace tour pauses with tour break times

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1372]
### What is missing ?

Because of estimated tour pauses in tcx imports https://github.com/mytourbook/mytourbook/issues/1370, there is a need to have better tour pauses.

This request implemented these features:

* TCX import can be configured to use tour break times instead of tour pauses 

![image](https://github.com/mytourbook/mytourbook/assets/1283445/f215b80b-ee9c-4237-96ea-efcfbf70461a)

* A new action is available to replace tour pauses with tour break times

![image](https://github.com/mytourbook/mytourbook/assets/1283445/224c5d19-b596-4d04-a11e-f893bf74a418)

* A new action is available to compute tour break times with the current break time preference in the preferences

![image](https://github.com/mytourbook/mytourbook/assets/1283445/a949e82d-96be-45bb-849d-defee79a6f81)

**Comment by wolfgang-ch** [comment]
Comparison between old pauses (left image) and new pauses which are using the computed break times. All pauses below 5 minutes are filtered out.

![image](https://github.com/mytourbook/mytourbook/assets/1283445/dc5476fc-dd9e-4939-b68e-1227ab135aad)

**Comment by FJBDev** [comment]
A good improvement would be for MT to detect how the TCX was formed and what type of pauses need to be imported instead of having the user guess and know what types of pauses are in the TCX file

**Comment by wolfgang-ch** [comment]
I'm now happy with the current solution because it find's correctly the longer pauses.
