### ISSUE TITLE
[Feature : Search Tours] Expand Search Result to show Distance , Average Speed, and Total Climb

### ISSUE THREAD

**Issue by stvzldn** [mytourbook/mytourbook#1379]
### What is missing ?

Often I will do a Tour Search to compare a current tour with prior. However the Search Result display options are limited to Description, Start, and Weather plus the start date/time. I have to open each tour to see speed and elevation gain to compare to my latest effort.
* Under Result Options add: Show average speed, average elevation gain, total distance.
* Under Sorting Options to sort the results by speed or elevation as well as by date,

**Comment by wolfgang-ch** [comment]
Discussed in https://github.com/mytourbook/mytourbook/discussions/1378

**Comment by wolfgang-ch** [comment]
Instead of expanding the fulltext search, would it be an option to show the fulltext search result tours (only the tours) in the tourbook view which has all these sort and column options.

**Comment by stvzldn** [comment]
> an option to show the fulltext search result tours (only the tours) in the tourbook view which has all these sort and column options.

Yes, then can use the TourBook view as a "report" as the Search reports some other less useful stuff (e.g. item number, doc ID, maybe weather).
Although missing from TourBook view is Tour Description which does show in Search (maybe another Feature request).
One thought is to have "Search Results" Tour Type Filter.

**Comment by wolfgang-ch** [comment]
The tour search result can now be pushed into the tourbook view and is displayed as a filtered collection 

![image](https://github.com/user-attachments/assets/1734d4af-a764-4c0e-a37a-49dab2fd9bb5)


https://github.com/user-attachments/assets/6016e6fb-9b1b-4ca6-ab7f-17b0262cfd8e
