### ISSUE TITLE
[Bug : Expanding Tour List Items] 

### ISSUE THREAD

**Issue by peter-rindfuss** [mytourbook/mytourbook#1398]
### What happened ?

When I select some years in the tour list and try to expand them with the right context menu ("Expand selection"), all years are expanded. When I use the (+) sign instead, only the last of the selected years is expanded. Both ways do not work as expected.

### Version

24.8.0

### System

Windows

**Comment by wolfgang-ch** [comment]
Thanks for this discovery

The correctly working code was deactivated 2023-09-06 in 3adbf8fdc514ebf1813f40a03fabd8ae0732c079, propably for debugging and was never activated again. This issue applys also to these views

![image](https://github.com/user-attachments/assets/672203c2-52d6-4890-b503-6c7e3ba61c77)

**Comment by peter-rindfuss** [comment]
Thanks.
