### ISSUE TITLE
[Bug : Location] Update to 23.8 destroys database

### ISSUE THREAD

**Issue by Marty56** [mytourbook/mytourbook#1404]
### What happened ?

Under MacOS I have updated from 23.1 to 24.8.
All data starting from Oct. 2023 is gone. So I lost almost one year of data.

### Version

23.8

### System

Windows

### Relevant log output

```shell
nA.
```

**Comment by Marty56** [comment]
I restored the db with timemachine and want to downgrade to version 23.1 but I cannot find it anymore because there a no downloads in the GitHub repro for this version. 
Please help.

**Comment by Marty56** [comment]
I have restored the db via Time Machine and downloaded 24.7 but also this version destroys the db.
In the update dialog it says db needs to be updated from 51 to 55.
Maybe the previous version was even older than 23.1.

**Comment by Marty56** [comment]
23.3.0 is not able to read version 51
24.1 update is failing.

I am lost. I need a version that is support version 51 out of the box. Please help

**Comment by wolfgang-ch** [comment]
>23.3.0 is not able to read version 51

What happens, can you provide a screenshot

DB version 51 is MT version 23.8 https://github.com/mytourbook/mytourbook/blob/bd06e5771be598fb3cd9fa7b9edbd944f07f99cb/bundles/net.tourbook/src/net/tourbook/database/TourDatabase.java#L126


Version of MT which are older than 19.10 are available here https://sourceforge.net/projects/mytourbook/files/MyTourbook/

**Comment by wolfgang-ch** [comment]
The MT 23.8 download is disabled because of this issue https://mytourbook.sourceforge.io/mytourbook/index.php/history/history-2023 however I could provide you a 23.8 download file

**Comment by wolfgang-ch** [comment]
> Under MacOS I have updated from 23.1 to 24.8.

There was never a MT 23.1 version

A DB downgrade is not supported

**Comment by Marty56** [comment]
> The MT 23.8 download is disabled because of this issue https://mytourbook.sourceforge.io/mytourbook/index.php/history/history-2023 however I could provide you a 23.8 download file

This would be appreciated because with this version I could at least update my backup.

**Comment by Marty56** [comment]
> > 23.3.0 is not able to read version 51
> > 24.1 update is failing.
> 
> What happens, can you provide a screenshot
> 
> DB version 51 is MT version 23.8
> 
> https://github.com/mytourbook/mytourbook/blob/bd06e5771be598fb3cd9fa7b9edbd944f07f99cb/bundles/net.tourbook/src/net/tourbook/database/TourDatabase.java#L126
> 
> Version of MT which are older than 19.10 are available here https://sourceforge.net/projects/mytourbook/files/MyTourbook/

The new version states that it needs to upgrade the db. When I confirm this upgrade takes place and there is no error.
But then in the new version all files from October 2023 onwards are gone. I would assume about 40 - 60 gps tracks.

**Comment by wolfgang-ch** [comment]
> > The MT 23.8 download is disabled because of this issue https://mytourbook.sourceforge.io/mytourbook/index.php/history/history-2023 however I could provide you a 23.8 download file
> 
> This would be appreciated because with this version I could at least update my backup. I would need an x86 version.

Do you need the MacOS Arm or MacOS x86 ?

**Comment by wolfgang-ch** [comment]
> > > The MT 23.8 download is disabled because of this issue https://mytourbook.sourceforge.io/mytourbook/index.php/history/history-2023 however I could provide you a 23.8 download file
> > 
> > 
> > This would be appreciated because with this version I could at least update my backup. I would need an x86 version.
> 
> Do you need the MacOS Arm or MacOS x86 ?

I had enough diskspace, so I've uploaded both. You can download MT 23.8 from https://www.dropbox.com/sh/v6kni9jof54pg2m/AAB8wMp96vH8Q2fZ_saoUPxWa?dl=0

**Comment by Marty56** [comment]
Thanks for the upload.
I have installed this version and receive no error. 
But unfortunately the newer files are still missing.

Maybe I have to restore further folders.
Right now, I have only restore the folder "mytourbook" under the /User/<username>/

Do i have to restore more folders?

**Comment by wolfgang-ch** [comment]
`C:\Users\<YOURNAME>\mytourbook\` is the only folder on e.g. Windows where MT data are stored there is no other data folder, only a program folder with the program code but this do not contain any user data

**Comment by Marty56** [comment]
Thanks Wolfgang for your great support.
As it is often, I have found the root cause which was my stupidity.
I had edited the config.ini and pointed the data folder to a different location.

Sorry for my stupidity
