### ISSUE TITLE
[Bug : Location] Automatic markers

### ISSUE THREAD

**Issue by benoitroger** [mytourbook/mytourbook#1407]
### What happened ?

Hello,
Thank you very much for this new "automatic markers" function that I was impatiently waiting for.
I installed version 24.9.1, the right click does not make the function appear.
Thank you
![Capture](https://github.com/user-attachments/assets/c0b61acc-4ee9-46bf-8e92-1693e71c30de)

### Version

24.9.1

### System

Windows

**Comment by wolfgang-ch** [comment]
> I installed version 24.9.1, the right click does not make the function appear.

In https://github.com/mytourbook/mytourbook/issues/1319#issuecomment-2367256942 I had written `This feature will be available in the next version.`

So the next version is **AFTER** 24.9.1

My screenshot displays 24.9.1 but this is my development environment and do not display the next version number which will be 24.???

**Comment by benoitroger** [comment]
AH ok, sorry, I'm so impatient to have this function that I read the information halfway...
