### ISSUE TITLE
[Feature : Tour Info Tooltip] Customize the content of the tour info tooltip

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1411]
### What is missing ?

Over the last years, the conent in the tour info tooltip was growing and growing but not everbody want's or need's all info, the content can now be customized.

https://github.com/user-attachments/assets/f69e084d-1955-4299-ba16-c0021c8da32c

**Comment by Thompson-ongithub** [comment]
When disabling "Show weather values" (around 11th second in the video) the values of second column (Heart Rate, Speed, Pace ... until Elevation) move a bit to the left. They move right again, if the weather values are enabled. 
Tested on Linux, with 24.11.0 from October 27th.

**Comment by wolfgang-ch** [comment]
Tour labels, values and units are aligned in colums, otherwise it would look too ugly. When the weather values are displayed, then the first column is wider because of the avg. Temperture label

![image](https://github.com/user-attachments/assets/bb64391a-6a63-4f17-8ce2-cf911fd57340)

**Comment by Thompson-ongithub** [comment]
aaah. I didn't realize it was the average temperature that moved the column
