### ISSUE TITLE
[Feature : Tour Location] Bulk renaming Start and End location

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#1413]
### Discussed in https://github.com/mytourbook/mytourbook/discussions/1409

<div type='discussions-op-text'>

<sup>Originally posted by **Thompson-ongithub** October 10, 2024</sup>
Is there a easy way to bulk rename the Start and End location fields?
The reason is that with the (rather) new feature of automatic Start / End locations the ways those locations are noted are different from when I inserted them by hand, leaving me now with quite a lot of double entries...

Thanks.</div>

**Comment by wolfgang-ch** [comment]
This feature will be available in th e next version

https://github.com/user-attachments/assets/bcd27882-d671-4754-a63e-92c78fbfe48e


* The start/end location field are filled with the content of the selected tours when they are unique
* When the tour already contains a location association, this can be removed

![image](https://github.com/user-attachments/assets/90517404-3945-44d6-a6db-3300a7a13976)

**Comment by Thompson-ongithub** [comment]
Wow, that was fast! Thank you very much!
