### ISSUE TITLE
[Bug : Location] photo thumbnails in 2D Map and 2.5DMap are corrupt. Higt quality is ok in 2DMap

### ISSUE THREAD

**Issue by telemaxx** [mytourbook/mytourbook#1414]
### What happened ?

When i 1st time open the map2 after updating to 24.9.1 the checkbox "show high quality photo images" is not set to on and
all photo are corrupt:

![grafik](https://github.com/user-attachments/assets/8a8c8750-f122-4afc-95e9-4bd796f8604d)

when i set this checkbox to on, photo are ok inside map2:

![grafik](https://github.com/user-attachments/assets/54b97556-50b1-45bf-97f8-60f37297971f)

but in map25 i currently dont have this checkbox:

![grafik](https://github.com/user-attachments/assets/fe7a606d-03bb-4c0b-891d-a4a96f075e95)

### Version

24.9.1

### System

Windows

### Relevant log output

```shell
[MTB] CREATE FUNCTION avgPace (tourTime BIGINT, tourDistance BIGINT)
[MTB] RETURNS REAL
[MTB] PARAMETER STYLE JAVA
[MTB] NO SQL LANGUAGE JAVA
[MTB] EXTERNAL NAME 'net.tourbook.ext.apache.custom.DerbyCustomFunctions.avgPace'
[MTB] 
[MTB] 11:12:57.265Number of processors: 12
[MTB] Warning: NLS unused message: BlockedJobsDialog_UserInterfaceTreeElement in: org.eclipse.ui.internal.progress.messages
[MTB] net.tourbook.srtm.ElevationFile - open \C:\Users\top\mytourbook\srtm3\N52E009.hgt
[MTB] 11:13:24.699'341 AWT: LoadImg-HQ-0    20240929_135635.jpg  total:   620  load:   449  resizeHQThumb: 164  saveHQThumb:    7  
[MTB] 11:13:24.699'347 AWT: LoadImg-HQ-1    20240929_143925.jpg  total:   619  load:   426  resizeHQThumb: 176  saveHQThumb:   17  
[MTB] net.tourbook.srtm.ElevationFile - open \C:\Users\top\mytourbook\srtm3\N52E008.hgt
[MTB] 11:17:46.524'785 AWT: LoadImg-HQ-4    20240918_145638.jpg  total:   541  load:   338  resizeHQThumb: 195  saveHQThumb:    8  
[MTB] 11:17:46.586'891 AWT: LoadImg-HQ-2    20240918_132151.jpg  total:   604  load:   404  resizeHQThumb: 196  saveHQThumb:    4  
[MTB] 11:17:46.612'232 AWT: LoadImg-HQ-7    20240918_180032.jpg  total:   561  load:   388  resizeHQThumb: 166  saveHQThumb:    6  
[MTB] 11:17:46.638'585 AWT: LoadImg-HQ-6    20240918_164229.jpg  total:   589  load:   411  resizeHQThumb: 174  saveHQThumb:    4  
[MTB] 11:17:46.650'267 AWT: LoadImg-HQ-5    20240918_161651.jpg  total:   602  load:   435  resizeHQThumb: 162  saveHQThumb:    5  
[MTB] 11:17:46.715'537 AWT: LoadImg-HQ-3    20240918_115811.jpg  total:   630  load:   457  resizeHQThumb: 170  saveHQThumb:    2  
[MTB] 11:17:47.040'248 AWT: LoadImg-HQ-8    20240918_115811.jpg  total:   443  load:   315  resizeHQThumb: 121  saveHQThumb:    4  
[MTB] 11:17:47.619'852 AWT: LoadImg-HQ-9    20240918_132151.jpg  total:   403  load:   259  resizeHQ: 113  saveHQ:   31  resizeThumb:   0  saveThumb:   0
[MTB] 11:17:51.410'325 AWT: LoadImg-HQ-10   20240918_162510.jpg  total:   360  load:   250  resizeHQThumb: 107  saveHQThumb:    3  
[MTB] 11:17:51.562'332 AWT: LoadImg-HQ-11   20240918_151607.jpg  total:   354  load:   246  resizeHQThumb: 106  saveHQThumb:    2  
[MTB] [LWJGL Application] INFO org.oscim.gdx.GdxMap - Type: OpenGL
[MTB] Version: 4:6:1
[MTB] Vendor: ATI Technologies Inc.
[MTB] Renderer: AMD Radeon(TM) Graphics
[MTB] Number of animations: 1  using animation.skateboard.new
[MTB] [PBRShader] Shader compilation success
[MTB] [PBRShader] Shader compilation success
[MTB] [PBRShader] Shader compilation success
[MTB] 11:19:22.245'397 AWT: LoadImg-HQ-1    20240918_145638.jpg  total:   370  load:   214  resizeHQ: 120  saveHQ:   35  resizeThumb:   0  saveThumb:   0
[MTB] 11:19:43.582'144 AWT: LoadImg-HQ-0    20240918_151607.jpg  total:   377  load:   239  resizeHQ: 110  saveHQ:   28  resizeThumb:   0  saveThumb:   0
[MTB] 11:23:42.838'628 AWT: LoadImg-HQ-4    20240918_180032.jpg  total:   425  load:   269  resizeHQ: 115  saveHQ:   40  resizeThumb:   0  saveThumb:   0
[MTB] 11:25:08.338'133 AWT: LoadImg-HQ-2    20240918_164229.jpg  total:   429  load:   276  resizeHQ: 112  saveHQ:   41  resizeThumb:   0  saveThumb:   0
[MTB] 11:25:20.327'318 AWT: LoadImg-HQ-7    20240918_162510.jpg  total:   380  load:   236  resizeHQ: 110  saveHQ:   34  resizeThumb:   0  saveThumb:   0
[MTB] 11:26:16.308'193 AWT: LoadImg-HQ-6    20240918_161651.jpg  total:   396  load:   249  resizeHQ: 118  saveHQ:   29  resizeThumb:   0  saveThumb:   0
```

**Comment by wolfgang-ch** [comment]
I cannot verify this issue

When "show high quality photo images" is not selected, then the thumbnail images are displayed in the 2D map, the 2.5D map shows always the thumbnail images. Each photo image file contains mostly also the thumbnail image which is very small and loaded very fast.


![image](https://github.com/user-attachments/assets/346c7461-fe5f-4a01-a011-d9cd3b1f36b3)


How do look the photo images in the tour photo view when the image size is below 160 pixel which will show the thumbnail images

![image](https://github.com/user-attachments/assets/97a09767-3bf6-4a0d-92dc-7b20ce79d90f)

**Comment by telemaxx** [comment]
with 62pixel it looks bad:

![grafik](https://github.com/user-attachments/assets/0f0821bc-18ed-44fe-8efd-f61c7bd5b2de)

with 161px it looks good:

![grafik](https://github.com/user-attachments/assets/285c94ae-b5f6-47e0-aeb8-e81744f732a5)

seems to be a problem with the thumnails.

BTW: in the map2 i can change the size in 1px steps.
in the "tour photo view" the mousewheel changes the size by about 40px and i can not enter a free number with the keyboard.
and the localization text is missing ;-)

![grafik](https://github.com/user-attachments/assets/b093e845-da5b-4d2a-b567-2db6aa147637)

**Comment by wolfgang-ch** [comment]
> in the "tour photo view" the mousewheel changes the size by about 40px and i can not enter a free number with the keyboard.

The mousewheel has AI since 12 years 😎 

The algorithm behind the mousewheel sets the size that always all displayed images are not truncated at the right border !

> and the localization text is missing ;-)

Will be available in the next version, there were not many new texts in the last version, so I skipped the whole translation process

**Comment by wolfgang-ch** [comment]
> with 62pixel it looks bad:

can you send me 2 photo images that I can test it, it seems, that the image data is displayed but somehow wrongly

**Comment by telemaxx** [comment]
i send you an email with some photos and a gps track..

**Comment by wolfgang-ch** [comment]
Fixed, see also commit comment https://github.com/mytourbook/mytourbook/commit/9593b6d23f4e3593f6fcda2412c901ff71a3f899


![image](https://github.com/user-attachments/assets/71b9506d-40f7-4342-87c7-4a551f3c3b13)



Thumbnail images are loaded completely differently with commons-imaging-alpha2 which may fail when AWT is converted into an SWT image in the MT code. It's too complex to debug this when it is not needed.

![image](https://github.com/user-attachments/assets/3d121c6f-a51b-4f54-93f5-0fde9809d205)

**Comment by telemaxx** [comment]
> 
> The mousewheel has AI since 12 years 😎
> 
> The algorithm behind the mousewheel sets the size that always all displayed images are not truncated at the right border !
> 

and i tried "shift" and "ctrl" with the mousewheel, like mentioned in the tooltip. but the AI did what it want 😎

**Comment by wolfgang-ch** [comment]
> and i tried "shift" and "ctrl" with the mousewheel, like mentioned in the tooltip. but the AI did what it want 😎

This is partly correct and partly wrong

When mutiply images are displayed horizontally, then the scrollwheel increments/decrements the horizontally visible number of photos. When only one photo is covering the horizontal space, then the mouswheel works as described in the tooltip

![image](https://github.com/user-attachments/assets/fcc32337-50f0-4528-82cf-681ac7c775c0)
