### ISSUE TITLE
[Bug : Tour Book/Copy Tags] 

### ISSUE THREAD

**Issue by bern6** [mytourbook/mytourbook#1431]
### What happened ?

"Copy Tags" doesn't copy to the clipboard.
Maybe it's also related to my distribution.
OS : debian/gnome
Windows 10 OK

### Version

24.11.1

### System

Linux

**Comment by wolfgang-ch** [comment]
I can confirm this issue. 

After testing on Linux, the clipboard worked differently on Linux than on Windows, this issue is now fixed
