### ISSUE TITLE
[Bug : Tour Editor] Selection of Tour Type first requires Save of other edits

### ISSUE THREAD

**Issue by stvzldn** [mytourbook/mytourbook#1437]
### What happened ?

After install of MTB v24.11.2 the Tour Editor will not let me select a Tour Type, saying that the current tour has been altered and must be saved first (See image below).
If I do the Save then I can set the Tour Type and Save again.  However I can get this error every time by changing the Tour Type once then trying to change the Tour Type again without saving.
Nothing shows in the Error Log.

![MTB save fail](https://github.com/user-attachments/assets/efc95ff9-7e5f-414d-aced-c878756aac52)

### Version

24.11.2

### System

Windows

**Comment by wolfgang-ch** [comment]
I can confirm this issue which was introduced with the last tour type modifications.

A workaround is, to save the tour in the tour editor and then apply the tour type.

**Comment by wolfgang-ch** [comment]
This issue is fixed in the next version
