### ISSUE TITLE
[Bug : Tour Book View] sort average speed SQL Error

### ISSUE THREAD

**Issue by Yscherz** [mytourbook/mytourbook#1441]
### What happened ?

in table view layout, SQL crashes when sorting by speed or pace. This issue exists already for quite some time in my database.
What can I do to fix this.

![SQLcrash](https://github.com/user-attachments/assets/d9ea0d0b-60ad-4c11-b675-c590ea834144)
![SQLcrash2](https://github.com/user-attachments/assets/1d26de66-9140-424b-a684-63cf0563ba66)

### Version

24.11.2

### System

Windows

**Comment by wolfgang-ch** [comment]
Can you attach the log file `C:\Users\YOUR-NAME\mytourbook\.metadata\.log`

**Comment by Yscherz** [comment]
here the log file.

**Comment by wolfgang-ch** [comment]
> here the log file

I don't see an attached log file

**Comment by Yscherz** [comment]
ok probably didnt attach file .... here another try.

**Comment by wolfgang-ch** [comment]
I still cannot see an attached log file, propably you cannot attach it with email

![image](https://github.com/user-attachments/assets/ffebae68-00f5-4ee6-a20c-3e42340bf460)

**Comment by Yscherz** [comment]
here the file ;)
[.log](https://github.com/user-attachments/files/18270297/default.log)

**Comment by wolfgang-ch** [comment]
Can you attach also the other log files because I would like to see the startup of MT. It seems that sql custom functions do not work which are set during the startup.

![image](https://github.com/user-attachments/assets/4e08c7ea-2895-42c2-a0a2-ba9f543fa683)

**Comment by Yscherz** [comment]
here the other log file
[.bak_0.log](https://github.com/user-attachments/files/18270555/default.bak_0.log)

**Comment by wolfgang-ch** [comment]
The attached log file is also a continuation of another log and I discovered that the needed info is not in the log file but when you start MT with a terminal then you can see all debug infos. To start MT with a terminal, use this command line (I run MT always with a terminal)

`"C:\Program Files\MyTourbook\mytourbook.exe" -debug -consolelog`

Use this procedure

* Start MT
* Reduce the number of displayed tours in the **Tour Book** view to 3..5 tours by using this tour filter 
![image](https://github.com/user-attachments/assets/8b5c11c6-7ca7-4745-a05b-1f3f482e753c)

* Stop MT
* Start MT
* Copy and attach the content of the terminal window here

**Comment by Yscherz** [comment]
here the debug infos
[MTdebugInfo.txt](https://github.com/user-attachments/files/18274271/MTdebugInfo.txt)

**Comment by wolfgang-ch** [comment]
The average function is loaded (left side).

![image](https://github.com/user-attachments/assets/ed1df80e-86cf-4508-9cb6-3378737da206)

Can you also sort the view by average speed and attach again the terminal log

**Comment by Yscherz** [comment]
here the debug infos by sort speed 
[MTdebugInfo2.txt](https://github.com/user-attachments/files/18276645/MTdebugInfo2.txt)

**Comment by wolfgang-ch** [comment]
Are you using the embedded or the network server ?

![image](https://github.com/user-attachments/assets/a610f37a-890d-49b5-bd9c-6ef48dac76d4)

**Comment by Yscherz** [comment]
Tour Setting is "Embedded Server", never changed something.

**Comment by wolfgang-ch** [comment]
This issue should now be fixed in 24.11.3, for me it is very strange that it worked in my environment and not in your. The java classpath seems to be the problem, this fix is now setting the java classpath into the sql db.

See also the readme for details https://raw.githubusercontent.com/mytourbook/mytourbook/refs/heads/main/info/release-notes/24.11.3-readme.txt

24.11.3 is only available from an update site https://mytourbook.sourceforge.io/mytourbook/index.php/download-install/software-updates with this url https://mytourbook.github.io/update-sites/24.11.3/

Happy new year !!!

**Comment by wolfgang-ch** [comment]
This sounds good that the fix worked also with your MT installation
