### ISSUE TITLE
[Bug : EasyImport] Set Tour-Type on EasyImport (and right-click in Tour Book)

### ISSUE THREAD

**Issue by Thompson-ongithub** [mytourbook/mytourbook#1444]
### What happened ?

Since 24.11.2 the tour type cannot be set in the import window any more (nor in Tour Book when right-clicking). The only way to set a tour type now is the Tour Editor

It definitively was working in previous 24-versions, quite sure still in 24.11.0
I might try to make a short video...

[Edit]
Strangely it only happens when importing a Tour or when the tour is edited for the first time. After that right-clicking in "Tour Book" seems to work as it should.

### Version

24.11.2

### System

Linux (Ubuntu 24.04.01 LTS)

**Comment by wolfgang-ch** [comment]
I just disabled 24.11.2 update site https://github.com/mytourbook/mytourbook.github.io/commit/93a461b142391459ef8edf4a75b5e09976d065a4 because it can cause, that a tour type could be set into the wrong tour

**Comment by wolfgang-ch** [comment]
Setting a tour type into a tour from the recent tour types, can cause this issue. When a tour type is set from all available tour type then this issue do not happen.

In the tourbook view another tour is selected than in the import view and this selected tour(s) in the tourbook view can get the wrong tour type. But it all depends which view is firstly opened.

https://github.com/user-attachments/assets/8be067d9-500c-4af9-8079-9040e181a52c

**Comment by wolfgang-ch** [comment]
Fixed in 24.11.3

**Comment by wolfgang-ch** [comment]
@Thompson-ongithub 

Can you test it in 24.11.3

24.11.3 is only available from an update site https://mytourbook.sourceforge.io/mytourbook/index.php/download-install/software-updates with this url https://mytourbook.github.io/update-sites/24.11.3/

See also the readme for 24.11.3 details https://raw.githubusercontent.com/mytourbook/mytourbook/refs/heads/main/info/release-notes/24.11.3-readme.txt

**Comment by Thompson-ongithub** [comment]
> @Thompson-ongithub
> 
> Can you test it in 24.11.3
> 

I tried importing a tour and everything seemed to work as it should. 
Thanks for the fix.
