### ISSUE TITLE
[SRTM Download ] Improve UI when setting tour elevation values from SRTM

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#334]
One last thing is that when I click on this button
![image](https://user-images.githubusercontent.com/25235665/116002889-f3560b00-a5b8-11eb-98b2-c32a8bd5bd7d.png)

It only display an error message when it fails. When successfully downloaded SRTM data, nothing is displayed and I find it confusing (did it work ? did it fail? etc....). I think it would be nice to display when successful, just like the tour-reimport, the previous elevation gain/loss and the new one

![image](https://user-images.githubusercontent.com/25235665/116002899-04068100-a5b9-11eb-8177-3edca329a0df.png)

_Originally posted by @FJBDev in https://github.com/wolfgang-ch/mytourbook/issues/309#issuecomment-826359119_

**Comment by wolfgang-ch** [comment]
I forgot to test this action when implementing the SRTM login, now the server account is validated with this https://github.com/wolfgang-ch/mytourbook/commit/add9b0d7b3e4157408fc6b7723060e18b180f1d1 commit

**Comment by FJBDev** [comment]
Title is wrong. It's not **SRMT** but **SRTM**

**Comment by FJBDev** [comment]
New log display

![image](https://user-images.githubusercontent.com/25235665/196011869-a425305d-1017-444b-8a5d-20b891b707db.png)
