### ISSUE TITLE
[2.5 Map] Filter photos

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#397]
2D map has a photo filter to show only specific photos, in this example

* 2D map shows the photo with the storchs because they have a 5 star rating
* 2.5D map shows the photo with the tree and the tiny storchs, the other photo with the larger storchs is behind the visible photo

![image](https://user-images.githubusercontent.com/1283445/133919055-36034ba2-878f-4c6d-be86-29bcddf66f41.png)

**Comment by telemaxx** [comment]
will have a look, when I am back home this weekend.

**Comment by telemaxx** [comment]
When photos are close together, the closest to the "viewer" overlaps the others.
If i turn the map, the other photot becomes closer and is shown.
But a working Filter is much better.
At interesting places, i often make a lot of photos.

When i find some time, i will try. but this "slideouts" are so complicate to me...

**Comment by wolfgang-ch** [comment]
I think the slideout is almost the same as in 2D map but you have to manage all photos and the filtered photos in the 2.5D map which will cause the most work

![image](https://user-images.githubusercontent.com/1283445/134850214-01ed20e0-07ca-481d-b627-dc2a987b1ead.png)

**Comment by wolfgang-ch** [comment]
I just extracted an interface to use the photo filter slideout also in other maps. It is currently in a new branch https://github.com/wolfgang-ch/mytourbook/commit/df82424d833a2bd32f6c94205d60a5eba0006fe9 which I will merge into main when MT 21.9 is released, propably tomorrow

**Comment by wolfgang-ch** [comment]
@telemaxx 
I'm currently implementing this photo feature to filter photos. Firstly I created a slideout which contains all existing photo features

![image](https://user-images.githubusercontent.com/1283445/158119610-5aa1c29e-0f85-49f0-b436-bd7afd2514c2.png)

Now I want to implement the photo filter but about 1/3 of the code in this file is just debug code (green markers on the right side) which I will remove when necessary to better see the code

![image](https://user-images.githubusercontent.com/1283445/158119205-4236f2e4-e23d-4692-8d99-2ba4488caf1e.png)

**Comment by telemaxx** [comment]
no problem. at the beginning I did a lot of investigations to understand how it works. switching the mapprovider was complicate...

**Comment by wolfgang-ch** [comment]
Can you test my current branch https://github.com/mytourbook/mytourbook/tree/ws-improvements if 2.5D map is still working with your configuration.

I also fixed an out of handle exception when too many images where displayed because in your code the images were not disposed

![image](https://user-images.githubusercontent.com/1283445/158150330-70ea5a66-528f-4e10-a453-cbbc9c1805ad.png)

**Comment by telemaxx** [comment]
looks good.
at first it looks not good, but than i recognized the disk in my vm was full.
(I had copied a lot of photos into the vm)
the reaction of eclipse was also not so good, all views where closed. ;-(

![grafik](https://user-images.githubusercontent.com/22706487/158225461-1477c409-ba33-4ebe-a978-9fd3e6f755d2.png)

**Comment by telemaxx** [comment]
can you also have a look why on linux the map provider configuration did not see any file:

![grafik](https://user-images.githubusercontent.com/22706487/158227488-00a287ce-a980-44f4-a76b-cd2342eee40a.png)

Folder looks empty, but is not.
![grafik](https://user-images.githubusercontent.com/22706487/158227620-10db0b87-a4de-40ec-945c-c3a4c394099a.png)

when i click ok *.map is selected:
![grafik](https://user-images.githubusercontent.com/22706487/158227790-92215879-ba4c-4c41-86d0-5365e52fd4bb.png)

When i manually enter the mapfile name, then it is working.
![grafik](https://user-images.githubusercontent.com/22706487/158227947-1fe692a4-3811-4f14-997a-a9c8f816c338.png)

**Comment by telemaxx** [comment]
with the theme file it is the same.

**Comment by telemaxx** [comment]
now i expand my vm disk, speed on ssd is not bad:

![grafik](https://user-images.githubusercontent.com/22706487/158229362-aa07bbcf-7cf0-49c5-bcf2-127c861e52ff.png)

**Comment by FJBDev** [comment]
> Can you test my current branch https://github.com/mytourbook/mytourbook/tree/ws-improvements if 2.5D map is still working with your configuration.
> 

I would have liked to test but I am too worried about that crash, I haven't used the photos feature of MT since I tried to use it the first time ever (as I wanted to import my photos for the first time) and had this [recurring issue](https://github.com/mytourbook/mytourbook/issues/372) :-(

**Comment by wolfgang-ch** [comment]
> > Can you test my current branch https://github.com/mytourbook/mytourbook/tree/ws-improvements if 2.5D map is still working with your configuration.
> 
> I would have liked to test but I am too worried about that crash, I haven't used the photos feature of MT since I tried to use it the first time ever (as I wanted to import all my photos for the first time in MT) and had this [recurring issue](https://github.com/mytourbook/mytourbook/issues/372) :-(

Isn't it time for you now to fix this low level issue as I did with the **vtm-jni64.dll** :-)

I did some Linux test with 2.5D map and photos (or without 2.5D map), some tours could be displayed with photos but sooner or later it always crashed

**Comment by FJBDev** [comment]
> Isn't it time for you now to fix this low level issue as I did with the **vtm-jni64.dll** :-)
> 
When I am done with the weather feature, I can look at that
