### ISSUE TITLE
Tour pauses improvements

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#428]
Pauses in the tour chart
* Stack pauses that they don't overlap
* Filter pauses to hide short pauses

![image](https://user-images.githubusercontent.com/1283445/145678807-7560d9f5-ddfe-4ceb-8ccf-b3f0874768fd.png)

Pauses in the 2D map
* Filter pauses to hide short pauses

![image](https://user-images.githubusercontent.com/1283445/145678904-0a8ce80b-0a1b-435b-b804-16fb5c0eee06.png)

Pauses without filter

![image](https://user-images.githubusercontent.com/1283445/145678950-8ecb449f-b21b-4b38-b2c6-c082bb7451de.png)

**Comment by FJBDev** [comment]
Nice! I am glad to see that people are using the pause features that I always believed was needed in MT (or any tracking software) and that I added now 1 year ago in [20.11.1](https://mytourbook.sourceforge.io/mytourbook/index.php/history/history-2020#v20.11.0) 😄

**Comment by wolfgang-ch** [comment]
The pauses needed these enhancements to be better readable, now they are not overlapped, they are now a maze :-)

![image](https://user-images.githubusercontent.com/1283445/145704004-4f4dad20-89e4-4eda-b50c-e872d2db33e0.png)

**Comment by wolfgang-ch** [comment]
Now you can find all your 007 pauses

![image](https://user-images.githubusercontent.com/1283445/145704213-8fef76c1-2a05-484d-87de-c2022cad5e72.png)

**Comment by wolfgang-ch** [comment]
The initial label alignment was centered to the pause point...

![image](https://user-images.githubusercontent.com/1283445/145765410-bb62d403-415f-4fb7-9c2b-3cdab4749201.png)

...now they are aligned according to their up/down gradient

![image](https://user-images.githubusercontent.com/1283445/145765560-b1bb5bb2-cab9-4842-931e-53116d6c1046.png)
