### ISSUE TITLE
[3D Map] Is not working with Java 17 - MT 21.12

### ISSUE THREAD

**Issue by maclura** [mytourbook/mytourbook#432]
I installed a new copy of Win 11 on a brand new HD, and now I am no longer able to see the 3D map in MT 21.12.
In the past, I upgraded Win 10 to Win 11 on another PC and the 3D map was working very well on MT 21.9.

Here is the error:
"Failed to create the part's controls"
and attached the error details

This error happens with:
OpenJDK16U-jdk_x64_windows_hotspot_16.0.2_7.msi
OpenJDK17U-jdk_x64_windows_hotspot_17.0.1_12.msi
microsoft-jdk-17.0.1.12.1-windows-x64.msi

Instead with
OpenJDK11U-jdk_x64_windows_hotspot_11.0.9_11.msi
microsoft-jdk-11.0.13.8.1-windows-x64.msi

I don't see any error, but this is what I see
IMG_01 : my map conf + 3D map window
IMG_02: this is the max zoom I can reach, after that,
IMG_03: this is what I see with more zoom
IMG_04: randomly zooming and rotating, sometime I see these 2 tiles from Bing imaginary
[MT-3Dmap-error-log_2021-12-27.log](https://github.com/mytourbook/mytourbook/files/7785629/MT-3Dmap-error-log_2021-12-27.log)
![IMG_01](https://user-images.githubusercontent.com/96787883/147588037-6b274c1e-7d8e-4fef-89eb-ed9e26f82161.jpg)
![IMG_02](https://user-images.githubusercontent.com/96787883/147588040-7146a298-65bb-4e44-a285-16a3ddf2a400.jpg)
![IMG_03](https://user-images.githubusercontent.com/96787883/147588043-876b5d3e-0efb-4fb9-8fd2-bfe5a1a30a12.jpg)
![IMG_04](https://user-images.githubusercontent.com/96787883/147588048-d443cf8f-b61f-4a3b-a70e-cd97cba52a2a.jpg)

**Comment by wolfgang-ch** [comment]
Win10 with OpenJDK17U-jdk_x64_windows_hotspot_17.0.1_12.msi

![image](https://user-images.githubusercontent.com/1283445/147631151-e8f56842-a4da-4c92-b587-44dc20edaefd.png)

**Comment by FJBDev** [comment]
Maybe you could open a bug in [JogAmp Bugzilla](https://jogamp.org/bugzilla/)

**Comment by wolfgang-ch** [comment]
You cannot register a new user account in bugzilla, so I created a forum entry

https://forum.jogamp.org/jogl-2-4-and-Java-17-Index-1-out-of-bounds-for-length-1-td4041575.html

**Comment by wolfgang-ch** [comment]
This problem can be fixed by adding these vm parameters

--add-exports java.base/java.lang=ALL-UNNAMED
--add-exports java.desktop/sun.awt=ALL-UNNAMED
--add-exports java.desktop/sun.java2d=ALL-UNNAMED 

https://forum.jogamp.org/jogl-2-4-and-Java-17-Index-1-out-of-bounds-for-length-1-td4041575.html#d1641378052144-283

**Comment by wolfgang-ch** [comment]
Fixed in https://github.com/mytourbook/mytourbook/commit/efa56be2754c12b4a7c94c68d8b62a98936c30cc

It took me several hours with testing to get it fixed in the product, see product and commit comments

**Comment by wolfgang-ch** [comment]
3D map would work only with this fix ` --add-exports java.desktop/sun.awt=ALL-UNNAMED` but the others are now also set
