### ISSUE TITLE
[2D Map] Show tour directions always

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#464]
Normally tour directions are displayed when a tour is hovered or selected (when multiple tours are displayed) however it is difficult to set the tour directions options (size, color) when they are hidden.

Implemented in https://github.com/mytourbook/mytourbook/commit/e1cf935e8c2efb5080f99aa2a8e4640feaf63492

![image](https://user-images.githubusercontent.com/1283445/153701887-10ca86de-3888-4eb2-9731-2864a09c5498.png)

**Comment by FJBDev** [comment]
It seems to me that the direction arrows are not "crisp" but instead pixelized. Also, they have some white in them

![image](https://user-images.githubusercontent.com/25235665/153717389-31463be3-a525-4bf8-9ab0-56c2f0730a53.png)

**Comment by wolfgang-ch** [comment]
>It seems to me that the direction arrows are not "crisp" but instead pixelized. 

The problem is that the map and track tiles are painted on separate images, to optimize performance, and there can be no antialiasing when these layers are painted in the final image.

>Also, they have some white in them

Without the white line, there is no contrast, there are a lot of possibilities to enhance the direction arrow

**Comment by wolfgang-ch** [comment]
This is painting with antialiasing on, which is even more not "crisp" and which is the reason why I introduced this new option

![image](https://user-images.githubusercontent.com/1283445/153740920-6a3633ad-006c-424f-8d6f-fa2ff63b54e9.png)
