### ISSUE TITLE
[2D Map] Zoom options in 2D Map

### ISSUE THREAD

**Issue by witdem** [mytourbook/mytourbook#468]
The 2D map has 3 zoom options: 

- Center to current map center
- Center to mouse position
- Center to tour

Those options are set in various ways and do impact each other. E.g when you have selected the first option (center to current map) the second option does no longer work. 
Maybe it could be implemented with the current center tour action by switching between these 3 options and removing the zoom option from the slideout.

**Comment by wolfgang-ch** [comment]
The map center button can now toggle between three map center options. 
An advantage is now also, that it is immediately visible how it's centered, previously you had to look into the slideout. This option in the slideout is now removed.

![image](https://user-images.githubusercontent.com/1283445/154922961-ad6c0d34-b136-44b0-a86a-7f1e8d16900e.png)

![image](https://user-images.githubusercontent.com/1283445/154922982-393121f4-27ce-432c-9e79-51f61aa97295.png)

![image](https://user-images.githubusercontent.com/1283445/154923007-a714ab90-c22c-4736-a566-8814a142c018.png)
