### ISSUE TITLE
[Tour Chart] Switch between SRTM 1 and SRTM 3 values

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#469]
![tour-chart-options-srtm1+3-2202](https://user-images.githubusercontent.com/1283445/154808173-9932d483-98fa-4637-9e05-4e6f0ca5bdca.png)

**Comment by wolfgang-ch** [comment]
Implemented in https://github.com/mytourbook/mytourbook/commit/cd4536e1e3c2927c862283f9fbca0e837808e451

**Comment by telemaxx** [comment]
Cool !!!
