### ISSUE TITLE
[Weather Retrieval] Tour weather data improvement and new vendor addition (OpenWeatherMap)

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#479]
- Tour Editor View modified and re-arranged to separate the weather data measured from the device vs from the provider/manually entered. A snowfall spinner has been added.

![image](https://user-images.githubusercontent.com/25235665/157542981-fbd9d716-dc2f-4854-a6e3-0819c6385513.png)

- Tour Editor View updated to take into account the case where the wind direction data doesn't exist
![image](https://user-images.githubusercontent.com/25235665/157543093-c3ef9fa5-8604-403b-8010-cab8cadfb096.png)

- New Preference page UI that allows to select the weather provider to use:

![image](https://user-images.githubusercontent.com/25235665/157542673-4c3ba558-4abf-4ad9-8d01-936f16f9a893.png)

- Added the ability to display the weather icon for each tour in the calendar view
![image](https://user-images.githubusercontent.com/25235665/156273639-dd356a04-106f-4f49-81a3-4d8987c75b36.png)

- The tour info tooltip now shows both average temperature from device & manually entered/from provider
![image](https://user-images.githubusercontent.com/25235665/157542545-352b5e28-d480-4916-9ce2-3fb682121d17.png)

- Better detailed weather retrieval logging

![image](https://user-images.githubusercontent.com/25235665/157543515-2f2d1d7e-f678-49af-ae4f-e3cb4e708f2f.png)

- Additional weather provider ([OpenWeatherMap](https://openweathermap.org/)) with no subscription requirement, offering a free [Historical weather 5 days](https://openweathermap.org/price)
![image](https://user-images.githubusercontent.com/25235665/157542794-325a271b-b3ed-4702-80c9-d7f1394e0bf5.png)

- Strava: Added the possibility to send the weather data in the uploaded activity's description

![image](https://user-images.githubusercontent.com/25235665/156870209-956a5271-344e-47a3-aa10-56099662fa03.png)

![image](https://user-images.githubusercontent.com/25235665/156870248-6fdb2636-c1f8-40be-b832-6969272d9f5b.png)

**Comment by FJBDev** [comment]
Tour Editor View modified to separate the weather data from the device vs from the provider/manually entered

![image](https://user-images.githubusercontent.com/25235665/156066457-9163bc79-12ab-4acf-8bbd-c3b70e9a29f9.png)

**Comment by wolfgang-ch** [comment]
@FJBDev After you closed this feature, can I now start the translation process for 22.3 ?

**Comment by FJBDev** [comment]
Yes, you can start the translation for 22.3
