### ISSUE TITLE
MyTourbook Wins an Award from SourceForge

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#480]
Today I received this email

![image](https://user-images.githubusercontent.com/1283445/156315688-5a629dfb-57a9-4758-a4de-c397f5c1c10e.png)

These are the badged we could use now, do you have any preferences ?

![image](https://user-images.githubusercontent.com/1283445/156315899-a84bc39a-de13-4c2f-94d2-b7e0726709bf.png)

**Comment by FJBDev** [comment]
Nice !!🎉🎉🎉👏👏👏

>These are the badged we could use now, do you have any preferences ?

Highlighted are my 2 favorites:
![image](https://user-images.githubusercontent.com/25235665/156378325-03d5259d-f6c7-4896-bc1d-b090d083fc7e.png)

**Comment by wolfgang-ch** [comment]
Your choice was also my favorites which are now put on the github page.

Replaced the SF logo on the MT homepage with just one award image, with the bright theme, this is more suitable.

![image](https://user-images.githubusercontent.com/1283445/156513069-9fffb7e2-3f2b-40c3-a8d8-8431dd728204.png)
