### ISSUE TITLE
[MT Export/Import] Export/import any tour values

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#493]
Because of using the test version 22.3 in my production which had a fatal error when migrating tour data to the new db version, I need a workflow to export my tours which I created with 22.3 and import it into a backup before version 22.3.

Version 22.3 is postponed, until this feature is available.

This featue is already started in https://github.com/mytourbook/mytourbook/commit/e1b60642268bb1b260d4f44312ba921b48903bee

**Comment by wolfgang-ch** [comment]
@FJBDev I will restructure many `<mt: ...>` tags in the gpx export file, so you may need to adjust the unit test file(s)

**Comment by FJBDev** [comment]
I actually wondered for a long time if MT is "symmetric". 
i.e.: If I import a tour from FIT to MT then export to GPX. The clears the db (or delete the imported FIT tour) and imports the exported GPX, will this imported tour be the EXACT same as the imported FIT ? 
I would hope that it is the same but I never took the time to test.

**Comment by wolfgang-ch** [comment]
Because gpx export/import gets more and more complicated when all MT fields are also integrated, I just decided to create the new export file extension `.mt` and it's file has it's own xml tags

**Comment by FJBDev** [comment]
What about `.mtx` since it's mainly based off the `gpx` format ?

**Comment by wolfgang-ch** [comment]
>What about `.mtx` since it's mainly based off the gpx format ?

Which ?

![image](https://user-images.githubusercontent.com/1283445/160060495-627435d9-7932-49ea-8c18-d87ee9fe45b8.png)

**Comment by FJBDev** [comment]
> Which ?

The number 10 😄 

Also, now that JSON is getting very popular and more "modern" compared to XML (which is getting old and verbose), you could inspire yourself from [those files ](https://github.com/mytourbook/mytourbook/blob/main/bundles/net.tourbook.tests/src/test/device/nmea/files/NMEAExample.json) for the MT format ?

**Comment by wolfgang-ch** [comment]
After I restarted this features a second time by using a StAX parser, for now I will stay with it.

>now that JSON is getting very popular and more "modern" 

I learned JSON in 2004 (or earlier) as an easy mechanism to transfer data from the server to the browser and with the JS `eval(...)` method you could convert the JSON text into JS objects

https://web.archive.org/web/20030205013518/http://crockford.com/JSON/js.html

![image](https://user-images.githubusercontent.com/1283445/160227063-1eb80cd6-cefa-48fa-ba26-a0c2b62ec603.png)

In the first version in 2002 we may also be already using JSON but I cannot remember it. There is a video from the 2002 presentation https://www.youtube.com/watch?v=Qs0K8zaVzZ8

![image](https://user-images.githubusercontent.com/1283445/160227656-1ce35936-bed8-4b17-9b6d-d13a77707b3a.png)

**Comment by wolfgang-ch** [comment]
After comparing .mt export files from the db with the fatal migration error and with the .mt import/export files from the fixed db, all .mt  files had the same content except the entity ID's and modified data.

I checked any import/export fields in the code but it could still be possible, that there may be fields which are not exported/imported correctly because I had not tested any possible fields, just the one I'm using in about 10 tour files.

When using this feature to export/import .mt files, it should always be used with care and backups are strongly recommended

**Comment by wolfgang-ch** [comment]
To identify the methods, which were added to get/set entity values for the MT export/import, all method comments have the tag "Used for MT import/export". 

These methods should **not be used** because of possible side effects, there are other methods to set/get entity fields, this was the reason to tag these methods.

**Comment by wolfgang-ch** [comment]
Workflow to fix the possible migration error.

* Install MT 22.3
* Start MT 
* Export all tours, with the format "MyTourbook (.mt)", which were created with the MT22.3 test version and containing the fatal error
* Exit MT 
* Replace "derby-database" folder with the same backup folder
* Start MT 
* Import .mt files and save the tours

**Comment by wolfgang-ch** [comment]
> > Workflow to fix the possible migration error.
> 
> Or what I did (another simple solution that didn't need a new file format) was to restore my backup before the MT22.3 test version and re-import my 10-15 new tours with the original files (.fit).

This is the other option but you loose all your comments, markers and photos which you've created/assigned.

I just updated the info which code should be updated, when the db data structure is modified https://github.com/mytourbook/mytourbook/commit/63aa3465b1e9d7f891013132e543ea4a3c01abdc

**Comment by FJBDev** [comment]
> This is the other option but you loose all your comments, markers and photos which you've created/assigned.
> 
Indeed, but in my case, I had none of those as I had just imported FIT files and not added comments, markers yet

>I actually wondered for a long time if MT is "symmetric".

Is the .mt import/export symmetric then ?

**Comment by wolfgang-ch** [comment]
All discovered issues are now fixed in https://github.com/mytourbook/mytourbook/commit/089ac348f8cd076cbb603c5aaebf294a31d477d0
