### ISSUE TITLE
[Weather] Retrieve current weather 

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#494]
Weather history can be retrieved only after the full hour is reached. 

Could it be possible to retrieve also the current weather?

![image](https://user-images.githubusercontent.com/1283445/159648372-ef12ec9d-e3ec-425b-b28b-8cf18c4cdd76.png)

**Comment by FJBDev** [comment]
It will depend if the provider offers the current weather. I will investigate.

**Comment by FJBDev** [comment]
Do you need that for 22.3 or 22.next ?

**Comment by wolfgang-ch** [comment]
> Do you need that for 22.3 or 22.next ?

22.next

**Comment by wolfgang-ch** [comment]
@FJBDev I'm planning to publish MT 22.6 when Eclipse 2022-6 is published. Is this issue already implemented?

**Comment by FJBDev** [comment]
@wolfgang-ch I have not implemented this issue already. Last time I spent time on it, I was not able to reproduce the issue.

**Comment by wolfgang-ch** [comment]
You are retrieving in the weather history but the next full hour has not yet reached but my request was

>Could it be possible to retrieve also the current weather?

if it is possible to get the current weather?

**Comment by FJBDev** [comment]
> if it is possible to get the current weather and not the history?

I think it could be possible but it will depend on if the weather vendor supports it.
But I'm not sure to understand the use case because when you import tours, aren't they all in "the past" ?
Maybe you can give me an example of scenario.

**Comment by wolfgang-ch** [comment]
It happened to me, that when I ended a tour e.g. at 4:05pm I had to wait until 5 pm to get the weather data. So it's a more comfort issue than a critical.

**Comment by FJBDev** [comment]
Ok, I see. It might be possible but it might have to be in the next release because it involves a different API call depending the vendor.

**Comment by wolfgang-ch** [comment]
Next version is OK, 22.6 should receive only fixes

**Comment by FJBDev** [comment]
>  22.6 should receive only fixes and translations

That's what I thought too.

**Comment by FJBDev** [comment]
Any preference on the weather provider to start with ? (OpenWeatherMap ? WorldWeatherOnline ? WeatherAPI ? )

**Comment by wolfgang-ch** [comment]
> Any preference on the weather provider to start with ? (OpenWeatherMap ? WorldWeatherOnline ? WeatherAPI ? )

It should be a free weather provider with the longest retrieval time -> WeatherAPI

**Comment by wolfgang-ch** [comment]
After 22.8 is ready, should this feature be included?

**Comment by FJBDev** [comment]
> MT 22.8 is now ready, should this feature be included?

It's not ready yet. I have pushed it to **22.next**

**Comment by FJBDev** [comment]
Using the [RealTime API](https://www.weatherapi.com/docs/#apis-realtime) to retrieve the weather data of the current hour

**Comment by FJBDev** [comment]
With WeatherAPI, this case doesn't happen as their API gives the weather data for the entire day (see attached JSON response) for the below request:

`weatherapi?lat=40.263996&lon=-105.58854099999999&dt=2022-10-25&lang=fr`

![image](https://user-images.githubusercontent.com/25235665/197896636-86848149-61bd-4f86-89d3-1fc655814137.png)

Response:

```
   "time_epoch": 1666677600,
                        "time": "2022-10-25 00:00",
```

to 

```
  "time_epoch": 1666760400,
                        "time": "2022-10-25 23:00",
```

[WeatherAPIResponse.txt](https://github.com/mytourbook/mytourbook/files/9864512/WeatherAPIResponse.txt)
