### ISSUE TITLE
[Temperature in Views] Only device temperature values are displayed in Views

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#495]
Manual created tours before 22.3

![image](https://user-images.githubusercontent.com/1283445/159674109-da89d8fd-0bdd-40ad-8950-dfc9bf191dcf.png)

The same tours with 22.3

![image](https://user-images.githubusercontent.com/1283445/159674254-724bc667-587c-4ba9-8c72-e781b56ac93b.png)

There could be these options to solve it:
* Depending on available temperature values, show manual/provider or device values
* Create temperature columns for manual/provider and device values
* User can decide which values should be displayed

**Comment by FJBDev** [comment]
I am leaning towards this

- User can decide which values should be displayed

Just like the pace/speed preference

![image](https://user-images.githubusercontent.com/25235665/159725783-aae7834c-3518-4654-bb3a-cc5f367059dd.png)

**Comment by wolfgang-ch** [comment]
I think combining both would be helpful

* First: the user can decide which values should be displayed, but when only the other value is available, then 
* Second: Show the other temperature values

**Comment by FJBDev** [comment]
Ok, so more of an order in which temperature is displayed.

**Comment by FJBDev** [comment]
@wolfgang-ch 
Any idea where you think this option would be best to put in the Preferences page ?

The best place I have found so far would be in the `View` preference page in a new UI group called `Temperature Values`

Thoughts ?

![image](https://user-images.githubusercontent.com/25235665/164811073-8c247322-45c7-4d05-ab33-d17cea2f4fb5.png)

**Comment by wolfgang-ch** [comment]
> @wolfgang-ch Any idea where you think this option would be best to put in the Preferences page ?
> 
> The best place I have found so far would be in the `View` preference page in a new UI group called `Temperature Values`
> 
> Thoughts ?
> 

I couldn't find a better place 👍

**Comment by FJBDev** [comment]
Actually, as I am working on this feature at the moment, I am wondering if it wouldn't be better to add instead the temperature in each contextual menu for `Device` (device values) and in the `Weather` menu (external values), that way, the user can choose in the same menu as other values instead of adding another preference, thoughts ?

![image](https://user-images.githubusercontent.com/25235665/166747301-a03dd23d-2e34-4681-ab9c-f7d88638299e.png)

**Comment by wolfgang-ch** [comment]
Good idea, instead of the pref page, the user can decide in the selected columns which temperature should be displayed but it should also be possible, that a combined temperature column is available as described above https://github.com/mytourbook/mytourbook/issues/495#issuecomment-1077225014-permalink

**Comment by FJBDev** [comment]
> Good idea, instead of the pref page, the user can decide in the selected columns which temperature should be displayed but it should also be possible, that a combined temperature column is available as described above [#495 (comment)](https://github.com/mytourbook/mytourbook/issues/495#issuecomment-1077225014-permalink)

Ok, so you mean an additional contextual menu named "Combined Temperature" ? Should I put it in the Tour contextual menu?

**Comment by wolfgang-ch** [comment]
I think the `Device/Temperature ...` actions should be moved to the `Weather` submenu, until now the temperature value was mostly from the device. 

The `Combined Temperature...` actions should also be located in the `Weater` submenu
