### ISSUE TITLE
[Weather Log] Save log from the weather provider in the tour weather field

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#498]
It could be helpful when this weather log can be saved in the weather text field. 
In the weather pref page this feature can be enabled/disabled.

![image](https://user-images.githubusercontent.com/1283445/160758727-83de27a2-3af2-4ae1-8d6e-6ac64eaf618f.png)

![image](https://user-images.githubusercontent.com/1283445/160759297-b1e3adbf-3e37-4ed1-8838-7e38457bc5cb.png)

**Comment by FJBDev** [comment]
It's funny because I actually thought about the same thing several days ago but was wondering if users would like it.
I can do that in 22.next if you want

**Comment by wolfgang-ch** [comment]
> I can do that in 22.next if you want

"Ich höre mich nicht nein sagen" -> "I can't hear myself saying no" (Yes)

https://www.google.com/search?client=firefox-b-d&q=ich+h%C3%B6re+mich+nicht+nein+sagen

**Comment by FJBDev** [comment]
Would it be useful to also save the name of the provider when the user has checked to save this weather log in the weather text field ?

**Comment by wolfgang-ch** [comment]
> Would it be useful to also save the name of the provider when the user has checked to save this weather log in the weather text field ?

This should be optional, when you always have the same weather provider, you may not want it

**Comment by FJBDev** [comment]
:warning: WARNING  :warning: :

For long tours, it's possible that the weather log exceeds what the weather description field can hold.
In this case, it will be truncated:

![image](https://user-images.githubusercontent.com/25235665/168393263-1452bf64-0274-4637-b2e4-36754150fe38.png)

**Comment by wolfgang-ch** [comment]
> For long tours, it's possible that the weather log exceeds what the weather description field can hold.
> In this case, it will be truncated to meet the maximum 1000 characters allowed:

Why not increase the field size to 32'000 like with `net.tourbook.data.TourData.DB_LENGTH_TOUR_DESCRIPTION_V10`

**Comment by FJBDev** [comment]
> > For long tours, it's possible that the weather log exceeds what the weather description field can hold.
> > In this case, it will be truncated to meet the maximum 1000 characters allowed:
> 
> Why not increase the field size to 32'000 like with `net.tourbook.data.TourData.DB_LENGTH_TOUR_DESCRIPTION_V10`

Yes, I can do that.
