### ISSUE TITLE
[JUnit Tests] 22.3 issues

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#499]
I fixed one issue https://github.com/mytourbook/mytourbook/commit/09848f80238271f34fd92da8579240939abe4f17 but there are other issues.

@FJBDev Can you fix these issues?

![image](https://user-images.githubusercontent.com/1283445/160784900-8deef12f-d696-455f-ab94-bef350b1ffe6.png)

**Comment by FJBDev** [comment]
Yes, I will look at fixing those issues.

**Comment by FJBDev** [comment]
What confuses me is why the [build didn't fail yesterday ](https://github.com/mytourbook/mytourbook/actions/runs/2057068504)since your commit that created those JUnit failures was from [yesterday](https://github.com/mytourbook/mytourbook/commit/0dab5350ffcb84f9cb4587ae20e652cb99e2d2a1)

**Comment by wolfgang-ch** [comment]
With your PR https://github.com/mytourbook/mytourbook/pull/500, now there are less errors/failures

![image](https://user-images.githubusercontent.com/1283445/160983664-8ad28e98-3c81-4dd3-b52f-f1b86a3bb46a.png)

[net.tourbook.tests 20220331-073129.xml.zip](https://github.com/mytourbook/mytourbook/files/8386280/net.tourbook.tests.20220331-073129.xml.zip)

**Comment by wolfgang-ch** [comment]
> What confuses me is why the [build didn't fail yesterday ](https://github.com/mytourbook/mytourbook/actions/runs/2057068504)since your commit that created those JUnit failures was from [yesterday](https://github.com/mytourbook/mytourbook/commit/0dab5350ffcb84f9cb4587ae20e652cb99e2d2a1)

I also don't have a short answer for this question, for a longer answer this has to be investigated but is this necessary?

**Comment by FJBDev** [comment]
> I also don't have a short answer for this question, for a longer answer this has to be investigated but is this necessary?

No, this is not necessary, it was more an observation I noted and I thought i would share it.
