### ISSUE TITLE
[Tour Chart] Show "Recorded Time" in value point tooltip

### ISSUE THREAD

**Issue by GurVJ** [mytourbook/mytourbook#502]
In the charts windows, the duration time indicated in the Info Tool Tip is the Elapsed time.
The feature request is that when the X-axis is selected to distance (km icon) then the duration time showed in the Info Tool Tip should be the recorded time (or at least the user should have the choice), so that there will be no longer "time jump" when a pause occured.

The same behaviour with the Map view Info Tool Tip would be also great.

ThanX !

**Comment by wolfgang-ch** [comment]
>The feature request is that when the X-axis is selected to distance (km icon) ... that there will be no longer "time jump" when a pause occured.

I don't see time jumps when the x-axis is showing distances, they occure when the x-axis is displaying time

**x-Axis: Distance**

![image](https://user-images.githubusercontent.com/1283445/161389530-6af9e6db-860a-4869-97f3-36b141460a2e.png)

**x-Axis: Time**

![image](https://user-images.githubusercontent.com/1283445/161389686-12fb7621-8f3c-4537-a0d3-702cdae8a16c.png)

**Comment by GurVJ** [comment]
I am talking about "Time Jumps" into the Info ToolTip window :
![image](https://user-images.githubusercontent.com/64196685/161391123-154a9a1c-2cdc-4241-8a69-a9b3a6e3c6ae.png)

**Comment by wolfgang-ch** [comment]
> I am talking about "Time Jumps" into the Info ToolTip window :

Now I understood it, an image is easier to understand than thousand words

**Comment by wolfgang-ch** [comment]
This feature will be available in the next version

![image](https://user-images.githubusercontent.com/1283445/227736058-ae9f3daf-1604-4798-b9c4-80c650b6dec5.png)

![image](https://user-images.githubusercontent.com/1283445/227736171-47597d76-17bf-4703-a8de-57fd5170ee9f.png)

**Comment by GurVJ** [comment]
Thank you @wolfgang-ch, but would it be also possible to have the choice of the "Recorded time" value ?

**Comment by wolfgang-ch** [comment]
Do I understand it correctly, that you want, that `Recorded time` should be displayed in **any locations within MT**, with or without break time which should be defined, e.g. in the pref paged?

**Comment by GurVJ** [comment]
You understand correctly.

For me the Moving Time is a useless indicator or at least a secondary one. Indeed, it happens frequently that I am not moving during my activity : it could be during recovery times, during time while I am looking for my way, during "refueling" times, etc. But these times are fully part of my activity (my effort) and if I do not want them to be part of my activity then I just stop the watch. That is why the recorded time is the most important indicator for me (and it is the default one used in all sport apps).

**Comment by wolfgang-ch** [comment]
How should "your time" be computed ?

What is missing in the statistic times ?

![image](https://user-images.githubusercontent.com/1283445/229265966-3b60b8ea-77be-4fc0-afba-553a4abdf8fc.png)

**Comment by GurVJ** [comment]
Nothing is missing in the statistic times : "my time" is "Recorded time".
So i just would like to have this time displayed in the tool tip (and idealy to have it also as an x-axis to graphics).

Recorded time is : Elapsed time - Pause Time
Or it also may be defined as the sum of all time intervals of the recorded points between Start and Stop events.

**Comment by GurVJ** [comment]
I just found an article from Garmin developer website, which gives definitions of all times used. The graph at the bottom of the article is a good summary ("Timer duration" is our "Recorded time")

[https://developer.garmin.com/fit/cookbook/durations/](url)

**Comment by wolfgang-ch** [comment]
The above link is not working, fixed link [https://developer.garmin.com/fit/cookbook/durations/](https://developer.garmin.com/fit/cookbook/durations/)

**Comment by wolfgang-ch** [comment]
> So i just would like to have this time displayed in the tool tip 

In which tooltip

In the value point tooltip I added the [moving time](https://github.com/mytourbook/mytourbook/issues/502#issuecomment-1483897001) but now you want the recorded time, I'm a bit confused

**Comment by GurVJ** [comment]
I am also confused because the initial request was to add the Recorded Time 

> The feature request is that when the X-axis is selected to distance (km icon) then the duration time showed in the Info Tool Tip should be the **recorded time** (or at least the user should have the choice)
> 

Then you added the Moving Time. Fine, but it does not answer the initial request, that's all.

Using the Moving Time is not reliable because it is a computed time so it depends on user parameters and because of GPS precision (even when the device is not moving, the position changes).

Let's have a look a the following case, with specific Moving Time parameters :
![image](https://user-images.githubusercontent.com/64196685/229302197-4a6dffdf-7a5a-4375-969d-ee8d79128dd7.png)

![image](https://user-images.githubusercontent.com/64196685/229302204-703de5bb-27a9-4f98-9ffc-b661073e0d04.png)

I moved more than 100 meters but the Moving Time did not change.

The only way to have reliable datas is to use Recorded Time (in addition to Elapsed Time).
But I can understand that it is not so easy to get (I think there is a link with issue [#1009])(https://github.com/mytourbook/mytourbook/issues/1009)
 
Am I clearer ? I really try ;-)

**Comment by GurVJ** [comment]
After studying the data points given in the Tour Editor, the computed "formula" to get the Recorded Time for each point could be :
Elapsed Time for the active point (Temps) - [sum of (Time interval value (||sec) when Pause (P) is True)  for all points before the active one]

See the following example (no other Pause before point #826) 
![image](https://user-images.githubusercontent.com/64196685/229305425-ea8dec68-611a-4ee0-bcdf-b50feb1deec0.png)

**Comment by wolfgang-ch** [comment]
Can you attach this tour ?

**Comment by GurVJ** [comment]
[D41A0557.zip](https://github.com/mytourbook/mytourbook/files/11132814/D41A0557.zip)

**Comment by wolfgang-ch** [comment]
I've total different values for moving time and speed.

Is your speed value of about 23 km/h realistic when you are running?

![image](https://user-images.githubusercontent.com/1283445/229419993-78c8f620-61ff-4cf8-8229-ef60a66f1486.png)

![image](https://user-images.githubusercontent.com/1283445/229420007-96624f91-b3d2-4f0c-9811-648f169b0158.png)

**Comment by wolfgang-ch** [comment]
> After studying the data points given in the Tour Editor, the computed "formula" to get the Recorded Time for each point could be :
> Elapsed Time for the active point (Temps) - [sum of (Time interval value (||sec) when Pause (P) is True) for all points before the active one]

This is exactly the formula, how the recorded time is computed

https://github.com/mytourbook/mytourbook/blob/51b27ce7f005da272455fc1af8fdba3c5c4bad65/bundles/net.tourbook.device.garmin.fit/src/net/tourbook/device/garmin/fit/FitData.java#L220

**Comment by wolfgang-ch** [comment]
I'll add the recorded time value to the value point tooltip

**Comment by GurVJ** [comment]
> I've total different values for moving time and speed.
>
Yes, no suprise because we haven't got the same parameters for moving time in this example (I chose extrem values to illustrate that Moving Value is not reliable).

> Is your speed value of about 23 km/h realistic when you are running?
>
Of course not :-)
That's why in my opinion, the average value shouldn't be computed with Moving Time or at least the user should have the choice with Recorded Time. And honestly I thought it was already the case with this :
![image](https://user-images.githubusercontent.com/64196685/229554176-0e7ff5bb-8049-43a7-a498-343a3e45cd95.png)

> I'll add the recorded time value to the value point tooltip
>
Thank you !

**Comment by wolfgang-ch** [comment]
The first pause `0:06` is an auto pause which is summarized in the recorded time

![image](https://user-images.githubusercontent.com/1283445/229724964-7438fbb8-8b5e-472d-a513-80bc938ff682.png)

**Comment by GurVJ** [comment]
What is the difference between the 0:06 pause and the 0:21 pause ?  In both cases the timer is stopped, isn't it ?

**Comment by wolfgang-ch** [comment]
> What is the difference between the 0:06 pause and the 0:21 pause ? In both cases the timer is stopped, isn't it ?

0:06 is an auto pause which is triggered by the device, e.g. when you are not moving below a specific speed, e.g. 2 km/h
0:21 is manually triggered by the user, when you press the pause/resume button on the device

**Comment by GurVJ** [comment]
OK, that's what I thought. So why do you include the 0:06 auto pause into the recorded time ? The stop button triggered by the user or by the device should be considered as indentical : the timer is no more running so it is not Recorded Time.

**Comment by GurVJ** [comment]
Tell me if I am wrong but in your example there is no "Standing Still" state (the altitude graph would be continouaus). There are only 2 "timer paused" states (one auto pause and one user pause), so the Recorded Time should be equal to your Moving Time.

**Comment by GurVJ** [comment]
Tomorrow I will try to record a tour with all situations to illlustrate my words.

**Comment by wolfgang-ch** [comment]
From https://developer.garmin.com/fit/cookbook/durations/

"Timer duration accounts for pauses during the recording of the activity due to a **manual or auto-pause** of the timer, and is always less than or equal to the elapsed duration. Timer duration only accumulates while the device timer is running."

The question is if the MT `Recorded Time` respectively Garmin `Timer Duration` should contain auto-pauses from the device or not ?

**Comment by GurVJ** [comment]
> The question is if the MT `Recorded Time` respectively Garmin `Timer Duration` should contain auto-pauses from the device or not ?

You're right and to me the sentence "Timer duration only accumulates while the device timer is running." means that manual and auto-pause should be considered the same way : not part of Recorded Time (Timer duration).


> Tomorrow I will try to record a tour with all situations to illlustrate my words.
Sorry I won't be able to do so because I hurt myself during my trainning session yesterday evening.

**Comment by FJBDev** [comment]
> You're right and to me the sentence "Timer duration only accumulates while the device timer is running." means that manual and auto-pause should be considered the same way : not part of Recorded Time (Timer duration).
> 

And this is exactly how I implemented the recorded time in [MT 20.11.0](https://mytourbook.sourceforge.io/mytourbook/index.php/history/history-2020#v20.11.0). Whether the pause is automatically triggered or manually triggered, it is substracted from the elapsed time to compute the recorded time.

You can see my original pull request details and explanation [here](https://github.com/mytourbook/mytourbook/pull/222)
