### ISSUE TITLE
[MTB 22.3.0] Duplicated view, one buggy

### ISSUE THREAD

**Issue by mff73** [mytourbook/mytourbook#511]
22.3.0 just installed and i found a duplicated view in the all view list : Données de Parcours (in french)
one is working if selected, the other is buggy
See screenshots
![MTB22 3 double view in list](https://user-images.githubusercontent.com/50132146/162606262-2111ebc5-2e29-4ef2-960b-b3f644e31511.png)

![MTB22 3 double view in list error view1](https://user-images.githubusercontent.com/50132146/162606260-23dbea96-a989-4eca-8f0f-485b8028bba7.png)

![MTB22 3 double view in list no error view2](https://user-images.githubusercontent.com/50132146/162606263-d27be740-e2dd-4f01-b212-c9c6de8f1110.png)

**Comment by telemaxx** [comment]
looks like a copy/paste error...

**Comment by FJBDev** [comment]
I had the same problem. Not sure when this issue appeared (22.3 ?). My hunch is that it has to do with the `workbench.xmi` but not sure...

**Comment by wolfgang-ch** [comment]
I've renamed this view internally from `TourData_View` -> `TourDataView` but this is not recognized in already installed MT apps.

There are 2 options, that the view name is not duplicated:

* Delete file `C:\Users\<YOUR-NAME>\mytourbook\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi` when MT is closed 
-> all your perspectives and UI layout will be reset to default 
-> not such a good idea
* Delete the whole section which you see in the screenshot, some values could be different but not the red marked
![image](https://user-images.githubusercontent.com/1283445/162698703-03a70222-5fdb-4be3-a70d-da088bb43775.png) in the file `C:\Users\<YOUR-NAME>\mytourbook\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi` when MT is closed 
-> I just tested it and it ran smoothly
When you reopen MT and the old view is still available in a perspective, just close this view, the duplicated entries should still be gone


**! ! ! Before you manipulate `C:\Users\<YOUR-NAME>\mytourbook\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi` make a backup of it. ! ! !**

**Comment by mff73** [comment]
@wolfgang-ch 
I did that, and it works, thanks.

> * Delete the whole section which you see in the screenshot, some values could be different but not the red marked
>   ![image](https://user-images.githubusercontent.com/1283445/162698703-03a70222-5fdb-4be3-a70d-da088bb43775.png) in the file `C:\Users\<YOUR-NAME>\mytourbook\.metadata\.plugins\org.eclipse.e4.workbench\workbench.xmi` when MT is closed

**Comment by FJBDev** [comment]
I also see what seems to be duplicate too, should the `TourData_View` be deleted too ??

```
 <children xsi:type="advanced:Placeholder" xmi:id="_kBg8EK1IEeuyqtgcQyR1oA" elementId="net.tourbook.ui.views.TourData_View" toBeRendered="false" ref="_SjyPKJCdEeuf-4SFt8Xi7g" closeable="true">
                    <tags>View</tags>
                    <tags>categoryTag:2. Propri&#xe9;t&#xe9;s du parcours</tags>
                  </children>
```

```
                  <children xsi:type="advanced:Placeholder" xmi:id="_hibPQLktEeytsaHKRtH8pg" elementId="net.tourbook.ui.views.TourDataView" ref="_LugA0LZ4EeyDHNjmELeWsw" closeable="true">
                    <tags>View</tags>
                    <tags>categoryTag:2. Propri&#xe9;t&#xe9;s du parcours</tags>
                  </children>
```

**Comment by FJBDev** [comment]
And I have the same duplication issue with `TourInfoView` & `TourInfo_View`.
Which one to keep ?

Now I need to look better at my `Workbench.xmi` because i think i have more duplication issues.....

```
<descriptors xmi:id="_Sjy2dpCdEeuf-4SFt8Xi7g" elementId="net.tourbook.ui.views.TourInfo_View" label="Informations du parcours" iconURI="platform:/plugin/net.tourbook/icons/tour-info.png" tooltip="" category="2. Propri&#xe9;t&#xe9;s du parcours" closeable="true" contributionURI="bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView">
    <persistedState key="originalCompatibilityViewClass" value="net.tourbook.ui.views.TourInfo_View"/>
    <persistedState key="originalCompatibilityViewBundle" value="net.tourbook"/>
    <tags>View</tags>
    <tags>categoryTag:2. Propri&#xe9;t&#xe9;s du parcours</tags>
  </descriptors>
```

```
 <descriptors xmi:id="_Sjy2VpCdEeuf-4SFt8Xi7g" elementId="net.tourbook.ui.views.TourInfoView" label="Informations du parcours" iconURI="platform:/plugin/net.tourbook/icons/tour-info.png" tooltip="" category="2. Propri&#xe9;t&#xe9;s du parcours" closeable="true" contributionURI="bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView">
    <persistedState key="originalCompatibilityViewClass" value="net.tourbook.ui.views.TourInfoView"/>
    <persistedState key="originalCompatibilityViewBundle" value="net.tourbook"/>
    <tags>View</tags>
    <tags>categoryTag:2. Tour Properties</tags>
    <tags>categoryTag:2. Propri&#xe9;t&#xe9;s du parcours</tags>
  </descriptors>

```

**Comment by wolfgang-ch** [comment]
> I also see what seems to be duplicate too, should the `TourData_View` be deleted too ??
> 
> ```
>  <children xsi:type="advanced:Placeholder" xmi:id="_kBg8EK1IEeuyqtgcQyR1oA" elementId="net.tourbook.ui.views.TourData_View" toBeRendered="false" ref="_SjyPKJCdEeuf-4SFt8Xi7g" closeable="true">
>                     <tags>View</tags>
>                     <tags>categoryTag:2. Propri&#xe9;t&#xe9;s du parcours</tags>
>                   </children>
> ```
> 
> ```
>                   <children xsi:type="advanced:Placeholder" xmi:id="_hibPQLktEeytsaHKRtH8pg" elementId="net.tourbook.ui.views.TourDataView" ref="_LugA0LZ4EeyDHNjmELeWsw" closeable="true">
>                     <tags>View</tags>
>                     <tags>categoryTag:2. Propri&#xe9;t&#xe9;s du parcours</tags>
>                   </children>
> ```

There are other `TourData_View` in this file but after I removed one of them, the workspace was corrupted and the default layout was displayed 

-> don't waste time and ignore duplicates when they are not somewhere visible

**Comment by FJBDev** [comment]
After several tests, I found that I needed to delete this one:
`net.tourbook.ui.views.TourInfoView`
