### ISSUE TITLE
V22.3 - Manual Temperature not showing on Tour Book

### ISSUE THREAD

**Issue by GurVJ** [mytourbook/mytourbook#513]
Hello,

with the new V22.3 release, all the manually added average Temperatures within the Tour Editor, are no more displayed in the corresponding Column of the Tourbook view.
![image](https://user-images.githubusercontent.com/64196685/162899247-290191fc-9021-4f46-8fe6-a4ff0b9358b3.png)

**Comment by wolfgang-ch** [comment]
This is a bug https://github.com/mytourbook/mytourbook/issues/495
