### ISSUE TITLE
[FeatureFromSF] #123 File Import Enhancement / Support Movescount GPX Files

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#781]
Hello MyTourbook team,

I already asked in ticket #123 to enhance the gpx import in a way to be able to import gpx files which were created/exported via Movescount/Suunto. 

Yes, with the last fix of #123 you can import these files again but the length of the imported tours are still wrong - as explained in ticket #123.

Could you fix this as well, please? 

Sample files can be found in ticket #123.

Thanks in advance.

Greetings

Marco

Reported by: veryfirstuser

Original Ticket: [mytourbook/feature-requests/129](https://sourceforge.net/p/mytourbook/feature-requests/129)

**Comment by FJBDev** [comment]
Closed as both files import fine and their length is correct `23.3.2`
