### ISSUE TITLE
[FeatureFromSF] Nautical measurement system

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#795]
Add nautical measurement system as an additional system measurement.

Nautical is only for distances, so altitude and temperature must be editable to have imperial or metrical for these values

Reported by: wolfgang-ch

Original Ticket: [mytourbook/feature-requests/143](https://sourceforge.net/p/mytourbook/feature-requests/143)

**Comment by FJBDev** [comment]
Implemented in [20.12.0](https://mytourbook.sourceforge.io/mytourbook/index.php/history/history-2020#v20.12.0)
