### ISSUE TITLE
[FeatureFromSF] Automatic import from Garmin Connect?

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#803]
Again... no idea if this is a big deal or a little one. No idea if it's a no-charge thing with the Garmin API or if there's a prohibitive fee. But it's pretty cool that once I let my watch sync up, ST3.mobi has the run in there in seconds. No need to import anything. 

Personal preference is to have a button I push in MT that grabs any Garmin Connect activities that haven't been brought down yet. But automatic works well with ST3, so... whatever. 

Reported by: gregoryx

Original Ticket: [mytourbook/feature-requests/151](https://sourceforge.net/p/mytourbook/feature-requests/151)

**Comment by FJBDev** [comment]
Closing as `not-planned` since the [Garmin API](https://developerportal.garmin.com) doesn't support it at the moment

**Comment by FJBDev** [comment]
FYI, I have started using [this tool](https://github.com/pe-st/garmin-connect-export) to automatically retrieve my activities from my Edge 530 and it has been working fine
