### ISSUE TITLE
[FeatureFromSF] Correct Import calories from tcx-files

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#812]
The import of the calorie values from a tcx file is read in too low by a factor of 1000. This is likely due to the fact that the calorie count is cal and not kcal. Could this be adjusted? Either in the options or fix.

Reported by: lamont

Original Ticket: [mytourbook/feature-requests/160](https://sourceforge.net/p/mytourbook/feature-requests/160)

**Comment by FJBDev** [comment]
Fixed in [23.3.0](https://github.com/mytourbook/mytourbook/pull/995)
