### ISSUE TITLE
[Easy Import] Set elevation totals from SRTM data

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#824]
Is it possible to add a feature to adjust the altitude automatically (elevation total), for devices without atmospheric pressure, for example Garmin forerunner, in the easy import dialog.

Reported by: berny

Original Ticket: [mytourbook/feature-requests/172](https://sourceforge.net/p/mytourbook/feature-requests/172)

**Comment by witdem** [comment]
I would like to have SRTM elevation correction applied during easy import. Now I have to do it manually.

**Comment by wolfgang-ch** [comment]
It is a duplicate https://github.com/mytourbook/mytourbook/issues/945

**Comment by wolfgang-ch** [comment]
This feature will be available in the next version, in the easy import tool...

![image](https://user-images.githubusercontent.com/1283445/227700388-22514a71-2827-45a7-81ac-d26849c2ba8e.png)

...and in the tour editor

![image](https://user-images.githubusercontent.com/1283445/227700423-ad8b52ec-0681-445f-ad84-182e2875ef17.png)

![image](https://user-images.githubusercontent.com/1283445/227700430-65277e74-f8fd-431f-bd8c-6f87a78e2119.png)
