### ISSUE TITLE
[Adjust Altitude] Adjust with SRTM for second portion of Tour

### ISSUE THREAD

**Issue by mff73** [mytourbook/mytourbook#865]
Feature request (except if i don't find how to do it now in 22.3.1)
SRTM adjust altitude is possible for whole tour or user definied first portion of tour, but not for any user defined second portion of tour (without touching the first portion). 
![image](https://user-images.githubusercontent.com/50132146/169778900-a84877ba-4760-4910-9d73-84a2d889e034.png)

**Comment by mff73** [comment]
Yes Wolgang, you are right, we can set addionnal points, but in some cases, it is not perfect and quite long.
in my previous screenshot, i would like to adjust mostly only the second half of the tour.
It is very easy for first half, very long for second half
And with such option (to be able to select right portion) we could even decide to replace altitude with SRTM for just end of Tour (not only beginning : left part).

**Comment by wolfgang-ch** [comment]
In the next MT version 22.6 you can now also move the left slider, until now it was fixed to 0 (first data point). It sounds easy but it was not to implement it, first I had to understand the x-year old code but finally it worked :-)

Now you can modify the elevation with splines with the minimum of just a few data points

![image](https://user-images.githubusercontent.com/1283445/171881864-571a6a4d-ff40-4b57-acc3-142a6e6455d3.png)

Example from zoomed out to zooming in

![image](https://user-images.githubusercontent.com/1283445/171881882-4284258c-911b-4221-930a-c6fd746190b5.png)

![image](https://user-images.githubusercontent.com/1283445/171881893-0abeb095-c52a-4a2d-aac9-6f9f58f12764.png)

![image](https://user-images.githubusercontent.com/1283445/171881907-d3552e2e-0dd4-406a-8746-7521ec7185a5.png)

**Comment by mff73** [comment]
I have no words, except : wow, and thanks. Eager to test. 👍👍

**Comment by wolfgang-ch** [comment]
To which e-mail address should I send to you the link for downloading the MT 22.6 test version, I will not publish the link here

**Comment by mff73** [comment]
> To which e-mail address should I send to you the link for downloading the MT 22.6 test version, I will not publish the link here

mff1_73@yahoo.fr
Thanks a lot.

**Comment by mff73** [comment]
Hi Wolfang,
Sorry for late answer.
Well received the link, installed, tested, and it works exactly as expected.

And thanks to that, it came to me a new bunch of possible enhancements.
MTB can now approach with SRTM between any intervals : so cool. But, what about the other adjustments options beging available in the same selected interval : 
![image](https://user-images.githubusercontent.com/50132146/173517387-985ea41d-69d6-49d0-8100-706c947ed6cd.png)
 
does it become even more complicated ?

**Comment by wolfgang-ch** [comment]
>But, what about the other adjustments options beging available in the same selected interval 
>does it become even more complicated ?

Fore sure, currently these algorithms work from start until the end and do not yet recognize the slider position(s)
