### ISSUE TITLE
[2.5D Map] Set sun position for building shadow

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#866]
The sun object `org.oscim.renderer.light.Sun` has the possibility to set it's position by time and the light color is accordingly adjusted

Just after sunrise

![image](https://user-images.githubusercontent.com/1283445/169786066-433719f1-f9be-4ff2-ab4a-0e3536d8589c.png)

Later after sunrise

![image](https://user-images.githubusercontent.com/1283445/169786151-e3b142c2-dfe6-45a1-b223-9d1ac3b27727.png)

Noon

![image](https://user-images.githubusercontent.com/1283445/169786203-503dfd50-20de-4e78-bc74-bcdbac94b4ae.png)

Before sunset

![image](https://user-images.githubusercontent.com/1283445/169786241-9cec4203-34fa-460b-a36c-edd484db7b77.png)

**Comment by wolfgang-ch** [comment]
Improved the UI to select the sun time in the slideout

Acropolis after sunrise

![image](https://user-images.githubusercontent.com/1283445/170661106-bbf27f17-a057-421b-b4ae-01027c6e56e5.png)

Acropolis before sunset

![image](https://user-images.githubusercontent.com/1283445/170661136-4dae246c-ed74-413c-ab95-499c7f824de2.png)

**Comment by wolfgang-ch** [comment]
These were my bookmarks to test the buildings

![image](https://user-images.githubusercontent.com/1283445/170662713-9f31ca39-c333-4d9c-8b6a-51c0e5c67e33.png)

**Comment by telemaxx** [comment]
I like the new UI for the map layer

![grafik](https://user-images.githubusercontent.com/22706487/170884611-774d8358-999e-445f-9e96-3c1429077b22.png)

and you fixed also the map provider menue. now i can select a map/theme-file. in the past i could only select the folder.

![grafik](https://user-images.githubusercontent.com/22706487/170884727-bf153005-66ae-43bc-b945-359fc2fc2f5a.png)

**Comment by wolfgang-ch** [comment]
> and you fixed also the map provider menue. now i can select a map/theme-file. in the past i could only select the folder.

It was this fix https://github.com/mytourbook/mytourbook/commit/9f653db6926c90795ac88986b04d2ae101424a22

**Comment by wolfgang-ch** [comment]
After seeing your screenshot...

![image](https://user-images.githubusercontent.com/1283445/170929830-833fb19c-f062-480a-99a7-1f95ba4b0c3b.png)

...I was shocked by myself at the alignment of some controls which I provided.

Now I fine-tuned it, I do this mostly by using temporarily background colors to see the control borders.

![image](https://user-images.githubusercontent.com/1283445/170930830-92b0f518-53ee-4b99-a62d-2383eb3eaf8c.png)

**Comment by telemaxx** [comment]
>  I do this mostly by using temporarily background colors to see the control borders.

good idea!

**Comment by wolfgang-ch** [comment]
> > I do this mostly by using temporarily background colors to see the control borders.
> 
> good idea!

This is the reason why you find many commented out `.setBackground(...` lines in the code

![image](https://user-images.githubusercontent.com/1283445/171034829-db3f7f3d-8fac-4ce3-b989-393d4fd94675.png)
