### ISSUE TITLE
[Bug : RxTx Crash] MyTourbook 22.3.0 HAC4pro import Crash

### ISSUE THREAD

**Issue by Tike3000** [mytourbook/mytourbook#869]
I have installed an update to version 22.3.
Since then, it has no longer been possible to import data from a HAC4pro.
As soon as you start the transfer of data to the PC in the device, MyTourbook crashes immediately

Before the update, everything worked perfectly for years.

i use the windows version

addendum:
You don't even have to start the transfer in the HAC, the program crashes a few seconds after you start the transfer on the PC

**Comment by FJBDev** [comment]
@Tike3000 
Could you attach a log to see if any useful information could help to troubleshoot this issue ?

Also, can you confirm that the last time it worked was with MyTourbook 22.2.X ?

**Comment by wolfgang-ch** [comment]
When a java app is crashing, then there is a second log (crash log file) and it's path is written in the normal log. Can you also attach the crash log file.

To see any MT log messages, you can start MT from a command line with these parameters

`"C:\Program Files\MyTourbook\mytourbook.exe" -debug -consolelog`

**Comment by wolfgang-ch** [comment]
It's a long time ago when I imported tours from my HAC4 device, however the startup for receiving data is working

![image](https://user-images.githubusercontent.com/1283445/171099535-6b133c17-5527-45af-bd57-2b3456baf3a8.png)

**Comment by Tike3000** [comment]
@FJBDev 
my last working version was AppVersion: 20.8.0.20200804-1351

Yesterday I updated from this version to the current 22.3.0 with Java Runtime, since then the program crashes as soon as I press the buttons in HAC4.

Before the update I never had a problem with the program :(

@wolfgang-ch
This window also appears for me, and the second the program crashes when I start the transmission.
I'll make a log file right away

**Comment by Tike3000** [comment]
Here is the log file, I hope it helps
[Crash_log_hs_err_pid13808.log](https://github.com/mytourbook/mytourbook/files/8802353/Crash_log_hs_err_pid13808.log)

**Comment by wolfgang-ch** [comment]
This red marked exception in the crash log ...

![image](https://user-images.githubusercontent.com/1283445/171104151-0788d06d-6387-438d-ba00-9d80321651ff.png)

... remembers me on the same issue which happened in the 2.5D map https://github.com/mytourbook/mytourbook/issues/440#issue-1095422214 and which I could fix in https://github.com/mapsforge/vtm/pull/911

But to fix it, I needed the source code for the dll and I had to reproduce it. 

I think the exception occured because the code of MT got larger and larger and then the address for accessing the PC memory was wrong because of a bug in the dll code. This may also be the reason for this RxTx (COM port) issue.

**Comment by Tike3000** [comment]
just as a hint.
I just installed the very old HAC4 software. The HAC USB/COM3/Driver interface works perfectly.
So unfortunately it really is a problem of MT.
I hope you can fix it.
Thank you so much!

**Comment by wolfgang-ch** [comment]
> But to fix it, I needed the source code for the dll and I had to reproduce it.

To create the dll, you have also have to figure out how it is build and setup a dev environment.

For the 2.5D map I needed about one week to setup a build environment and could finally build the dll. For RxTx, the code may be much more complex, also the testing by using a HAC4 device is very time intensive.

**Comment by wolfgang-ch** [comment]
> just as a hint. I just installed the very old HAC4 software. The HAC USB/COM3/Driver interface works perfectly. So unfortunately it really is a problem of MT. I hope you can fix it. Thank you so much!

As I pointed out above, I think the larger size of newer MT versions is causing this issue, older version also still work as you pointed out for 20.8. The same was also for the 2.5D map.

**Comment by Tike3000** [comment]
Thanks for the feedback.
I help myself now by downloading the raw data with the old HAC4 software and then importing it manually into MT.

The HAC4pro is an ancient device, but I haven't found a better device to date, the accuracy is unbelievable, especially the altitude difference.

Even when I asked on forums what I could use as a successor, I was told keep it until it broke.
Good old hardware

**Comment by wolfgang-ch** [comment]
Will not be fixed because of

* Very old hardware
* No source code available
* Very time intensive to fix and test it
