### ISSUE TITLE
[2D Map] Include the Esri maps in list of 2D Map Providers

### ISSUE THREAD

**Issue by stvzldn** [mytourbook/mytourbook#873]
I find the Esri maps to be useful and I think they should be added to the MyTourBook list of 2D map providers.
I like the NatGeo World, World Imagery, and World Street maps in particular.
See: https://www.esri.com/en-us/arcgis/about-arcgis/overview
Attached are my 2D map provider xml files for the above 3 maps.
[arcgis maps.zip](https://github.com/mytourbook/mytourbook/files/8840926/arcgis.maps.zip)

**Comment by wolfgang-ch** [comment]
Can be installed from the website when MT 22.6 is published
