### ISSUE TITLE
[Weather] Add "drizzle" icon for weather

### ISSUE THREAD

**Issue by stvzldn** [mytourbook/mytourbook#874]
I think MTB needs to have a icon for "Drizzle" which would show a single water droplet under the cloud (See example image below).
I log drizzle when there is a very brief light shower or foggy conditions.
![image](https://user-images.githubusercontent.com/106929478/172074303-d8b2ab57-8487-46e6-a621-d2574aa96697.png)

**Comment by wolfgang-ch** [comment]
Where is the origin of this icon?

**Comment by stvzldn** [comment]
I was not thinking fully - the first request icon was captured from my ST3 install and only meant to illustrate the request.

I have edited the MyTourBook three drop icon to a single drop which I offer below:

![Cloud_with_drop](https://user-images.githubusercontent.com/106929478/172155503-d8bd6f00-03d3-46fe-a23a-ca342a29bab1.jpg)

**Comment by FJBDev** [comment]
> Where is the origin of this icon?
> 

The icon comes from ST 3.1 (see screenshot below) but I don't think stvzldn meant to reuse this icon but instead, asking to add a similar icon that would depict a very light rain shower/drizzle

![image](https://user-images.githubusercontent.com/25235665/172165395-0b835568-850e-499c-a728-59fe092361ab.png)

**Comment by FJBDev** [comment]
As of today, in MT, there is:
- Scattered showers
![image](https://user-images.githubusercontent.com/25235665/172244201-35a84a37-9529-4e72-9b38-aa08f329c418.png)

- Showers
![image](https://user-images.githubusercontent.com/25235665/172244157-376ead89-c308-467a-855a-f311a284edc4.png)


Should this new one called "Drizzle" ?

OpenWeatherMap calles it [Drizzle](https://openweathermap.org/weather-conditions#Group%203xx:%20Drizzle)

[WWO](http://www.worldweatheronline.com/feed/wwoConditionCodes.xml) also uses "Drizzle"

WeatherAPI also uses ["Drizzle"](https://www.weatherapi.com/docs/conditions.json)

**Comment by wolfgang-ch** [comment]
MT 22.6 will have updated weather icons https://github.com/mytourbook/mytourbook/commit/4da0f1ee09060202db78a818a129a8ec70b792fb but in 22.6 there will be no new weather icons, this is postponed

![image](https://user-images.githubusercontent.com/1283445/172338585-986502c9-d1f8-431d-8dcb-ae9db00001c5.png)

 The second row is for the dark theme

**Comment by GurVJ** [comment]
IMO the icon that is missing is the one for partially cloudy weather with some rare showers, like this one :
![p12bisj](https://user-images.githubusercontent.com/64196685/172349265-54b92aa7-f328-415a-8e94-0f3a6da3b99f.jpg)
