### ISSUE TITLE
[Weather] Keep weather location in the weather log

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#876]
After analyzing the raw weather data, I maybe found the locations where the weather is logged, it is just at the beginning of `rawWeatherData`

Here is an example of 2 tours with 2 different routes which also have different weather locations

`OpenWeatherMap` do not show the name but a similar lat/lon

![image](https://user-images.githubusercontent.com/1283445/172394139-ca5fdd83-158c-4954-a458-141fbc0a5c4d.png)

**Comment by FJBDev** [comment]
I had looked at it when I added those vendors but it seemed to me that it is just the coordinates that were originally sent by the MT request, i.e., the coordinates of the [center of the tour.](https://github.com/mytourbook/mytourbook/blob/9fff029986921f1ba55291dda83a760c5b9e9fb9/bundles/net.tourbook/src/net/tourbook/weather/HistoricalWeatherRetriever.java#L53)

Here is an example with WeatherApi, note that the returned lat/lon is the same as in my request. And I know this place, there is no way there is a weather station at this location, [see for yourself](https://www.google.com/maps/place/40%C2%B015'50.4%22N+105%C2%B035'18.8%22W/@40.2644937,-105.5971692,2949m/data=!3m1!1e3!4m5!3m4!1s0x0:0xed704773f680b14d!8m2!3d40.263996!4d-105.588541)

![image](https://user-images.githubusercontent.com/25235665/172438486-24d4107e-3819-405a-95ab-4a4a68ea3a40.png)

**Comment by wolfgang-ch** [comment]
Now I see that there are two issues

1. Missing 13h and 14h log entries

This is time for the original tour

![image](https://user-images.githubusercontent.com/1283445/172538269-a06b44f4-a0f1-408d-9f5b-179703f51bdf.png)

![image](https://user-images.githubusercontent.com/1283445/172538306-5174bf17-44f1-415a-9247-ae46247e8363.png)


2. Weather location

The weather location is not in the center of the tour, I truncated the original tour and removed my outward and return journey, now you can see only the track which will be the start of Tour de Suisse 2022 next sunday https://www.tourdesuisse.ch/en/tds-2022/stage-plan/stage-1/

![image](https://user-images.githubusercontent.com/1283445/172539174-82e7a796-f5f7-4144-bcf1-862bf306779f.png)

![image](https://user-images.githubusercontent.com/1283445/172539199-5c9b5513-c460-488a-93c4-6971d34a4c7c.png)

**Comment by wolfgang-ch** [comment]
> Now I see that there are two issues
> 
>     1. Missing 13h and 14h log entries

I just saw that 14h is available, maybe 13h could also be added?

**Comment by FJBDev** [comment]
> I just saw that 14h is available, maybe 13h could also be added?

13h is not in the log because if you look at your tour, it starts at **13:38**, which is by definition closer to 14h than 13h and hence my algorithm takes the closest hour, => 14h.

**Comment by FJBDev** [comment]
>     2. Weather location
> 
> 
> The weather location is not in the center of the tour, I truncated the original tour and removed my outward and return journey, now you can see only the track which will be the start of Tour de Suisse 2022 next sunday https://www.tourdesuisse.ch/en/tds-2022/stage-plan/stage-1/

Sorry, I don't understand what you mean

**Comment by wolfgang-ch** [comment]
>but it seemed to me that it is just the coordinates that were originally sent by the MT request, i.e., **the coordinates of the [center of the tour.](https://github.com/mytourbook/mytourbook/blob/9fff029986921f1ba55291dda83a760c5b9e9fb9/bundles/net.tourbook/src/net/tourbook/weather/HistoricalWeatherRetriever.java#L53)**

The coordinates are not in the center of the tour, because `Möchaltdorf` is on the track and is very likely the weather station. Also `Ramismuhle` in my log above https://github.com/mytourbook/mytourbook/issues/876#issue-1263332787 seems also be a weather station

https://wetterstationen.meteomedia.ch/?map=Zuerich&station=069133

![image](https://user-images.githubusercontent.com/1283445/172625059-806fb565-2359-4612-aace-f648823306a9.png)

**Comment by FJBDev** [comment]
> The coordinates are not in the center of the tour, because `Möchaltdorf` is on the track and is very likely the weather station. Also `Ramismuhle` in my log above [#876 (comment)](https://github.com/mytourbook/mytourbook/issues/876#issue-1263332787) seems also be a weather station
> 

I think it will depend on each tour and also the weather vendor. In the example I gave above, it's not a weather station

**Comment by FJBDev** [comment]
But again, if you use WorldWeatherOnline, it will give you the weather station location and URL. It's just that OpenWeatherMap and WeatherApi don't give that information.

![image](https://user-images.githubusercontent.com/25235665/172734408-93fb9668-e3ff-4c02-8263-1d79cf9fadcf.png)

```
{
    "data": {
        "request": [
            {
                "type": "LatLon",
                "query": "Lat 45.53 and Lon -122.73"
            }
        ],
        "nearest_area": [
            {
                "areaName": [
                    {
                        "value": "Hazelwood"
                    }
                ],
                "country": [
                    {
                        "value": "United States of America"
                    }
                ],
                "region": [
                    {
                        "value": "Oregon"
                    }
                ],
                "latitude": "45.517",
                "longitude": "-122.523",
                "population": "0",
                "weatherUrl": [
                    {
                        "value": "https://www.worldweatheronline.com/v2/weather.aspx?q=45.531226,-122.727262"
                    }
                ]
            }
        ],
```

**Comment by FJBDev** [comment]
@wolfgang-ch 

In the case where the user uses a weather provider like WWO that contains a weather station location, do you think it would be useful to have a button on the 2D/2.5D/3D maps to display it on the map ?

![image](https://user-images.githubusercontent.com/25235665/172760678-7893d114-5ab3-4729-bc53-ed3853fa25aa.png)

**Comment by wolfgang-ch** [comment]
> do you think it would be a good feature to have a button on the 2D/2.5D/3D maps to display it on the map and be able to see where it is compared to the tour track ?

For sure but there is currently no code facility in these maps to show markers which are outside of the tour track except map bookmarks or wikipedia locations in the 2D map.

**Comment by FJBDev** [comment]
> For sure but there is currently no code facility in these maps to show markers which are outside of the tour track except map bookmarks or wikipedia locations in the 2D map.

Ah ok, good to know, I was not aware of that limitation.

**Comment by wolfgang-ch** [comment]
This is my spectator video from the Tour de Suisse 2022 https://youtu.be/RUzK4xNL9jE

![image](https://user-images.githubusercontent.com/1283445/173349056-4102395d-48aa-4001-bb36-c80b7b36e0a4.png)

![image](https://user-images.githubusercontent.com/1283445/173349633-ce5d2a23-d9ce-4040-8762-bb257e6a0d75.png)

**Comment by FJBDev** [comment]
> This is my spectator video from the Tour de Suisse 2022 https://youtu.be/RUzK4xNL9jE
> 
Beautiful spot to watch it!

**Comment by wolfgang-ch** [comment]
This track was like in my "Living Room", I knew every meter. So I think that this viewspot was one of the best to see the cycler for a longer time and is easily accessible for me
