### ISSUE TITLE
[2D Map] Include the GeoPortail maps in list of 2D Map Providers

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#883]
The french users could benefit from those maps as they offer, for free (no API key needed anymore) the "Cartes IGN" that seem to be used a lot (see original Sourceforge thread [here](https://sourceforge.net/p/mytourbook/discussion/622811/thread/714fb7df55/))

Here is the WMTS profile
[prof-geoportail-maps-2022-06-09.zip](https://github.com/mytourbook/mytourbook/files/8872817/prof-geoportail-maps-2022-06-09.zip)

![image](https://user-images.githubusercontent.com/25235665/172915338-d45bda61-4874-4f26-8751-a987c5bdac66.png)
![image](https://user-images.githubusercontent.com/25235665/172915382-78863d3f-884e-4b76-ab1d-2a8b81a48868.png)

**Comment by wolfgang-ch** [comment]
Can be installed from the website when MT 22.6 is published
