### ISSUE TITLE
[2.5D Map] Draw tour track with colors which depend on track values, e.g. elevation

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#893]

**Comment by wolfgang-ch** [comment]
It seems that I found a description from the 2.5D map creator ("I [investigated](http://http.developer.nvidia.com/GPUGems2/gpugems2_chapter22.html) [various](https://github.com/opensciencemap/vtm/blob/037c25153ba199769b0dd214c90b65e3817516c9/vtm/src/org/oscim/renderer/elements/LineLayer.java) [approaches](http://artgrammer.blogspot.de/2011/05/drawing-nearly-perfect-2d-line-segments.html) to line rendering..."), how lines are painted in the 2.5D map. 

Until now I did not understood why it is so more complex compared than using a simple line drawing command but this description tells it.

https://blog.mapbox.com/drawing-antialiased-lines-with-opengl-8766f34192dc

PDF: [Drawing Antialiased Lines with OpenGL by Mapbox maps for developers.pdf](https://github.com/mytourbook/mytourbook/files/9007555/Drawing.Antialiased.Lines.with.OpenGL.by.Mapbox.maps.for.developers.pdf)


This is another description how to draw lines with OpenGL

https://blog.scottlogic.com/2019/11/18/drawing-lines-with-webgl.html

PDF: [Drawing Lines with WebGL.pdf](https://github.com/mytourbook/mytourbook/files/9007551/Drawing.Lines.with.WebGL.pdf)

**Comment by wolfgang-ch** [comment]
The current line drawing algorithm is not perfect, there are overlapped parts in sharper curves, they disappear when zoomed in more.

The overlapped parts are also more visible when the path is less opaque

![image](https://user-images.githubusercontent.com/1283445/176833117-2431084a-558d-4524-b6f3-2ed59323dd07.png)

![image](https://user-images.githubusercontent.com/1283445/176833506-cb421c46-9d25-4583-afb8-f117747655cf.png)

![image](https://user-images.githubusercontent.com/1283445/176833523-da776544-754f-4361-9bc6-2a0acbf17529.png)

![image](https://user-images.githubusercontent.com/1283445/176833549-9fbbafbe-3397-4c96-be12-62f76ccc691e.png)

**Comment by wolfgang-ch** [comment]
After 4 weeks of learning OpenGL, get used to the 2.5D map internal drawings and lots of try and error coding, now I saw the first light, that it works :-)

![image](https://user-images.githubusercontent.com/1283445/177573827-5128899d-87a5-4bcf-8396-e795f0d9195c.png)

![image](https://user-images.githubusercontent.com/1283445/177573872-1a19b9fd-9bc7-4e3c-90c6-4027aaf0a1b8.png)

![image](https://user-images.githubusercontent.com/1283445/177573909-4dccf4f1-07dc-4e1d-94af-2580ff9ac51a.png)

![image](https://user-images.githubusercontent.com/1283445/177573945-d2028260-779e-49c9-9d5f-d7fd9e61c4e8.png)

The colors seems to be inverted

![image](https://user-images.githubusercontent.com/1283445/177575732-d8aeaaeb-adf7-4d10-a22a-cd3957daee63.png)


For sure, there are still issues, but it works (partly :-)

**Comment by wolfgang-ch** [comment]
With a few fixes, it works :-)))

![image](https://user-images.githubusercontent.com/1283445/177714593-cf38878f-8e07-48f6-adcf-09cdeeb04afa.png)

**Comment by wolfgang-ch** [comment]
Tracks can now also painted with an outline to make them better visible

![image](https://user-images.githubusercontent.com/1283445/177793796-0e8076e3-fa75-4f86-8df4-047a51e57139.png)

**Comment by telemaxx** [comment]
2D vs 2.5D

@wolfgang-ch: it seems so, that you have now understood this complicate opengl stuff...

![grafik](https://user-images.githubusercontent.com/22706487/177817427-fdd378d9-84fc-44aa-8ce3-0508c267a70a.png)

**Comment by telemaxx** [comment]
![grafik](https://user-images.githubusercontent.com/22706487/177818314-916110b7-9742-4289-83a1-9124e81c27cb.png)

if we draw  a compass rose bottom left, instead of the Hexagon in the center...

![grafik](https://user-images.githubusercontent.com/22706487/177819975-337bb9ed-5ae7-4d8e-8bec-ffc0451f59d5.png)

than the compass would turn with the map.

**Comment by wolfgang-ch** [comment]
> it seems so, that you have now understood this complicate opengl stuff...

This description https://blog.mapbox.com/drawing-antialiased-lines-with-opengl-8766f34192dc helped me a lot to understand what is going on in the two shaders but all the mathematics is still a part which I don't fully understand.

**Comment by wolfgang-ch** [comment]
> if we draw a compass rose at bottom left, instead of the Hexagon in the center it would look like this graphics:
> 
> ...
> 
> than the compass would turn with the map.

The hexagon is not a bitmap it is drawn with OpenGL commands https://github.com/mytourbook/mytourbook/blob/ws-map25-track-color/bundles/net.tourbook/src/net/tourbook/map25/HexagonRenderer.java but a compass rose could be an additional bitmap layer or you can draw it with OpenGL commands :-)

**Comment by wolfgang-ch** [comment]
> > it seems so, that you have now understood this complicate opengl stuff...
> 
> This description https://blog.mapbox.com/drawing-antialiased-lines-with-opengl-8766f34192dc helped me a lot to understand what is going on in the two shaders but all the mathematics is still a part which I don't fully understand.

What makes it also very complex is that the 2.5D map OpenGL commands are distributed over several methods and classes (files) and it's difficult to know what is currently set or not set because these commands depend on each other. 

In the above hexagon example there are also some OpenGL commands which are outsourced, e.g. `GLState..., _vbo.bind()`.
I think this is mainly done for performance reasons but makes it very difficult to understand it.

**Comment by telemaxx** [comment]
> 
> The hexagon is not a bitmap it is drawn with OpenGL commands https://github.com/mytourbook/mytourbook/blob/ws-map25-track-color/bundles/net.tourbook/src/net/tourbook/map25/HexagonRenderer.java but a compass rose could be an additional bitmap layer or you can draw it with OpenGL commands :-)

i think a bitmaplayer would zoom and move together with the map, but the compass should be fixed in size and position.
when i saw you´re Hexagon i thought this is the way to go.

This would be ideal:
https://github.com/telemaxx/vtm/blob/master/vtm-playground/src/org/oscim/test/renderer/SymbolRenderLayer.java

`it.bitmap = CanvasAdapter.getBitmapAsset("", "symbols/food/cafe.svg");`

but i am not sure where to put the "cafe.svg" graphics. i do not completely understand how to access icons and images in MT.

For the tests i use the star from MarkerToolkit. This is working. I have a star in the middle of the screen and this is not moving with the map, only turned and tilted.

This is like trekbuddy it did.

![grafik](https://user-images.githubusercontent.com/22706487/178058634-35a9011d-786a-45bc-ae86-ab5eb3092b95.png)

**Comment by telemaxx** [comment]
Only this is working, but i would prefer a svg graphics...

![grafik](https://user-images.githubusercontent.com/22706487/178059971-502fbcb7-06eb-4b3e-a5b8-e3cc204d9f14.png)

to be continued.

**Comment by wolfgang-ch** [comment]
> i do not completely understand how to access icons and images in MT.

I had to put the shader files into the net.tourbook plugin

![image](https://user-images.githubusercontent.com/1283445/178093356-19dcac96-bc3a-41a6-98f4-4a852e3b01b6.png)


Here you can see how to access the shader file

https://github.com/mytourbook/mytourbook/blob/519e2b1f9298b123a545921bd269d2edd2e3f203/bundles/net.tourbook/src/net/tourbook/map25/renderer/GLShaderMT.java#L155-L167

**Comment by wolfgang-ch** [comment]
Art can now be created by setting the outline width

![image](https://user-images.githubusercontent.com/1283445/178097267-aeb04382-d481-4d20-a88e-f5b787d4a82b.png)

![image](https://user-images.githubusercontent.com/1283445/178097272-fe7ceb48-960e-404c-9779-ed8c10662fb1.png)

**Comment by telemaxx** [comment]
Nice Artwork!

i have tried youre tips.

For my tests i put 2 files in the shader dir:

![grafik](https://user-images.githubusercontent.com/22706487/178102884-7cb4b26c-8d93-4a62-bcb6-de22a1bd08fe.png)

when you're glsl is active in my program the content of that file is written correctly to console,
but when my svg or a.txt is active, only null

![grafik](https://user-images.githubusercontent.com/22706487/178103210-b9fc90bd-6101-432f-8916-e1abbad95ead.png)

![grafik](https://user-images.githubusercontent.com/22706487/178103296-61f69ead-fdce-4a20-af8e-f50230486fab.png)

do i have to register new file somewhere?

**Comment by wolfgang-ch** [comment]
The `AssetAdapter` is accessing the vtm plugin, you have to use 

```
       final String path = "shaders/YOUR-FILENAME";  
       final URL bundleUrl = TourbookPlugin.getDefault().getBundle().getEntry(path); 
       String fileURL = null; 
       try { 
          fileURL = NIO.getAbsolutePathFromBundleUrl(bundleUrl); 
      ...
```

**Comment by telemaxx** [comment]
i think i had it done that way. havent?

```
String file = "a.txt";
final String path = "shaders/" + file;
final URL bundleUrl = TourbookPlugin.getDefault().getBundle().getEntry(path);
String fileURL = null;
System.out.println("bundlepath = " + bundleUrl.getPath() + " " + AssetAdapter.readTextFile(bundleUrl.getPath()));

try {
         fileURL = NIO.getAbsolutePathFromBundleUrl(bundleUrl);
 catch (final IOException e1) {
         e1.printStackTrace();
}

```
but anyhow i play now with markertoolkit.

![grafik](https://user-images.githubusercontent.com/22706487/178109914-a71d8ba3-1383-4c34-b424-cc069aa88d0d.png)

sometimes when zooming and dragging, i lost orientation.
i think than would an optional compass helpful.

**Comment by telemaxx** [comment]
Compass Arrow is nicer.

![grafik](https://user-images.githubusercontent.com/22706487/178117919-171a5197-7946-4d83-9f61-a35a08e1c198.png)

**Comment by telemaxx** [comment]
Ok, that was the problem.
Now i can load a svg graphics, but it is to tiny. up scaling the svg with inkscape doesn't change it in MT.

![grafik](https://user-images.githubusercontent.com/22706487/178134437-796e99bd-6b50-48a6-b2cb-61238fd923c0.png)

using MarkerToolkit seems to be easier and i can easily change color and size.

**Comment by wolfgang-ch** [comment]
Support for opacity in the gradient colors

![image](https://user-images.githubusercontent.com/1283445/178939593-171eb39e-943d-4088-ab3d-427a55ca12cc.png)

![image](https://user-images.githubusercontent.com/1283445/178939632-a736d821-6c5c-41ed-8efa-b8d5339b51ae.png)

**Comment by telemaxx** [comment]
map25 toolbar filling with cool stuff.

@wolfgang-ch: Last week i tried your ws-map25-track-color branch.
since commit 8e4813c i have the problem that the track is only shown when "direction arrows" are on.
when i switch arrows off, i dont see the track. also parts of the map are missing and i get errors in the console:

```
18:56:32,429 [LWJGL Application] ERROR GLUtils - org.oscim.renderer.MapRenderer: finish: 	glError GL_INVALID_OPERATION (1282)
18:56:32,763 [LWJGL Application] ERROR GLUtils - org.oscim.renderer.MapRenderer: finish: 	glError GL_INVALID_OPERATION (1282)
18:56:33,111 [LWJGL Application] ERROR GLUtils - org.oscim.renderer.MapRenderer: finish: 	glError GL_INVALID_OPERATION (1282)
```

commit 519e2b1 is OK

**Comment by wolfgang-ch** [comment]
When I run the last commit then it works with my external screen 2560x1440 which I use in my home office

![image](https://user-images.githubusercontent.com/1283445/179153369-64e9177f-c432-4558-af1e-fd10f56dc170.png)


When I run it with my notebook 4k screen then I get this error

![image](https://user-images.githubusercontent.com/1283445/179153550-d93c3b6f-15f3-460c-b7db-d9002e3b8fe9.png)

@telemaxx Which OpenGL version/vendor are you using?

**Comment by wolfgang-ch** [comment]
After fixing this issue https://github.com/mytourbook/mytourbook/commit/77d32cf82627eac01c9605258ae6dca5b93b646b and it is working now with the 4k display, Linux is reporting a new issue

![image](https://user-images.githubusercontent.com/1283445/179157926-9320ec8d-e894-479b-9bb7-de397378d5af.png)

**Comment by wolfgang-ch** [comment]
Linux is now also fixed https://github.com/mytourbook/mytourbook/commit/bb4f9245ff4bc5eaf26a1d9d53fabbab4b8f1d61

![image](https://user-images.githubusercontent.com/1283445/179161182-0230809c-9b0b-4543-80d8-5bc72f0ae9c8.png)

**Comment by wolfgang-ch** [comment]
After fixing these issues, the NVIDIA compiler seems to be more tolerant

**Comment by telemaxx** [comment]
>@telemaxx Which OpenGL version/vendor are you using?

![grafik](https://user-images.githubusercontent.com/22706487/179163475-c4609d26-51f7-4680-a73c-62b21697719a.png)

with the commit from today its fine!

![grafik](https://user-images.githubusercontent.com/22706487/179163322-dc6c3065-6560-4ab5-acee-f685da24232d.png)

**Comment by wolfgang-ch** [comment]
> map25 toolbar filling with cool stuff!

99% of the code is copied/reused from the 3D map

**Comment by wolfgang-ch** [comment]
The different track colors are now saved in the track option profiles

![image](https://user-images.githubusercontent.com/1283445/179358069-0b989ed6-9151-4e50-ac44-854bb5ab773a.png)


![image](https://user-images.githubusercontent.com/1283445/179358073-245fdff8-29e8-4f83-ab9b-4647a3ca92f2.png)


![image](https://user-images.githubusercontent.com/1283445/179358077-13995432-11c4-4988-99f9-8c1a8dc7fc54.png)

**Comment by wolfgang-ch** [comment]
2.5D and 3D map are using the same color profiles, when both maps are displaying the same tour values, e.g. elevation then both have the same colors

![image](https://user-images.githubusercontent.com/1283445/179385656-897564f2-a1c0-43a2-be6d-39e5cbbbeb7f.png)

**Comment by wolfgang-ch** [comment]
A video is displaying the same color profiles better

https://user-images.githubusercontent.com/1283445/179386432-e9926cb3-184e-440f-a64b-e174e97de641.mp4

**Comment by wolfgang-ch** [comment]
Track legend is now available

![image](https://user-images.githubusercontent.com/1283445/179536576-4064b256-f02f-41be-a985-be50b2b5382e.png)

**Comment by wolfgang-ch** [comment]
Depending on the map and track colors, the legend units looks good or ugly, this can now be customized

![image](https://user-images.githubusercontent.com/1283445/179930154-491778d5-3a1d-4e8b-94f0-2725151fff17.png)

**Comment by wolfgang-ch** [comment]
Luminance can now applied to the map

https://user-images.githubusercontent.com/1283445/180606632-eae735ea-5ce8-46e3-8d54-a20f9e060b13.mp4
