### ISSUE TITLE
[2.5D Map] Draw Compassrose

### ISSUE THREAD

**Issue by telemaxx** [mytourbook/mytourbook#896]
Sometimes when turning moving tilting and scaling in the map, i am lost in space.

Then a compassrose would be cool.

![grafik](https://user-images.githubusercontent.com/22706487/178136832-0321b480-b366-4e65-b30f-c61c36739ce8.png)

i know @wolfgang-ch  is also working on map25, doing crazy open gl-things.
So i wait with my PR until Wolfgang is ready with his improvements, to avoid conflicts.

**Comment by wolfgang-ch** [comment]
I tested the rotation of a bitmap https://github.com/mytourbook/mytourbook/commit/26904f52d61c96d90dc75911d3654e02b1cd355b but the math needs some adjustments

https://user-images.githubusercontent.com/1283445/180791641-16b82e08-2387-41d0-bc55-4ad8f615dd58.mp4

**Comment by telemaxx** [comment]
I thought already the new legend could be a good startpoint.

we should maybe use the same graphic like in map3:
https://github.com/nasa/World-Wind-Java/blob/master/WorldWind/src/gov/nasa/worldwind/layers/CompassLayer.java

images/notched-compass.dds

notched-compass.png I found also

**Comment by telemaxx** [comment]
![https://infosys.ars.usda.gov/svn/code/weps1/branches/weps.gui-subregion/lib/Worldwind/src/images/notched-compass.png(url)

**Comment by telemaxx** [comment]
![](https://infosys.ars.usda.gov/svn/code/weps1/branches/weps.gui-subregion/lib/Worldwind/src/images/notched-compass.png)

**Comment by wolfgang-ch** [comment]
After many try and errors, the "rose" is now rotating at the correct location. 

This is the code for the video

![image](https://user-images.githubusercontent.com/1283445/182015198-47048800-a23f-4300-aaf1-82ec5f8eb3b6.png)


https://user-images.githubusercontent.com/1283445/182015301-aa8d7bc9-998e-450c-9af7-09095074228a.mp4

**Comment by wolfgang-ch** [comment]
Implemented in https://github.com/mytourbook/mytourbook/commit/5d4864665c5df31ba078c91fc72ba2e4d351dfd1

https://user-images.githubusercontent.com/1283445/182037288-55cbae86-35bd-4fd0-a7c8-57a4f18f240c.mp4

**Comment by telemaxx** [comment]
YES!
