### ISSUE TITLE
[Tour Editor] Change lines in TourEditor weather

### ISSUE THREAD

**Issue by Frans2222** [mytourbook/mytourbook#897]
Future request:
Like in notes, it would be nice if one could alter the number of lines for remarks in the Weather section. 
The current 6 lines takes a lot of space on my screen, where 1 line is fine for me. Gives me a better overview and saves me a lot of downscrolling.
Thanks!

**Comment by wolfgang-ch** [comment]
The number of lines in the weather field was increased to better see the automatically added weather log but I agree with you that the number of lines should be customizable

**Comment by wolfgang-ch** [comment]
Merged in https://github.com/mytourbook/mytourbook/commit/75c94a12021327bb9f7b92e09016d170a47fb864

**Comment by Frans2222** [comment]
Thanks Wolfgang, spinner weather looks fine!

Greetings, Frans

**Comment by wolfgang-ch** [comment]
This feature was implemented by Frederic, I just merged it.
