### ISSUE TITLE
[Tour Export TCX] Speed unit in km/h and not in m/s ?

### ISSUE THREAD

**Issue by mff73** [mytourbook/mytourbook#903]
### What happened ?

I exported for the first time a tour into a TCX format.
And speed values are in km/h in the file. and i think they should be in m/s to be properly imported in third party apps which doesn't recalculate the speed ?

Am i wrong ? is there a setting in MTB i forgot to set ?
Thanks

TCX example :
![image](https://user-images.githubusercontent.com/50132146/182379822-c38fcd01-f524-4035-9a95-433c22400da0.png)

MTB value (coherent)
![image](https://user-images.githubusercontent.com/50132146/182380092-ad990461-6f9b-4adb-acae-af005562c6cf.png)

Interpreted speed in Quantified-self.io
![image](https://user-images.githubusercontent.com/50132146/182381842-51d1f561-0197-4875-9a04-b894e7ebc7a2.png)

In Sports-Tracker (aka in SuuntoApp as well) after TCX transfer with Syncmytrack
![image](https://user-images.githubusercontent.com/50132146/182382632-92352b5d-3788-47eb-8025-facbaa816251.png)

### Version

22.6.1

### System

Windows

**Comment by FJBDev** [comment]
@mff73 

Indeed, while the [schema](https://www8.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd) doesn't specify the units of the speed values, it seems like it should be in meters per second ([Source 1](https://forums.garmin.com/apps-software/mobile-apps-web/f/garmin-connect-web/55379/units-of-speed-values-in-tcx), [Source 2](https://github.com/pcolby/bipolar/issues/74))

I will try to fix that for the upcoming MT version

**Comment by FJBDev** [comment]
@mff73 

See my PR [here](https://github.com/mytourbook/mytourbook/pull/904)

**Comment by mff73** [comment]
cool, thanks
