### ISSUE TITLE
[Bug : Tour Book] Fields not updated after Time Slices deleted

### ISSUE THREAD

**Issue by GurVJ** [mytourbook/mytourbook#910]
### What happened ?

Hello,

I found an issue this morning when I wanted to reduce the duration of my tour (forgot to press Stop button).
In the editor view, time slices tab, I've deleted all the points I wanted to remove and it worked correctly.
Unfortunaltely, back to the Tour Book view the duration information had not been updated (and the related fields like average speed).
So at this point, the information is not the same in the Tour Book view and the Editor view.
![MTB_ModifDuration](https://user-images.githubusercontent.com/64196685/183460509-9daedc61-b501-4928-b5a5-6b37c2413735.jpg)

### Version

22.6.1

### System

Windows

**Comment by FJBDev** [comment]
>>. In the editor view, time slices tab, I've deleted all the points I wanted to remove and it worked correctly. Unfortunaltely, back to the Tour Book view the duration information had not been updated (and the related fields like average speed).

Which feature did you use to delete those points ?

In 22.6, I fixed a similar issue that you can read about in the[ 22.6 release notes](https://mytourbook.sourceforge.io/mytourbook/index.php#v22.6.0)

_Tour Editor (Frederic)

    Fixed a bug where the recorded and paused times were not recomputed when using the feature "Delete Time Slices and Remove Time"_

**Comment by GurVJ** [comment]
I used the third Option
![image](https://user-images.githubusercontent.com/64196685/184091686-9c61df29-e884-4d51-ab55-344640a0ed6d.png)

The issue you fixed seems to work correctly as the data in the editor are correct.

**Comment by FJBDev** [comment]
> I used the third Option ![image](https://user-images.githubusercontent.com/64196685/184091686-9c61df29-e884-4d51-ab55-344640a0ed6d.png)

Thanks, I will investigate this issue

> 
> The issue you fixed seems to work correctly as the data in the editor are correct.

Good to know!

**Comment by FJBDev** [comment]
@GurVJ 

I have investigated the issue you reported but I see a different behavior.

When I delete a time slice with the third option, the recorded time gets updated correctly in the Tour Data Editor View (In this case, it removes 1s) and indeed, in the TourBook, the recorded time is still the same, see my screenshot below:
![image](https://user-images.githubusercontent.com/25235665/184411981-7aca7efd-3fc9-495c-93c0-db38bb7aee18.png)


Once I save the tour, then the recorded time in the tourbook is correct.

![image](https://user-images.githubusercontent.com/25235665/184412081-77025946-9d0a-43a2-aaf7-23d02aa38643.png)


Am I missing something ?

**Comment by GurVJ** [comment]
No you'not missing something. But the behaviour of your second step has been different for me as saving the tour did not updated the tourbook recorde time.
I will try to reimport the tour and delete times slice again to check if the it was a "one shot bug". I'll tell you.

**Comment by GurVJ** [comment]
Well, I tried again and it worked perfectly ... I suppose I encountered a problem when saving the modified tour. the first time.

**Comment by FJBDev** [comment]
> Well, I tried again and it worked perfectly ... I suppose I encountered a problem when saving the modified tour. the first time.

Good to know, thanks for double checking
