### ISSUE TITLE
[Cloud Service] Implement an alternative to Heroku

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#915]
Per the Heroku announcement [here ](https://blog.heroku.com/next-chapter#focus-on-mission-critical)to discontinue the free dyno apps that [MT is using for multiple cloud services integration](https://github.com/mytourbook/mytourbook/blob/cdb5a294f3508eee5726822124c5f4e2410921b2/bundles/net.tourbook.cloud/src/net/tourbook/cloud/oauth2/OAuth2Constants.java#L24), I will be looking at migrating the MT integration node.js app to another free node.js service.

`Thank you for being a Heroku user. Starting November 28, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available.`

[Here ](https://geshan.com.np/blog/2021/01/free-nodejs-hosting/) are some possible free alternatives

**Comment by FJBDev** [comment]
I have chosen [Cyclic](https://app.cyclic.sh/#/) and the migration was successful

**Comment by FJBDev** [comment]
Implemented in this [commit](https://github.com/mytourbook/mytourbook/commit/743ec8aa99fcb64a930b6cd337df939284f2211c)

**Comment by FJBDev** [comment]
The free Heroku apps will start being deprecated `Starting November 28, 2022,`

**Comment by wolfgang-ch** [comment]
Tomorrow I'll prepare `22.11`

**Comment by FJBDev** [comment]
I am not able to reproduce it locally and also, it works on Github, see last build [here](https://github.com/mytourbook/mytourbook/actions/runs/3443289956)

You said it fails when building `22.11`d but I see this, is it normal ?
Non-resolvable parent POM for net.tourbook:net.tourbook.tests:**22.8.0**-SNAPSHOT

Did you try to remove the tests and ui.tests module since they are not used when building a new version of MT?

**Comment by wolfgang-ch** [comment]
It was my fault 😮 

When I did a search and replace of the old version number 22.8.0 with 22.11.0, the test projects were closed, so the version number was not updated
