### ISSUE TITLE
[Import] Can't import a lot of my CRP Files

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#927]
### Discussed in https://github.com/mytourbook/mytourbook/discussions/924

<div type='discussions-op-text'>

<sup>Originally posted by **ovahead** September  4, 2022</sup>
As I wrote before on Sourceforge I can't import some of my CRP Files (CicloTour/HAC4). That file that Frederic used was okay. But I think he didn't saw the other file:
220322.crp is one of the files that won't import.

Sorry Frederic for wrote that in the discussion where the thread was for Fit Files. 

[220322.zip](https://github.com/mytourbook/mytourbook/files/9485537/220322.zip)

![MyTourbook-Tour-Protocol](https://user-images.githubusercontent.com/112829463/188334822-3c9c37f8-2b1b-44ab-8927-1d21e0ba92a1.jpg)

Even if I can import a file all values without distance and the total time are different. Starts with the moving time. </div>

**Comment by FJBDev** [comment]
Issue fixed and tested/verified by the user [here](https://github.com/mytourbook/mytourbook/discussions/924#discussioncomment-3656250)
