### ISSUE TITLE
[2D Map] Can't download SRTM-Data

### ISSUE THREAD

**Issue by cyc1ingsir** [mytourbook/mytourbook#928]
MT-Version: 22.8.0
Linux (Opensuse-Tumbleweed)

Cycling in a completely different location at the moment, I realized, that "Adjust Evavluation" isn't working.   
![Screenshot_20220909_204524](https://user-images.githubusercontent.com/2297037/189430362-d2689bcc-0b31-4c55-8624-a10fd5a49a3d.png)

I did create a NASA EARTHDATA account a few years ago and this validates just fine.   
![Screenshot_20220909_205056](https://user-images.githubusercontent.com/2297037/189430355-b0ac9955-617d-40a0-8044-332d800e202c.png)

However, there must be a setting/option I haven't discovered yet. The srtm3 data I've found on the default location is 12 years old.   
![Screenshot_20220909_212443](https://user-images.githubusercontent.com/2297037/189430347-63071ec5-86da-4a42-96bd-1b81c8752c3d.png)

Looking on the new location, I just created, only the empty zip files for which the error was reported have been created:
```bash
ll /opt/SRTM_Data/srtm3/
-rw-r--r-- 1 m users 0  9. Sep 20:40 N44E006.SRTMGL3.hgt.zip
-rw-r--r-- 1 m users 0  9. Sep 20:53 N44E007.SRTMGL3.hgt.zip
-rw-r--r-- 1 m users 0  9. Sep 20:53 N45E006.SRTMGL3.hgt.zip
-rw-r--r-- 1 m users 0  9. Sep 20:53 N45E007.SRTMGL3.hgt.zip
```

There is this "strange" map provider which seems to cause the trouble (just guessing). But on the other hand, it seems to be a build in one, if there is such a thing. The option to delete the provider is grayed out/disabled for this one.   
![Screenshot_20220909_210622](https://user-images.githubusercontent.com/2297037/189430351-f25e7436-3211-4ccc-9dbd-a4a872827f64.png)

I wonder, why it tries to download the data via HTTP instead of HTTPS. I assume, there is a left over from 2010 somethere in the settings.

Any help would be very much appreciated.

**Comment by cyc1ingsir** [comment]
As I can't no longer import new workouts after today's update to version 22.8, I reverted to 21.6.1 for the time being.
Couldn't spot a cause, when inspecting the log after starting MT from the console. It just freezes after clicking the import button.
Maybe, it's related.

**Comment by wolfgang-ch** [comment]
I had the same error

![image](https://user-images.githubusercontent.com/1283445/189474057-e1f1db76-ce05-4d10-b814-c411c897ce77.png)

This is now fixed in https://github.com/mytourbook/mytourbook/commit/ae385c8ac883b69a17af85055052abb21475d96a

![image](https://user-images.githubusercontent.com/1283445/189474004-aa23bcdc-10e5-4c36-b02e-73484b4b43e8.png)
