### ISSUE TITLE
[Tour] Duplicate a tour with random tour ID

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#937]
### Discussed in https://github.com/mytourbook/mytourbook/discussions/935

<div type='discussions-op-text'>

<sup>Originally posted by **gregoryxxxxxx** September 21, 2022</sup>
Hey! Y'all moved! 

I know there was talk of how to do this in the past - and I am still doing a duplicate by using the "unique ID" thing. But... is there any option for duplicating an existing tour that isn't manual at this point? Or still the same as past? 

Thx! </div>

**Comment by wolfgang-ch** [comment]
This feature will be available in the next version for any tours not only for manually created tours

![image](https://user-images.githubusercontent.com/1283445/222945336-17111d08-f260-4a50-a185-3c014e456ba9.png)

This warning will be displayed

![image](https://user-images.githubusercontent.com/1283445/222945373-da641ffe-b885-4575-9499-8481c0588636.png)

**Comment by gregoryxxxxxx** [comment]
Much appreciated, @wolfgang-ch !!
