### ISSUE TITLE
Wind Direction Bug in MTs Tour Info?

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#942]
### Discussed in https://github.com/mytourbook/mytourbook/discussions/940

<div type='discussions-op-text'>

<sup>Originally posted by **ovahead** October  1, 2022</sup>
After importing weather data the Tour Info shows e.g. 25° WSW but the Tour Editor NNO 25°, or another example Tour Info 16° SSO, Tour Editor NNO 16°</div>

**Comment by FJBDev** [comment]
@ovahead
Can you fill all the necessary details please ? MT version used, screenshots, scenario to reproduce etc...
It helps us investigate and fix any possible issue more efficiently.

Thanks!
Frederic

**Comment by ovahead** [comment]
Sorry...

I used MyTourbook 22.08.0 20220915-1631. Weather Data imported with "Weather API". Tour Editor information appear correctly. Concerns only Tour Info compass point information.
![screen-1](https://user-images.githubusercontent.com/112829463/194912638-68cc267f-a67a-4c92-b0d0-25948128e483.jpg)
![screen2](https://user-images.githubusercontent.com/112829463/194912661-6a38b22d-0527-45a6-bc13-09bd6e1005a7.jpg)

**Comment by FJBDev** [comment]
@ovahead 

Thanks for all the details.
I was able to reproduce the issue. There is a display bug that will display the wrong wind's cardinal value in the Tour Info tooltip. I have a fix that should be in the next version of MyTourbook.


![image](https://user-images.githubusercontent.com/25235665/194943127-faa155fd-03b5-45d1-b19b-ab38c944aa21.png)
