### ISSUE TITLE
[Easy Import] Set elevation up/down values from SRTM data

### ISSUE THREAD

**Issue by bern6** [mytourbook/mytourbook#945]
### What is missing ?

Optional up/down is a nice feature, but why not enable/disable in 'easy import config' instead of 'tour editor', like the cadence (spm/rpm),

In my case :
Garmin edge 1030 : disable
Garmin forerunner 235 : enable
Garmin edge 820 : disable

Thanks

**Comment by wolfgang-ch** [comment]
> Optional up/down is a nice feature, but why not enable/disable in 'easy import config' instead of 'tour editor', like the cadence (spm/rpm),

What do you mean with "Optional up/down", can you create a screenshot ?

**Comment by bern6** [comment]
sorry, i was talking about that,

"Recompute the elevation up/down values when tour is saved is now optional, this can be enabled/disabled in the tour editor options"

And the watch which calculates the elevation by GPS, adjust the elevation automatically with SRTM.

**Comment by wolfgang-ch** [comment]
Duplicate of https://github.com/mytourbook/mytourbook/issues/824
