### ISSUE TITLE
[App Menu] Replace/rename the Forum menu entry

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#951]
### Discussed in https://github.com/mytourbook/mytourbook/discussions/950

<div type='discussions-op-text'>

<sup>Originally posted by **FJBDev** October 22, 2022</sup>
Since the [Sourceforge forum is discontinued](https://sourceforge.net/p/mytourbook/discussion/622811/thread/10e08732d0/), maybe that menu entry should be removed ? or replaced by the [GitHub Issues](https://github.com/mytourbook/mytourbook/discussions) link ?

![image](https://user-images.githubusercontent.com/25235665/197316308-393f6511-73bc-4d0b-8ae1-296781904e7f.png)
</div>

**Comment by wolfgang-ch** [comment]
`Forum...` should be replaced/renamed with a Github link and a second link should be added:

* `Discussion`
* `Feature Requests and Bugs`

**Comment by FJBDev** [comment]
Fixed in [this PR](https://github.com/mytourbook/mytourbook/pull/959)

![image](https://user-images.githubusercontent.com/25235665/201229058-74e71ee3-fdae-4c42-85f1-8eddf5fda216.png)
