### ISSUE TITLE
[Geo Search] Select tours in other views which are selected in the 2D Map

### ISSUE THREAD

**Issue by wolfgang-ch** [mytourbook/mytourbook#966]
### Discussed in https://github.com/mytourbook/mytourbook/discussions/965

<div type='discussions-op-text'>

<sup>Originally posted by **mff73** November 16, 2022</sup>
Hello,
i use the geo search function, and when i arrives to a limited numbers of found tours, is it possible to select them physically (all) for example to add tags ?
Here i selected 33 tours
![image](https://user-images.githubusercontent.com/50132146/202140380-18008dda-5987-417b-b8b6-f8d484277730.png)

But right click doesn't give anything, and tour list is not updated with found tours ?

Thanks.</div>

**Comment by wolfgang-ch** [comment]
Select tours in `Tour Book` view when `TourEventId.TOUR_SELECTION` is fired

**Comment by mff73** [comment]
thanks Wolfgang to create a feature request from my question (hence the answer is that it is not possible yet 😁)
to precise the process i followed according to the previous screenshot.
i used geo search selecting a map area (just one box)
MTB found 189 tours
![image](https://user-images.githubusercontent.com/50132146/202227627-ea0570d0-cbda-435a-a518-a3674b0d4bc8.png)

then i mouse-over the map on a specific path (bottom right), and MTB shows me a limited list of tours
![image](https://user-images.githubusercontent.com/50132146/202228391-502e8db1-f912-44fb-90cf-3b104d89e03d.png)

and then i could click on those second tour list (18 tours), and it should select them in tourboob view, right ?
![image](https://user-images.githubusercontent.com/50132146/202228956-d232c57c-751f-4b5f-a93b-cdac15a4a1bc.png)

**Comment by wolfgang-ch** [comment]
> Select tours in `Tour Book` view when `TourEventId.TOUR_SELECTION` is fired, like in the `Tour Chart` view

Yes

**Comment by wolfgang-ch** [comment]
This feature is now implemented in https://github.com/mytourbook/mytourbook/issues/1050
