### ISSUE TITLE
MacOS "Schnell bearbeiten" führt zu öffnet Fenster mit Fehlern.

### ISSUE THREAD

**Issue by Marty56** [mytourbook/mytourbook#969]
### What happened ?

OS: MacOS Ventura
MyTourBook Version: Version: 22.11.0

Wenn man in der Touren Liste eine Tour doppelklickt wird ja die Funktion "schnell bearbeiten" gestartet, die man auch im Rechtsklick Context aufrufen kann. 

Es öffnet sich ein Fenster, bei dem nicht mehr gescrollt werden kann und dem die Unterpunkte "Tour/Ereignis" und "Datum/Zeit/Entfernung/Dauer" fehlen. Das Fenster beginnt auch mit den Unterpunkten "Persönliche Angaben". 
Die Funktion "Tour bearbeiten" aus dem Context Menü funktioniert.

![Bildschirm­foto 2022-12-01 um 09 48 11](https://user-images.githubusercontent.com/8623789/205008659-5ed8f9ac-a35d-4af7-9fb2-44852dae5a38.jpg)

### Version

 22.8.0 und 22.11.0

### System

OSX

**Comment by wolfgang-ch** [comment]
Den Dialog sollte man vergrössern/verkleinern können um den gesamten Inhalt anzuzeigen

![image](https://user-images.githubusercontent.com/1283445/205013244-5d86887d-1b06-49a4-90e6-4cc551c188a8.png)

**Comment by Marty56** [comment]
Danke für den Hinweis!
Super das funktioniert!! 

Und ich freue mich wirklich, dass die MacOS Version wieder etwas unterstützt wird.
Auch nochmal explizit auch ein großes DANKE!
