### ISSUE TITLE
[Bug : TourenImport] Fenster bleibt weiß

### ISSUE THREAD

**Issue by Laul-de** [mytourbook/mytourbook#982]
### What happened ?

Hallo.
Das Import Fenster bleibt weiß; wenn man an die "bekannte Stelle" mit der Mouse geht, kommt aber die Info-Box zum TourenImport und der Touren-Import funktioniert auch problemlos. Somit ist es vermutlich nur ein Anzeigeproblem.
Im Einsatz ist 22.6.1 unter Ubuntu 22.04.1 LTS.
Das Problem bestand auch schon mit früheren Versionen von MT; aber erst seit der Migration auf Ubuntu 22.04 LTS; unter Ubuntu 18.04 LTS war alles ok.

Ist dieses Problem bekannt bzw. "irgendwie" lösbar?

Ciao
Laul.de

### Version

22.6.1

### System

Linux

**Comment by wolfgang-ch** [comment]
Könntest du einen Screenshot erstellen die das Problem zeigt

**Comment by FJBDev** [comment]
It looks to me to be [this issue](https://sourceforge.net/p/mytourbook/discussion/622811/thread/af9e977f4c/) no?

**Comment by wolfgang-ch** [comment]
This https://sourceforge.net/p/mytourbook/discussion/622811/thread/af9e977f4c/#e71e may solve the problem

**Comment by Laul-de** [comment]
Hi Wolfgang.

The issue seems to be the same.
No, the workaround doesn't solve the problem. Sorry,
I made the change to 0,0 secs; restart the application and the import
screen stays white.

The only way to get the context menu is to put the mouse to the place
where the button for easy import should be and then rightclick.
My individual browser is epiphany; disabling the checkbox and restarting
the application was not successful.




Ciao
Ulli

Am 31.01.23 um 06:38 schrieb Wolfgang Schramm:

**Comment by FJBDev** [comment]
I am seeing the same issue today with MT 22.11.0 and Win 10 but it seems to be random, I can't reproduce it all the times

![image](https://user-images.githubusercontent.com/25235665/215891402-8fe91969-a537-4111-a5ce-ee6b9dc53d80.png)

Also, I don't see any log entries

**Comment by wolfgang-ch** [comment]
Implemented an alternative easy import UI https://github.com/mytourbook/mytourbook/issues/1065
