### ISSUE TITLE
[Feature : Tags Edition] Picture Field

### ISSUE THREAD

**Issue by GurVJ** [mytourbook/mytourbook#984]
### What is missing ?

Hello,

Would it be possible to add a "picture field" in the Tag Edition window ?
The aim of this is to add more information about the gear used (shoes for example) by having a picture of it.
The user would have the ability to download or not a picture file to complete the description.
Thanx

**Comment by FJBDev** [comment]
I think this is a duplicate of [this one](https://github.com/mytourbook/mytourbook/issues/805) (for which I am currently working on)

**Comment by GurVJ** [comment]
You're right ! I had not seen this Enhancement Request before you mentionned it ...
Sorry about it.
