### ISSUE TITLE
[Feature : TourBook View] Add the ability to change pause types individually and in bulk

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#988]
### What is missing ?

[In 22.1](https://mytourbook.sourceforge.io/mytourbook/index.php#v22.1.0) was added the display of auto-pauses vs user pauses

While the pauses for the tours in FIT format I imported after upgrading to 22.1 show correctly (i.e.: Red and white for user pauses vs black and white for auto-pauses), the pauses for all the tours that are **NOT** in FIT format (i.e.: TCX, fitlog, fitlogex, suunto sml/xml/json.gz) show as auto pauses as it is the [default behavior](https://github.com/mytourbook/mytourbook/blob/9ac7297bbae57d1b0583fe73fc61b294d991555d/bundles/net.tourbook/src/net/tourbook/ui/tourChart/TourChart.java#L2301) for the pause type coming from the formats that don't indicate the pause type (user vs auto).

[Here is an example of a TCX file](https://github.com/mytourbook/mytourbook/blob/main/bundles/net.tourbook.tests/src/test/device/garmin/tcx/files/2021-01-31.tcx) for which I know the pause was triggered by me but it shows as an auto-pause in MT and, as of today, there is no possibility to change it to a user-pause

![image](https://user-images.githubusercontent.com/25235665/216190057-4d5190c4-6ace-4add-ae61-2cf28053bcfe.png)

Proposal:

- Add the ability to change the pause type of all the pauses for 1 or several tours from the context menu
![image](https://user-images.githubusercontent.com/25235665/216190499-28cacfdd-ff33-4adc-94bb-9b959c0c1577.png)

- Add the ability to change the pause type for each specific pause from a contextual menu in the Tour Pauses view

![image](https://user-images.githubusercontent.com/25235665/216190668-2f9af74b-4ec9-4e80-b384-c9aa7cc4b16b.png)

**Comment by stvzldn** [comment]
Might also be nice to be able to consolidate pauses which occur within a small radius and within a small time period which were caused by brief movements at a stop.  This would remove the start stop travel distance and put all time into the paused time.

**Comment by FJBDev** [comment]
> Might also be nice to be able to consolidate pauses which occur within a small radius and within a small time period which were caused by brief movements at a stop. This would remove the start stop travel distance and put all time into the paused time.

Can you create a feature request for that since it's different than this one?
